### ISSUE TITLE
403 Client Error: Forbidden for url

### ISSUE THREAD

**Issue by Xiaowang78** [dipu-bd/lightnovel-crawler#1003]
www.mtl.com seem tp have bugs again. I can't make epub from there. 
I use discord bot. 
![Screenshot_2021-08-06-16-37-21-050_com discord](https://user-images.githubusercontent.com/77606342/128590738-23c7c056-e370-4b82-bf16-47700d602ad1.png)

**Comment by dipu-bd** [comment]
This bug is a common one. Check #948 #928 #968 

I should probably change the error message into something more meaningful.

**Comment by Xiaowang78** [comment]
So I have to wait? It can't fixed?

**Comment by dipu-bd** [comment]
No sorry, this error can not be fixed for bots. But downloading in desktop works though.

**Comment by Xiaowang78** [comment]
Well I'll try with my desktop then. Do I need to install on my desktop?

**Comment by dipu-bd** [comment]
It is recommended to use the python package, if you know how to do the setup. Otherwise, you can use the exe versions. You can find the links in the README.md file.
