### ISSUE TITLE
id.mtlnovel.com 403 Client Error: Forbidden for url 

### ISSUE THREAD

**Issue by fadhilm293** [dipu-bd/lightnovel-crawler#1004]
**Describe the bug**
Log 
https://gist.github.com/hkgistbot/6d8619a7ec9f779e0db57305c9c4d195

**Let us know**

Where did you find this bug?
 Telegram Bot

What is your novel URL?
https://id.mtlnovel.com/the-strongest-qi-refiner/

**Comment by dipu-bd** [comment]
#1003
