### ISSUE TITLE
https://www.lightnovelworld.com/

### ISSUE THREAD

**Issue by ghus3rz** [dipu-bd/lightnovel-crawler#1005]
Hi 
Was trying to check if this site is already supported and I think it is different from the https://lightnovel.world in the current list.

Thank you if this is possible.

**Comment by dipu-bd** [comment]
Check this PR: https://github.com/dipu-bd/lightnovel-crawler/pull/789

The https://www.lightnovelworld.com/ was changed to https://www.lightnovelpub.com/

As far as I can remember, the lightnovelworld was down at that time, and lightnovelpub was exactly like the old one. So we  thought they are the same.

**Comment by ghus3rz** [comment]
Thank you :)
