### ISSUE TITLE
wnmtl.org got an update and no longer works

### ISSUE THREAD

**Issue by Awsomer82** [dipu-bd/lightnovel-crawler#1017]
on discord wnmtl no longer works 
![image](https://user-images.githubusercontent.com/88712999/128844846-f4c5840f-89e3-4129-a8ce-9b3890bc989e.png)

**Comment by marcandjulien** [comment]
@Awsomer82 Use https instead of http and it works.

**Comment by marcandjulien** [comment]
@dipu-bd Do you want to support http version of sites or do you support only https by design?

**Comment by dipu-bd** [comment]
There is no design restrictions between http and https. To enable http we just have to add an entry to `base_url` of the crawler. I have done this in the above commit
