### ISSUE TITLE
https://www.readwn.com/ - Stop working in Bot - [BUG]

### ISSUE THREAD

**Issue by shirosora55555** [dipu-bd/lightnovel-crawler#1030]
https://www.readwn.com/ - Stop working in Bot - [BUG]

Failed to get novel info.
`Detected a Cloudflare version 2 challenge, This feature is not available in the opensource (free) version.`

**Comment by dipu-bd** [comment]
which bot?

**Comment by dipu-bd** [comment]
check answers: https://stackoverflow.com/q/64433684/1583052
