### ISSUE TITLE
Antivirus false-positive

### ISSUE THREAD

**Issue by Flwk** [dipu-bd/lightnovel-crawler#1031]
Hello

I tried to download the latest version but my AV (BitDefender Total Security 21)  detect is as a virus. : Gen:Variant.Bulz.586825

[Here ](https://www.virustotal.com/gui/url/27113115f787dc2eef74e5050faf5d81a23ab46a35db004332e169708f4ccef2/detection)is the virustotal link of the file .

Do you think it's possible to resolve this problem

Thanks in advance.

**Comment by dipu-bd** [comment]
You can use the python package. I originally intended to publish only python package. Since making EXE with pyinstaller was easy enough, we are doing that too. However, I do not plan to work on resolving blacklists of antivirus. It  is going to be too much work for what it is worth.
