### ISSUE TITLE
https://www.lightnovelpub.com  ! Error: list index out of range/405 Client Error: Method Not Allowed for url

### ISSUE THREAD

**Issue by alsderda** [dipu-bd/lightnovel-crawler#1033]
**Describe the bug**

--exe 

? Enter novel page url or query novel: https://www.lightnovelpub.com/novel/reincarnated-as-a-fox-with-system-novel-1907
2354
Retrieving novel info...
https://www.lightnovelpub.com/novel/reincarnated-as-a-fox-with-system-novel-19072354

 ! Error: list index out of range

--discord
Failed to get novel info.
405 Client Error: Method Not Allowed for url: https://www.lightnovelpub.com/novel/reincarnated-as-a-fox-with-system-novel-19072354?tab=chapters&page=1&chorder=asc
Closing current session...

https://www.lightnovelpub.com seams to have changed how thier site is structured wich means 
https://www.lightnovelpub.com/novel/reincarnated-as-a-fox-with-system-novel-19072354?tab=chapters&page=1&chorder=asc
no longer works instead it should probeply be
https://www.lightnovelpub.com/novel/reincarnated-as-a-fox-with-system-novel-19072354/chapters/page-1?chorder=asc

**Let us know**

Where did you find this bug?

 EXE | Discord Bot

What is your novel URL?
 https://www.lightnovelpub.com/novel/reincarnated-as-a-fox-with-system-novel-1907

If you are using PIP / EXE, what is your APP version ?
 2.28.2

If you are using PIP / EXE, what is your operating system ?
 Windows 10

**Comment by dipu-bd** [comment]
This issue was already fixed by this commit: https://github.com/dipu-bd/lightnovel-crawler/commit/d4384fe468e7b3083f026f32abe77cf9062c9ace
