### ISSUE TITLE
Fix this bug

### ISSUE THREAD

**Issue by Viani1412** [dipu-bd/lightnovel-crawler#1036]
**Describe the bug**
It just downloaded for 20 chapter of 145 chapter of 

**Let us know**

Where did you find this bug?
 both 

What is your novel URL?
https://noveltoon.mobi/id/detail/428389/comments

If you are using PIP / EXE, what is your APP version ?

If you are using PIP / EXE, what is your operating system ?

**Comment by dipu-bd** [comment]
because only 20 chapters are accessible for free.

Check the link: https://noveltoon.mobi/id/watch/428389/1523535

It does not have any contents.
