### ISSUE TITLE
Error 403: Cloudflare source issue

### ISSUE THREAD

**Issue by Sabruness** [dipu-bd/lightnovel-crawler#1037]
**Describe the bug**

Crawler present the following message when trying to crawl Ranobes.net for several novels:
"Error: 403 Forbidden! Could not bypass the cloudflare protection." Error seems to be source sitewide

![bug](https://user-images.githubusercontent.com/86401359/130304959-5eae1a1c-7c09-410c-8a81-d9e125d4e0aa.png)
**Let us know**

Where did you find this bug?
EXE

What is your novel URL?
https://ranobes.net/up/combat-maid-harem/
https://ranobes.net/up/the-mage-of-primordial-chaos/

If you are using PIP / EXE, what is your APP version ?
v2.28.2

If you are using PIP / EXE, what is your operating system ?
Windows 10

**Comment by dipu-bd** [comment]
can you please search existing issues before creating a new one?
