### ISSUE TITLE
Use another storage server instead of google drive

### ISSUE THREAD

**Issue by dipu-bd** [dipu-bd/lightnovel-crawler#1041]
Setting up google drive for bots is complicated. Also, drive storage are not unlimited. Managing it is a bit bothersome. It is better to use an alternate simple solution.

Possible solutions:
- https://gofile.io/api

**Comment by damare01** [comment]
[https://mega.nz/sdk]https://mega.nz/sdk)

**Comment by damare01** [comment]
[https://www.opendrive.com/api](https://www.opendrive.com/api)

**Comment by damare01** [comment]
[https://www.mediafire.com/developers/core_api/1.5/getting_started/](https://www.mediafire.com/developers/core_api/1.5/getting_started/)

**Comment by damare01** [comment]
[https://www.file.io/developers](https://www.file.io/developers)

**Comment by dipu-bd** [comment]
https://file.io is pretty good. but it deletes files after one time download.

**Comment by dipu-bd** [comment]
mega.nz does not have official python client. I found `mega.py`, but could not make it working however.

**Comment by dipu-bd** [comment]
setting up yandex is as much pain as google drive

**Comment by dipu-bd** [comment]
opendrive, mediafire etc provides limited spaces, and harder to use. i will go with gofile.io, since it is the simplest one of them all

**Comment by damare01** [comment]
@dipu-bd please do tell or update README when this feature is already implemented.

**Comment by damare01** [comment]
or make an announcement

**Comment by damare01** [comment]
Haha! Never mind just found out that it is already implemented

**Comment by dipu-bd** [comment]
https://anonfiles.com/
