### ISSUE TITLE
https://blnovels.net/

### ISSUE THREAD

**Issue by catt-z1** [dipu-bd/lightnovel-crawler#1056]
https://blnovels.net/
 
https://blnovels.net/

**Comment by SirGryphin** [comment]
@dipu-bd I think this site is shutdown now, might want to close this.

**Comment by dipu-bd** [comment]
the site is okay. maybe it was another issue from your side.

**Comment by SirGryphin** [comment]
@dipu-bd Ah, I see it's back online now. Sorry about that.
