### ISSUE TITLE
Modify novel search methods of crawlers

### ISSUE THREAD

**Issue by dipu-bd** [dipu-bd/lightnovel-crawler#106]
Now search results supports `info` field along with `title` and `url`. Put a short description or chapter and volume count in it whenever possible.

List of all search-enabled crawlers:
- [ ] https://litnet.com search
- [ ] https://www.webnovel.com search
- [x] https://www.scribblehub.com search
- [x] https://www.novelall.com search
- [x] https://wuxiaworld.online search
- [x] https://mtled-novels.com search
- [x] https://worldnovel.online search
- [x] https://www.royalroad.com search
- [x] https://novelonlinefree.info search
- [x] https://novelplanet.com search
- [x] https://m.wuxiaworld.co search
- [x] https://www.wuxiaworld.co search
- [x] https://m.wuxiaworld.com search
- [x] https://www.wuxiaworld.com search
- [x] https://boxnovel.com search
- [x] http://novelfull.com search
- [x] http://fullnovel.live search

**Comment by dipu-bd** [comment]
`boxnovel` is done

**Comment by yudilee** [comment]
@dipu-bd  which one is better for info, novel description (easier to get from search page on sites) or number of chapter (must create new function to get it by inserting url from search url)? In my opinion i prefer number of chapter or latest chapter to be shown at search menu

**Comment by dipu-bd** [comment]
I also prefer the latest chapter, ratings, chapter & volume count etc. useful information.

We should keep info as short as possible so that it does not take too much space in console. Novel description is long and not particularly useful. Because most people would choose their novel by web browser first.

Also, consider the time the search would take if you want to crawl all info for every single novels. We should always minimize the number of network calls inside search method.

**Comment by dipu-bd** [comment]
- [x] http://fullnovel.live/
- [x] http://novelfull.com/
- [x] https://m.wuxiaworld.co/
- [x] https://www.wuxiaworld.co/

**Comment by yudilee** [comment]
added to pull request #108 

- [x] https://worldnovel.online/
- [x] https://royalroad.com/

**Comment by dipu-bd** [comment]
List of all search-enabled crawlers:
- [ ] https://www.royalroad.com search
- [ ] https://www.scribblehub.com search
- [ ] https://www.webnovel.com search
- [ ] https://www.wuxiaworld.co search
- [ ] https://www.wuxiaworld.com search
- [ ] https://www.novelall.com search
- [ ] https://worldnovel.online search
- [ ] https://wuxiaworld.online search
- [ ] https://mtled-novels.com search
- [ ] https://novelonlinefree.info search
- [ ] https://novelplanet.com search
- [ ] https://m.wuxiaworld.co search
- [ ] https://m.wuxiaworld.com search
- [ ] https://litnet.com search
- [ ] https://boxnovel.com search
- [ ] http://novelfull.com search
- [ ] http://fullnovel.live search

**Comment by yudilee** [comment]
> List of all search-enabled crawlers:
> 
>     * [x]  https://www.royalroad.com search
> 
>     * [ ]  https://www.scribblehub.com search
> 
>     * [ ]  https://www.webnovel.com search
> 
>     * [x]  https://www.wuxiaworld.co search
> 
>     * [ ]  https://www.wuxiaworld.com search
> 
>     * [ ]  https://www.novelall.com search
> 
>     * [x]  https://worldnovel.online search
> 
>     * [ ]  https://wuxiaworld.online search
> 
>     * [ ]  https://mtled-novels.com search
> 
>     * [ ]  https://novelonlinefree.info search
> 
>     * [ ]  https://novelplanet.com search
> 
>     * [x]  https://m.wuxiaworld.co search
> 
>     * [ ]  https://m.wuxiaworld.com search
> 
>     * [ ]  https://litnet.com search
> 
>     * [x]  https://boxnovel.com search
> 
>     * [x]  http://novelfull.com search
> 
>     * [x]  http://fullnovel.live search

Just pull request #111 for updating search method for wuxiacom, novelplanet and novelonlinefree

**Comment by yudilee** [comment]
Added pull request #113 for  
https://www.scribblehub.com 
https://www.novelall.com 
https://wuxiaworld.online 
https://mtled-novels.com
