### ISSUE TITLE
Cloudflare Bug Ranobes

### ISSUE THREAD

**Issue by Saketh-Kanchi** [dipu-bd/lightnovel-crawler#1074]
## Describe the bug

![image](https://user-images.githubusercontent.com/70572193/132118525-618f0790-f3da-44b2-a157-a231fcfa9859.png)

It worked for the first two novels I downloaded from Ranobes, but didn't work from the next ones.

## Let us know

**Input**: https://ranobes.net/novels/1075084-talqpfty.html   
**App type**: EXE    
**App version**: 2.28.4                       
**Your OS**: Windows

**Comment by dipu-bd** [comment]
Follow the instruction of the error message. there is nothing to do about this error.
