### ISSUE TITLE
Failed to download source file

### ISSUE THREAD

**Issue by Otherdeath** [dipu-bd/lightnovel-crawler#1080]
Just downloaded lncrawl.exe to update to version 2.28.4, and everytime I start the app I get the following message:

"Failed to download source file. Error: 404 Client Error: Not Found for url: https://raw.githubusercontent.com/dipu-bd/lightnovel-crawler/master/sources/readln.py"

Even running the .exe as administrator doesn't fix it and because of that I can't query novels always ending in error.

**App type**: EXE
**App version**: 2.28.4  
**Your OS**: Windows

**Comment by dipu-bd** [comment]
delete `.lncrawl` folder from your home directory. It should fix the issue.

**Comment by Otherdeath** [comment]
Oh, what I did was download the source folder and replace it manually. But will do that next time then, thanks for the quick reply.

**Comment by SirGryphin** [comment]
@dipu-bd 
I'm getting same error when I updated to latest version through pip (2.28.5) and I have no .lncrawl file to delete.

**Comment by Otherdeath** [comment]
> 
> 
> @dipu-bd
> I'm getting same error when I updated to latest version through pip (2.28.5) and I have no .lncrawl file to delete.

.lncrawl is not a file but folder under user at - C:\Users\'user'\.lncrawl. It's created when executing the .exe for the first time.

![Folder](https://user-images.githubusercontent.com/68498565/132953085-11a23e99-c0cb-4cf9-a2f3-8dc3fc3e01f1.PNG)

**Comment by SirGryphin** [comment]
@dipu-bd Found it and deleted, all working fine now :) I was checking the github/lightnovel-crawler folder for it lol. I thought that's what you meant by "home directory", guess you actually meant home directory like "windows".
