### ISSUE TITLE
boxnovel.com Returning 0 Chapters

### ISSUE THREAD

**Issue by dastrdly6585** [dipu-bd/lightnovel-crawler#1084]
## Describe the bug

All novels on boxnovel.com are returning 0 volumes and 0 chapters.

## Let us know

**Input**: https://boxnovel.com/novel/reborn-little-girl-wont-give-up/
**App type**:  EXE & Discord
**App version**: 2.28.5
**Your OS**: Windows

**Comment by SirGryphin** [comment]
Fixed and add to latest PR #1098
