### ISSUE TITLE
Ranobes Advertisements

### ISSUE THREAD

**Issue by Saketh-0** [dipu-bd/lightnovel-crawler#1087]
The novels grabbed from Ranobes have Advertisements. And sometimes multiple such words in a single chapter.

https://i.imgur.com/tBN5Rx5.png

**Comment by dipu-bd** [comment]
please provide a sample novel link

**Comment by Sololvl0** [comment]
https://ranobes.net/novels/951494-reincarnated-with-the-strongest-system-v256143.html
Don't judge...

**Comment by Sololvl0** [comment]
[Reincarnated With The Strongest System c1-271.zip](https://github.com/dipu-bd/lightnovel-crawler/files/7182782/Reincarnated.With.The.Strongest.System.c1-271.zip)
Here is the epub file

**Comment by SirGryphin** [comment]
I tried testing ranobes.net but I keep getting this error.

```
 ! Error: 403 Forbidden! Could not bypass the cloudflare protection.
  If you are running from your own computer, visit the link on your browser and try again later.
  Sometimes, using `http` instead of `https` link may work.
```

**Comment by Sololvl0** [comment]
> I tried testing ranobes.net but I keep getting this error.
> 
> ```
>  ! Error: 403 Forbidden! Could not bypass the cloudflare protection.
>   If you are running from your own computer, visit the link on your browser and try again later.
>   Sometimes, using `http` instead of `https` link may work.
> ```

Open a separate issue for it. And post the details there. It mostly happens after you download 2 or more novels in the last 6-12 hrs. Just wait
