### ISSUE TITLE
Rejected source removal from "_rejected.json" file

### ISSUE THREAD

**Issue by damare01** [dipu-bd/lightnovel-crawler#1094]
## Describe the bug

I already removed [Chrysanthemungarden](https://chrysanthemumgarden.com/) from the `_rejected.json` but the bot still says source is not recognize

## Let us know

**Input**:         <novel url or query you entered>  https://chrysanthemumgarden.com/novel-tl/btbab/
**App source**:     Cloned git file
**App version**:     My own self hosted bot

**Comment by dipu-bd** [comment]
If you are running your bot in production mode, you have to do this: 

Check the following line: 
https://github.com/dipu-bd/lightnovel-crawler/blob/master/lncrawl/core/sources.py#L80

Change the `__master_index_file_url` to your own repository link.
