### ISSUE TITLE
MTLNovel.com - Cloudflare protection

### ISSUE THREAD

**Issue by banditdk20** [dipu-bd/lightnovel-crawler#1095]
## Describe the bug

As per the screenshot, unable to download a novel from MTLNovel.com website despite it being one of the websites listed in the sources. I've tried multiple novels and I tried entering with HTTP instead of HTTPS as per the error suggestion, no results. Am i doing something wrong or does it not work in general?

## Let us know

**Input**:         https://www.mtlnovel.com/entertainment-i-can-upgrade-infinitely/
**App source**:    EXE
![Screenshot 2021-09-19 121607](https://user-images.githubusercontent.com/91012011/133925502-9e8dd221-0e66-42b5-9807-7224ff008d7f.JPG)

**App version**:   2.28.5  
**Your OS**:       Windows

**Comment by dipu-bd** [comment]
No, you are not doing something wrong. This issue is common occurence for the bots. There is no solution yet.

**Comment by banditdk20** [comment]
Thank you for a quick response. I've managed to find the same novel on another website and downloaded from there instead, so all good :)
