### ISSUE TITLE
Search for title not working on wujizun.com source

### ISSUE THREAD

**Issue by mygithub-acct** [dipu-bd/lightnovel-crawler#1097]
When I searched for "The Transmigration Survival Guide" it doesn't come up with the source of wujizun.com but it can still download if I pasted the link instead.
![Screenshot_20210920-095323_Termux](https://user-images.githubusercontent.com/71422313/133947076-bd081877-5f13-44fd-bdbb-cb09f18e83f4.jpg)

**Comment by SirGryphin** [comment]
@mygithub-acct
That's because search isn't supported for this site. You can check here: https://github.com/dipu-bd/lightnovel-crawler#supported-sources and the ones with the 🔍 icon allow searching.

**Comment by mygithub-acct** [comment]
> @mygithub-acct
> That's because search isn't supported for this site. You can check here: https://github.com/dipu-bd/lightnovel-crawler#supported-sources and the ones with the 🔍 icon allow searching.

I see, my bad. Didn't read the source table properly. Thanks for clearing it up
