### ISSUE TITLE
Get error about cfscrape

### ISSUE THREAD

**Issue by yudilee** [dipu-bd/lightnovel-crawler#110]
**Get error about cfscrape**
While searching got error message on log `Error parsing Cloudflare IUAM Javascript challenge. Cloudflare may have changed their technique, or there may be a bug in the script.`. I have already update cfscrape this morning because get the same error while testing using IDLE. but error persist in lightnovel-crawler. is it because file cfscrape in util ?

**Let us know**
- Novel URL: using search, not yet getting url but error shown while accessing novel planet in log
- App Version: [2.9.0]
- Package: [github]
- OS: [Ubuntu 18.10]

**Comment by dipu-bd** [comment]
I updated the `cfscrape`. Now it should be fixed.

Using the `js2py` module removes nodejs dependency. I do not see why cloudflare's evaluation would be a security risk if solved using js2py. That's why I am keeping a modified copy of original `cfscrape` in utils
