### ISSUE TITLE
! Error: 'NoneType' object has no attribute 'text'

### ISSUE THREAD

**Issue by taitin916** [dipu-bd/lightnovel-crawler#1107]
## Describe the bug

! Error: 'NoneType' object has no attribute 'text'

## Let us know

**Input**:         https://rewayat.club/novel/omniscient-reader-viewpoint
**App source**:  EXE
**App version**:   2.28.5
**Your OS**:       Windows

**Comment by dipu-bd** [comment]
rewayat has changed their web layout. now it uses javascript to render pages on the client side. it will be difficult to support this new structure.
