### ISSUE TITLE
Request remove readwn Crawler

### ISSUE THREAD

**Issue by readsgo** [dipu-bd/lightnovel-crawler#1109]
Request remove my websites from the Crawler list, Because it puts a lot of load on my server
This caused me a lot of trouble, working 18 hours a day & ready to block the ip at any time

1. readwn.com
2. novelmt.com
3. novelmtl.com

thank you

**Comment by dipu-bd** [comment]
This app is no way related to your server load. I have done everything I could do to appear as a normal reader. If you are experiencing this issue, it might be because of some other crawlers. Please do not put your blames on the wrong people.

**Comment by readsgo** [comment]
Maybe what you said is right, sorry for the extra words, 
I just hope to remove my websites from the Crawler list
