### ISSUE TITLE
Fix this bug

### ISSUE THREAD

**Issue by jericelona** [dipu-bd/lightnovel-crawler#112]
the epub, html etc shows no content. only the site logo and chapter number.

- Novel URL: https://comrademao.com/novel/harry-potter-and-the-secret-treasures/
- App Version: 2.8.4
- Package: pip, github, exe
- OS: Windows 7

**Comment by yudilee** [comment]
Try updating your app to latest, yesterday i have already pull request #107 to fix this

**Comment by dipu-bd** [comment]
A major change is going on in the next version: 2.9.0
It will be ready to be released by tomorrow. Wait for it :popcorn:

**Comment by dipu-bd** [comment]
New version released. this bug is fixed.
