### ISSUE TITLE
https://www.worldnovel.online/

### ISSUE THREAD

**Issue by bucakuku** [dipu-bd/lightnovel-crawler#1128]
Hi

Can you guys help me with the error on this website?
there is a problem when crawling per chapter with a description like the one below

**Body is empty: https://www.worldnovel.online/worn-and-torn-newbie/worn-and-torn-newbie-chapter-1/
Body is empty: https://www.worldnovel.online/worn-and-torn-newbie/worn-and-torn-newbie-chapter-2/**

Thank you

**Comment by dipu-bd** [comment]
Site changed. The bot requires an update to get it working again.
