### ISSUE TITLE
Feature request:local cache for novel that has been scrapped

### ISSUE THREAD

**Issue by yudilee** [dipu-bd/lightnovel-crawler#114]
The idea is because in older version of lightnovel-crawler this feature is already there but not support multiple novel source. I think in version 1 or earlier version 2 this app save crawled novel and asking for deletion. But check it by the name of novel. If novel is saved in local cache in novel name inside novel sites name we can check and use it in later generated epub for every novel in each site's so no need to re-download it.

**Comment by dipu-bd** [comment]
It feature is also available now too. If chapter body already is present as json, it won't get downloaded. But I am crawling novel-info like - title, chapter list etc each time, because they can be updated frequently.

**Comment by yudilee** [comment]
Many aggregates sites have same novel but somehow they are different for example almost every chapter on wuxiaworld.co has chapter title but boxnovel only has chapter number as title for earlier chapter. But they have the same novel and if we saved it locally using novel title as folder name not differentiate novel source, the output is can be confusing

**Comment by dipu-bd** [comment]
You are right, multiple sites have the same novel. Are you saying the folder names should be something like- `Novel title [source]` to differentiate between novel and source?

**Comment by yudilee** [comment]
If it's to long maybe we can use subfolder

**Comment by dipu-bd** [comment]
Ok, we can consider this option. I will put it in the next release. Using subfolders for sources seems better choice

**Comment by yudilee** [comment]
Thank you so much @dipu-bd. This is really good news
