### ISSUE TITLE
Problem in search 

### ISSUE THREAD

**Issue by loro102** [dipu-bd/lightnovel-crawler#115]
The application has some problem because when I search for a title for example "The Strongest gene" I get blocked in 14/15 but if I cut the internet I can continue . I suppose there is not a timeout for each web

================================================================================
                             Lightnovel Crawler #2.9.2
            Download lightnovels into html, text, epub, mobi and json
--------------------------------------------------------------------------------

-> Press  Ctrl + C  to exit

? Enter novel page url or query novel:  The Strongest Gene
Searching |██████████████████████████████  | 14/15

**Comment by yudilee** [comment]
Found the problem. search in novelplanet resulting waiting forever. need to update cfscrape in util

**Comment by yudilee** [comment]
I pull request #116 to fix this problem
