### ISSUE TITLE
chrysanthemumgarden.com

### ISSUE THREAD

**Issue by plush18** [dipu-bd/lightnovel-crawler#1153]
## Describe the bug

I checked the updated source list both here and in Terminal and CG is back as a listed source. I was able to download 2 novels off of the site but nothing after that. No matter what link I tried, it showed a rejected source error. 

## Let us know

**Novel URL**:     <https://chrysanthemumgarden.com/novel-tl/ntnh/>
**App source**:    PIP
**App version**:   2.28.8
**Your OS**:       Mac
 
![CG](https://user-images.githubusercontent.com/92849611/138051250-4646f87d-838d-4d46-a534-6564795704a7.jpg)

**Comment by dipu-bd** [comment]
I fixed the issue. There will be fix in the new version. The new version will be released in a few days
