### ISSUE TITLE
https://www.litenovel.com

### ISSUE THREAD

**Issue by Emasoft** [dipu-bd/lightnovel-crawler#1165]
https://www.litenovel.com

- Language: english
- Supports Searching: Yes
- Contains Machine Translations: No
- Contains Manga/Manhua/Manhwa: No
- Has CloudFlare Protection: No

Special interest:
the only website with a non broken (missing chapters or half chapters) version of NSHBA: 
https://www.litenovel.com/nine-star-hegemon-body-arts/

**Comment by hoangphuc05** [comment]
And...this domain is gone
