### ISSUE TITLE
can't find crawler / parsers in the newest release anymore

### ISSUE THREAD

**Issue by Kusurisan** [dipu-bd/lightnovel-crawler#1166]
## Describe the bug
Updated to the last version and now i get this error messages:

`Could not load crawlers from C:\Users\Cyy\AppData\Local\Temp\_MEI30642\sources\en\l\lnmtl.py. Error: No module named 'js2py'
Could not load crawlers from C:\Users\Cyy\AppData\Local\Temp\_MEI30642\sources\en\n\novelmao.py. Error: No module named 'js2py'
Could not load crawlers from C:\Users\Cyy\AppData\Local\Temp\_MEI30642\sources\en\q\qidianunderground.py. Error: No module named 'regex'
Could not load crawlers from C:\Users\Cyy\AppData\Local\Temp\_MEI30642\sources\en\r\rewayatclub.py. Error: No module named 'js2py'
Could not load crawlers from C:\Users\Cyy\.lncrawl\sources\en\l\lnmtl.py. Error: No module named 'js2py'
Could not load crawlers from C:\Users\Cyy\.lncrawl\sources\en\n\novelmao.py. Error: No module named 'js2py'
Could not load crawlers from C:\Users\Cyy\.lncrawl\sources\en\q\qidianunderground.py. Error: No module named 'regex'
Could not load crawlers from C:\Users\Cyy\.lncrawl\sources\en\r\rewayatclub.py. Error: No module named 'js2py'`

deleting the .lncrawl folder in my homedirectory and the %appdata% temp folder didn't change anything. downloading an older release works and it isn't showing the issue.

## Let us know

**App source**:    Windows Exe
**App version**:   newest
**Your OS**:      Windows 10

**Comment by dipu-bd** [comment]
Delete the `C:\Users\Cyy\.lncrawl` folder
