### ISSUE TITLE
https://mostnovel.com/

### ISSUE THREAD

**Issue by shirosora55555** [dipu-bd/lightnovel-crawler#1169]
I saw one post of this website, but never was added, 
I for Webnovel.com novels, & these days hard to catch up to see what latest new novel on webnovel. 
So this website best to pull. 

- Language: English
- Supports Searching: Yes
- Contains Machine Translations: No
- Contains Manga/Manhua/Manhwa: No
- Has CloudFlare Protection: Unknown if has, prob No

**Comment by dipu-bd** [comment]
#974
