### ISSUE TITLE
Searching in novel planet returning list of all novel on novelplanet so output is invalid

### ISSUE THREAD

**Issue by yudilee** [dipu-bd/lightnovel-crawler#117]
**Describe the bug**
I try searching using novelplanet as source in crawler app and also try it on novelplanet website and IDLE. when using novelplanet crawler output generates is exactly the same with when we enter wrong url after novelplanet.com for example i want to search for novel **Kenkyo, Kenjitsu o Motto ni Ikite Orimasu** so i used keyword kenjitsu. in browser url for search is https://novelplanet.com/NovelList?name=kenjitsu. try this on browser and IDLE (using cfscrape and beautiful soup) returning exactly 1 novel, the novel i'm looking for but when try it on lightnovel-crawler it returning list of novel as if i wrongly used search url it gave the same result as this url https://novelplanet.com/NovelList.

**Let us know**
- Novel URL: [e.g. https://novelplanet.com/NovelList?name=kenjitsu]
- App Version: [2.9.2]
- Package: [github]
- OS: [e.g. Ubuntu Desktop 18.10]

**Comment by dipu-bd** [comment]
I am temporarily disabling the search feature on novelplanet as it is not working
