### ISSUE TITLE
Enter your desired sources here

### ISSUE THREAD

**Issue by RaihaGremori** [dipu-bd/lightnovel-crawler#1173]
https://grensia.blogspot.com

- Language: Indonesia
- Supports Searching: Yes
- Contains Machine Translations: Yes
- Contains Manga/Manhua/Manhwa: No
- Has CloudFlare Protection: No

**Comment by dipu-bd** [comment]
its already available. check README

**Comment by RaihaGremori** [comment]
it's no longer possible, it says (not "str")

**Comment by dipu-bd** [comment]
You should create a bug request in that case. Source request is only for the websites that are not yet supported.
