### ISSUE TITLE
scribblehub.com cannot parse

### ISSUE THREAD

**Issue by Here-Be-Saoirse** [dipu-bd/lightnovel-crawler#1174]
## Describe the bug

Lncrawl can no longer download from scribblehub, it now presents an "unable to parse" error message.

## Let us know

**Novel URL**:     https://www.scribblehub.com/series/40636/falling-over/
**App source**:    PIP and source both
**App version**:   latest (git)
**Your OS**:       Linux

**Comment by dipu-bd** [comment]
fixed
