### ISSUE TITLE
Fix grensia.blogspot.com

### ISSUE THREAD

**Issue by RaihaGremori** [dipu-bd/lightnovel-crawler#1175]
## Let us know

**Novel URL**: https://grensia.blogspot.com/
**App source**: EXE
**App version**: 2.28.9
**Your OS**: Windows
  
![Screenshot_2021-11-02-16-45-52-44](https://user-images.githubusercontent.com/93586947/139988023-20a89ee0-b70d-48e2-8b79-560c7d09179f.jpg)

**Comment by dipu-bd** [comment]
fixed
