### ISSUE TITLE
Lightnovel Crawler 2.28.9, 2.28.11, never worked now

### ISSUE THREAD

**Issue by shirosora55555** [dipu-bd/lightnovel-crawler#1184]
## Describe the bug

Lightnovel Crawler - bot always busy), (Its online, but never worked since update of 2.28.9, 2.28.11, 
Always Message: 
Sorry! I am too busy processing requests of other users.
Please knock again in a few hours.

## Let us know

**App source**:    PIP | EXE | Discord | Telegram 
Discord Bot: Lightnovel Crawler 2.28.9, 2.28.11, 

**App version**:   x.y.z  
**Your OS**:    Linux | Windows | Mac 
  Lightnovel Crawler 2.28.9, 2.28.11,

**Comment by dipu-bd** [comment]
I will turn off the user limiting feature in the next version.
