### ISSUE TITLE
https://www.fanfiction.net/

### ISSUE THREAD

**Issue by SakethKanchi** [dipu-bd/lightnovel-crawler#1186]
https://www.fanfiction.net/

- Language:
- Supports Searching: Yes
- Contains Machine Translations: No
- Contains Manga/Manhua/Manhwa: No
- Has CloudFlare Protection: Yes

**Comment by dipu-bd** [comment]
![image](https://user-images.githubusercontent.com/5158124/141381463-60a1fd30-2723-4ff2-ace3-828bc0b01e7e.png)

**Comment by SakethKanchi** [comment]
![image](https://user-images.githubusercontent.com/70198692/141403452-245aacc3-c357-4e05-9f12-bf7763101a67.png)

Reference Link: https://www.fanfiction.net/s/12975806/1/Harry-Potter-and-the-Secret-of-the-Patronus

**Comment by dipu-bd** [comment]
This has already been discussed multiple times. See older issues.

![image](https://user-images.githubusercontent.com/5158124/141432009-6486d2a3-e3de-424e-a6f4-dded560745b0.png)
