### ISSUE TITLE
List Index out of range" in readwn.com

### ISSUE THREAD

**Issue by josephfrances123** [dipu-bd/lightnovel-crawler#1191]
Whenever I download from Readwn.com, this happens

Failed to get novel info.
list index out of range

please help how

**Comment by dipu-bd** [comment]
Please create a `Source Not Working`  type issue

https://github.com/dipu-bd/lightnovel-crawler/issues/new?assignees=&labels=bug&template=3_source-issue.md&title=Fix+this+source
