### ISSUE TITLE
https://web.archive.org/web/20161119214524/http://www.wuxiaworld.com/cdindex-html/

### ISSUE THREAD

**Issue by budikesuma** [dipu-bd/lightnovel-crawler#1194]
Hello Devs...
since the completed novel in WW locked by karma.  So working from web archive sources will solve the problem, as some people prefer the original format over unclean aggregated sources.  So I ask developers to start adding web archive sources for us, thanks.

`Sample of Completed Novel url: `
https://web.archive.org/web/20161119214524/http://www.wuxiaworld.com/cdindex-html/

App: exe & termux.
OS: win 10.

**Comment by UltraStudioLTD** [comment]
Working with **web.archives.org** would be difficult

**Comment by budikesuma** [comment]
Have been able to scrape it off with manual scripting. Sorry I forgot to close it.
