### ISSUE TITLE
Fix this source: toc.qidianunderground.org

### ISSUE THREAD

**Issue by budikesuma** [dipu-bd/lightnovel-crawler#1204]
`Source Not Working`
Crawler unable to find chapter links from toc.qidianunderground.org, with result: `List index out of range`.

`Novel url: `
https://toc.qidianunderground.org/api/v1/pages/public/cd9768464ea15bd2/chapters

From index `i`:
https://toc.qidianunderground.org/#I

**App source**: 
`Discord bot` and  `Termux`, V2.28.11
**App version**: 
`Lightnovel Crawler`
.
![Screenshot_20211119-164628_Discord~2](https://user-images.githubusercontent.com/50254552/142603389-9dbd8841-af47-4f5b-8884-be3e81a859c8.jpg)

![Screenshot_20211119-171254_Termux](https://user-images.githubusercontent.com/50254552/142606094-b3ff317f-7823-4de1-b083-b184e9971a76.jpg)

**Comment by dipu-bd** [comment]
it works on desktop
