### ISSUE TITLE
Fix this bug: new ads from lightnovelpub.com

### ISSUE THREAD

**Issue by budikesuma** [dipu-bd/lightnovel-crawler#1205]
Hello Devs,
I found new ads template from lightnovelpub.com source: 

`<strong>`random texts from lightnovelpub.com`</strong>`

Please remove it,thanks. 

`Novel url:`
https://www.lightnovelpub.com/novel/the-mech-touch-wn-19072354

**Comment by johnveyron** [comment]
@dipu-bd 
Hello dev,
You should go take a quick look at your discord.  It's already full of Spammers, it's been days we've been mentioning @dev, but no response.  
Please remove them before the other members runaway.

**Comment by mesmerlord** [comment]
Info on this : they're using CSS to hide the ads with two strong tags

.chapter-content p > strong > strong {
		display:none;
	}
Still not too familiar with the extract tags function otherwise I'd submit a PR

**Comment by dipu-bd** [comment]
```py
for el in soup.select("p > strong > strong"):
    el.extract()
```

**Comment by dipu-bd** [comment]
fixed
