### ISSUE TITLE
Fix this bug

### ISSUE THREAD

**Issue by e4e6** [dipu-bd/lightnovel-crawler#1207]
it takes too long to make simple search, 6 min for a simple search and everytime thats too long

![image](https://user-images.githubusercontent.com/73366454/143606766-f295667f-8789-463a-a17b-45ca796ecae3.png)

**Comment by 02alia1** [comment]
> it takes too long to make simple search, 6 min for a simple search and everytime thats too long
> 
> ![image](https://user-images.githubusercontent.com/73366454/143606766-f295667f-8789-463a-a17b-45ca796ecae3.png)

It's doesn't really take that long. For me it takes around 2 minutes to search the novel. Once you find the novel it downloads pretty fast. Maybe, this depends on your ISP speed.

However, it would be nice if the search speed fast a bit faster. But I can understand that the algorithm takes a while to search through all the sources available.

Have you tried copying and pasting the url link for the novel. This could be a bit faster compared to searching via novel name.

**Comment by 02alia1** [comment]
It's doesn't really take that long. For me it takes around 2 minutes to search the novel. Once you find the novel it downloads pretty fast. Maybe, this depends on your ISP speed.

However, it would be nice if the search speed fast a bit faster. But I can understand that the algorithm takes a while to search through all the sources available.

Have you tried copying and pasting the url link for the novel. This could be a bit faster compared to searching via novel name.

**Comment by dipu-bd** [comment]
use the `-x` option to select which sources you want to search. e.g.

```
$ lncrawl -q "novel query" -x novelfull
$ lncrawl -q "novel query" -x boxnovel
$ lncrawl -x royalroad
```
