### ISSUE TITLE
save novels in Google drive

### ISSUE THREAD

**Issue by loro102** [dipu-bd/lightnovel-crawler#122]
I want to save the novels in google drive, do you have an option to do it? If so, how can I configure it?

**Comment by yudilee** [comment]
There is already option for that but you have to get credential for Google api check how to setup at https://pythonhosted.org/PyDrive/quickstart.html then edit uploader.py file in util folder to set your directory ID in gdrive

**Comment by dipu-bd** [comment]
For console app, this option is not available. I do not see how it will be useful for console app, since all files are already available in your local storage

**Comment by yudilee** [comment]
> I want to save the novels in google drive, do you have an option to do it? If so, how can I configure it?

Can we close this issue?  If you need help iregarding this issue please inform us
