### ISSUE TITLE
https://chrysanthemumgarden.com/

### ISSUE THREAD

**Issue by EVANSSTOKER** [dipu-bd/lightnovel-crawler#1220]
- Language:
- Supports Searching: Yes/No
- Contains Machine Translations: Yes/No
- Contains Manga/Manhua/Manhwa: Yes/No
- Has CloudFlare Protection: Yes/No

**Comment by mesmerlord** [comment]
It should already be available as a source in sources/en/c/chrysanthemumgarden

**Comment by dipu-bd** [comment]
It was disabled by the request of the site owner #649
