### ISSUE TITLE
Failed download

### ISSUE THREAD

**Issue by kakarott14** [dipu-bd/lightnovel-crawler#1222]
I cant open the downloaded file. 
Below is the link of the picture of the said problem.
https://drive.google.com/file/d/1MlD5BvjO1Sc5b6GhhfZ80BO2JFALLw61/view?usp=drivesdk

**Comment by dipu-bd** [comment]
create a source issue please 

https://github.com/dipu-bd/lightnovel-crawler/issues/new?assignees=&labels=source-issue&template=3_source-issue.md&title=Fix+this+source
