### ISSUE TITLE
LNMTL Bug

### ISSUE THREAD

**Issue by loks1234** [dipu-bd/lightnovel-crawler#123]
**Describe` the bug**
Unable to load even the info about the novel. it shows " Error: expected string or bytes-like object'. I have attached the log
[Log for LNMTL.txt](https://github.com/dipu-bd/lightnovel-crawler/files/3042590/Log.for.LNMTL.txt)

**Let us know**
- Novel URL: https://lnmtl.com/novel/reincarnation-paradise
- App Version: 2.9.4
- Package:pip
- OS: Ubuntu 18.04

**Comment by yudilee** [comment]
It happened due to change in some new novel addition to lnmtl, add fix in pull request #124
