### ISSUE TITLE
scribblehub: improve inline footnote style

### ISSUE THREAD

**Issue by riking** [dipu-bd/lightnovel-crawler#1232]
Example: Very end of https://www.scribblehub.com/read/117113-isekaid-shoggoth/chapter/117132/

Incorrect:
![Screenshot_20211228-174614](https://user-images.githubusercontent.com/627891/147619731-7b49181b-188d-4bed-8bf3-5c66a636d1f6.png)
> 'eau fleurie du nord<sup><a href>1</a></sup>flower water from north'.

Correct: Either a true epub footnote, or remove the link and put the text into square brackets.
> 'eau fleurie du nord [flower water from north]'.

Might be interested in figuring this out myself.

**Comment by dipu-bd** [comment]
fixed
