### ISSUE TITLE
Ranobes.net Error: invalid literal for int() with base 10:

### ISSUE THREAD

**Issue by AbdAlrahmanFayed** [dipu-bd/lightnovel-crawler#1235]
When trying to download from ranobes.net it gives the following 

Error: invalid literal for int() with base 10:

No novel can be downloader

**Comment by setite** [comment]
I am seconding this, I have run into the same problem.

**Comment by watzeedzad** [comment]
For my initial finding, it's seem like response that got from `https://ranobes.net/chapters/xxxxx/` did not contains any chapter details, even if I got `pages_count` via `script` tag, crawler still unable to find title nor chapter url because it did not in the response in the first place.

**Comment by watzeedzad** [comment]
So basically they move chapter details behind endpoint `https://ranobes.net/engine/mods/reader/ajax.php`, but unfortunately I unable to get cloudscraper to get pass through cloudflare.

**Comment by dipu-bd** [comment]
fixed
