### ISSUE TITLE
https://mtlnation.com/

### ISSUE THREAD

**Issue by 3dycosmo** [dipu-bd/lightnovel-crawler#1236]
Guys, this is faloo novels, add will you?

**Comment by dipu-bd** [comment]
check #1057

**Comment by 3dycosmo** [comment]
> check #1057
You don't need to crawl
You just have to use auto generate for the enxt number, coz all chapter on mtlnation are numerical sequences
Like this;
https://mtlnation.com/novel/metropolis-i-tall-rich-and-handsome-villain/chapter-31/
The next obviously;
https://mtlnation.com/novel/metropolis-i-tall-rich-and-handsome-villain/chapter-32/

Thx, could forget crawling toc and used the numbering sequence, thx again

**Comment by Flwk** [comment]
Hello,

I tried with the latest version, but it mentionned that it cannot reco

Here is an example :

**Comment by dipu-bd** [comment]
Use https://mtlnation.com/novel/misunderstanding-i-really-didnt-show-love-to-my-teacher

without `www`

**Comment by Flwk** [comment]
@dipu-bd Thank you very much ! :)
