### ISSUE TITLE
wuxiaworld.site error

### ISSUE THREAD

**Issue by plush18** [dipu-bd/lightnovel-crawler#1239]
Yes, I have searched the existing issues. 

**Novel URL**:    (https://wuxiaworld.site/)
**App Location**:    PIP
**App Version**:  2.28.11

## Describe this issue

Any novel I try to download from wuxiaworld.site fails to start crawling. The site is supported but before the app can proceed to the menu with the number of chapters available, an error message shows up. 

<img width="576" alt="Screenshot 2022-01-18 at 11 38 25 AM" src="https://user-images.githubusercontent.com/92849611/149881261-19564c81-b157-4988-9036-247d6806599d.png">
<img width="636" alt="Screenshot 2022-01-18 at 11 43 37 AM" src="https://user-images.githubusercontent.com/92849611/149881277-e2600905-3af6-4605-adbc-52a81f49c448.png">

**Comment by GoldenJJ** [comment]
wuxiaworld.site has recently introduced cloudflare and captcha protection

**Comment by Brian-Zombait** [comment]
> 

Maybe it's because I use Brave browser and I log in, but I don't get any captchas. I'll try another browser to see.

**Comment by Brian-Zombait** [comment]
> wuxiaworld.site has recently introduced cloudflare and captcha protection

> 

Maybe it's because I use Brave browser and I log in, but I don't get any captchas. I'll try another browser to see.

**Comment by Brian-Zombait** [comment]
> > wuxiaworld.site has recently introduced cloudflare and captcha protection
> 
> > 
> 
> Maybe it's because I use Brave browser and I log in, but I don't get any captchas. I'll try another browser to see.

Just tried with Duckduckgo no login and still no captcha after many pages.

**Comment by GoldenJJ** [comment]
> 

I'm not talking about users visiting the page, try sending a request to wwsite and you'll get the code for the cloudflare page.

**Comment by Brian-Zombait** [comment]
> I'm not talking about users visiting the page, try sending a request to wwsite and you'll get the code for the cloudflare page.
Not sure what exactly you mean. Do you mean via CMD window?

**Comment by GoldenJJ** [comment]
> Not sure what exactly you mean. Do you mean via CMD window?
Ah I see where the confusion is, sorry. I meant that if you send a GET request to wuxiaworld.site, which is what ln-crawler is doing, you receive the source code for a cloudflare page, instead of the page requested by the user. Hence, ln-crawler is no longer able to actually visit the website due to the creator implementing protection against crawling.

**Comment by dipu-bd** [comment]
![image](https://user-images.githubusercontent.com/5158124/151649548-00b84ee7-2aeb-4d71-b7a2-4d0992e626cb.png)

It shows me Access Denied in browser.
