### ISSUE TITLE
merge 2 link

### ISSUE THREAD

**Issue by fm39hz** [dipu-bd/lightnovel-crawler#1241]
can you add a feature like merge 2 link between 1 file?
cuz there are some novel has 2 team trans 2 part different, and i want to merge them into 1 file for more comfortable to read

**Comment by dipu-bd** [comment]
Give an example set of links please

**Comment by budikesuma** [comment]
> can you add a feature like merge 2 link between 1 file? cuz there are some novel has 2 team trans 2 part different, and i want to merge them into 1 file for more comfortable to read

I know what you want, you just need to install the epub-merge plugin on your desktop Calibre software.  Or if it's a hassle and you want to run through a mobile device, then use online epub merge in the chrome browser, very convenient...

https://www.onlineconverter.com/merge-epub (works on both desktop and mobile).

**Comment by dipu-bd** [comment]
Merging epubs are actually out of scope of this app. Since this feature is not very useful to everyone, and there are a lot of online tools available for it. I don't want to do the extra work for it.
