### ISSUE TITLE
https://comrademao.com/ - Fix this source

### ISSUE THREAD

**Issue by levinuiiy** [dipu-bd/lightnovel-crawler#1242]
## Let us know

**Novel URL**:     <your novel url or query> 

https://comrademao.com/

**App Location**:    PIP | EXE | Discord | Telegram 
Discord Bot
**App Version**:   x.y.z  
Lightnovel Crawler 2.28.11
## Describe this issue

Failed to Crawl Site: https://comrademao.com/novel/kunluns-first-saint/page/6/

Failed to get novel info.
`'NoneType' object is not subscriptable`

Failed to crawl site: https://comrademao.com

**Comment by Brian-Zombait** [comment]
I got the exact same thing on v 2.2.11  but on 2.26.3 I got this...
"! Error: 'NoneType' object has no attribute 'text'" see image
![2_26_3_COMRADEMAO_01](https://user-images.githubusercontent.com/6810618/150666285-3cf2afef-fe4b-40fb-8c36-1175f8f04095.png)

**Comment by dipu-bd** [comment]
fixed
