### ISSUE TITLE
https://lightnovelreader.org/

### ISSUE THREAD

**Issue by Mstrssmst** [dipu-bd/lightnovel-crawler#1243]
- Language: English
- Supports Searching: Yes
- Contains Machine Translations: No
- Contains Manga/Manhua/Manhwa: No
- Has CloudFlare Protection: Yes/No

**Comment by Brian-Zombait** [comment]
It would help if you added the actual problem, or at least a screenshot. Here you go
![lightnovelreader_org_fail](https://user-images.githubusercontent.com/6810618/150666366-0fc0d0a7-76e9-40df-9343-129594c81ac3.png)
!

**Comment by dipu-bd** [comment]
added
