### ISSUE TITLE
Fix this source: www.wuxiaworld.com new website design no longer working 

### ISSUE THREAD

**Issue by budikesuma** [dipu-bd/lightnovel-crawler#1244]
@dipu-bd 
   Due to the latest design changes on the www.wuxiaworld.com web page, lightnovel-crawler can no longer work since it requires downloading/run javascript files...

   _It will most likely be very difficult to fix, but nothing is impossible in the technology world._

Novel link:
https://www.wuxiaworld.com/novel/yama-rising

**Comment by Brian-Zombait** [comment]
![2_26_3_tutorial_is_too_hard_02](https://user-images.githubusercontent.com/6810618/150666096-01d330ce-2da6-46a1-9679-fb955cbe3d3a.png)
I cannot get an error code from the latest version, but this is what I get from 2.26.3 though I have to hit prt scrn to capture it before it closes.
"! Error: 403 Client Error: Forbidden for url: https://wuxiaworld.site/novel/the-tutorial-is-too-hard-full-novel/chapter-1/" It's the same regardless of novel.

**Comment by budikesuma** [comment]
@Brian-Zombait 
This error code from the latest version. 

```
❗ Error: 'NoneType' object has no attribute 'text'
```
.
.
![Uploading Screenshot_20220123-210534_Termux.jpg…]()

**Comment by budikesuma** [comment]
Through Google Colab it may be possible to trick the browser into running a series of javascript files, but it must change the WuxiaWorld scraper parameters first.

Chapter Content fetch: 

`<div class="chapter-content ww`
`<div class="fr-view`

Chapter Title fetch: 

`<h4 class`

**Comment by Mentole** [comment]
Any update on this? would hate to have to manually copy 5000 chapters.

**Comment by dipu-bd** [comment]
fixed
