### ISSUE TITLE
Fix this source https://www.foxaholic.com/

### ISSUE THREAD

**Issue by Darkmaster006** [dipu-bd/lightnovel-crawler#1245]
Yes, similar issue in comrademao.com:
https://github.com/dipu-bd/lightnovel-crawler/issues/1242
https://github.com/dipu-bd/lightnovel-crawler/issues/1143

**Novel URL**:     https://www.foxaholic.com/novel/the-weakest-tamer/
**App Location**:    Linux Mint 20.2 Uma, pip 20.0.2 from /usr/lib/python3/dist-packages/pip (python 3.8), Lightnovel Crawler 2.28.11
**App Version**:   Lightnovel Crawler 2.28.11

## Describe this issue

When I try 'lncrawl -s https://www.foxaholic.com/novel/the-weakest-tamer/' in the terminal, the output is:
Retrieving novel info...
https://www.foxaholic.com/novel/the-weakest-tamer/

 ❗ Error: 'NoneType' object is not subscriptable 

The same happens if I provide the link in an interactive session, or even if I provide a link to a chapter.

![image](https://user-images.githubusercontent.com/21136515/150692623-adfca008-9d11-4035-b301-cb96cf417065.png)

**Comment by ebausson** [comment]
The website in question doesn't use novel_ids anymore, neither does the scraping script. It's just dead code that wasn't removed that is now acting up.

**Comment by ebausson** [comment]
Fix in #1250 , awaiting merge.

**Comment by Darkmaster006** [comment]
This works now with the latest version. Thank you.
