### ISSUE TITLE
Slow parsing of url?

### ISSUE THREAD

**Issue by Darkmaster006** [dipu-bd/lightnovel-crawler#1246]
Basically, when in interactive mode I'm asked to provide an url or a name, when I parse a name, it reaches 125 and then goes reaaally slow, see here:
![image](https://user-images.githubusercontent.com/21136515/150694240-496a8f3e-75ff-4c97-9471-c3b9708018ba.png)
Any ideas? Taking at least 10 min as of now. Using Linux Mint 20.2 Uma, Python 3.8.

**Comment by dipu-bd** [comment]
Use the latest version and let me know if it is still slow.

**Comment by Darkmaster006** [comment]
> Use the latest version and let me know if it is still slow.

Checked with v2.29.6, seems not to lag now, definitely does not lag at the end. Seems fixed, thank you!
