### ISSUE TITLE
https://www.tapread.com/

### ISSUE THREAD

**Issue by yudilee** [dipu-bd/lightnovel-crawler#125]

**Comment by yudilee** [comment]
I check the source code of tapread, it use javascript to render its page so i think we need javascript renderer to be able to scrap from this source. also comrademao also use javascript too now. maybe to hinder bot to scrap it's site. I check many available solution and found splash (A javascript rendering service) @dipu-bd can we add this(splash) to this project to enable spider to scrap from sites that use javascript to render its page.

**Comment by dipu-bd** [comment]
There is another plugin named [splinter](https://splinter.readthedocs.io/en/latest/) which use the native browser to render pages. I used it in the initial version of ebook-crawler. But it is slow and I could not figure out how to run parallel threads to speed it up.

It seems splash supports parallel threading. But it has a lot of dependencies. It means the bundle size will increase. We have to check it first carefully before deciding to add it.

**Comment by yudilee** [comment]
Added in pull request #127
