### ISSUE TITLE
https://myoniyonitranslations.com/

### ISSUE THREAD

**Issue by yudilee** [dipu-bd/lightnovel-crawler#128]

**Comment by dipu-bd** [comment]
Samples:
https://myoniyonitranslations.com/the-king-of-the-battlefield/

https://myoniyonitranslations.com/category/swordmaster-healer/
https://myoniyonitranslations.com/swordmaster-healer/
https://myoniyonitranslations.com/swordmaster-healer-episode-169-171/
https://myoniyonitranslations.com/smh-169/

https://myoniyonitranslations.com/kh-chapter-30/
https://myoniyonitranslations.com/category/kill-the-hero/
https://myoniyonitranslations.com/kill-the-hero/
https://myoniyonitranslations.com/kill-the-hero/kh-chapter-30/

https://myoniyonitranslations.com/the-king-of-the-battlefield/
https://myoniyonitranslations.com/category/the-king-of-the-battlefield/
https://myoniyonitranslations.com/the-king-of-the-battlefield/chapter-10-boss-battle-3/
https://myoniyonitranslations.com/kotb-chapter-10/
https://myoniyonitranslations.com/kotb-chapter-207/
https://myoniyonitranslations.com/the-king-of-the-battlefield/kotb-chapter-207/

**Comment by yudilee** [comment]
I think its because ther web is based on wordpress so they have category link such as 'https://myoniyonitranslations.com/category/swordmaster-healer/' but they are not significant also they have page to inform user that they post new chapter such as https://myoniyonitranslations.com/swordmaster-healer-episode-169-171/ but they aren't significant too. the only page we need to get chapter list is toc page like this https://myoniyonitranslations.com/swordmaster-healer/ . but i also not to sure about it, will check it later. Thanks for working on it

**Comment by dipu-bd** [comment]
Ok thanks. But will every user know to input the correct novel page? I think novel id, e.g. `swordmaster-healer` should be parsed first from the url. And use it to generate novel url like I did in [fourscanlation.py#L16](https://github.com/dipu-bd/lightnovel-crawler/blob/master/lncrawl/spiders/fourscanlation.py#L16)
