### ISSUE TITLE
https://novelhi.com/

### ISSUE THREAD

**Issue by DaoDaoDao12** [dipu-bd/lightnovel-crawler#1288]
- Language:
- Supports Searching: Yes/No
- Contains Machine Translations: Yes
- Contains Manga/Manhua/Manhwa: No
- Has CloudFlare Protection: Yes/No

**Comment by DaoDaoDao12** [comment]
NovelHi.com has extremely high-quality MTL translations - possibly the best I've ever read. It'd be a fantastic addition.

**Comment by dipu-bd** [comment]
duplicate request #1263
