### ISSUE TITLE
https://allnovelfull.com/

### ISSUE THREAD

**Issue by saphiejie** [dipu-bd/lightnovel-crawler#1296]
- Language:
- Supports Searching: Yes/No
- Contains Machine Translations: Yes/No
- Contains Manga/Manhua/Manhwa: Yes/No
- Has CloudFlare Protection: Yes/No

**Comment by dipu-bd** [comment]
#1102

**Comment by saphiejie** [comment]
HI what does this mean? does this mean allnovelfull is already on the list of sites?
