### ISSUE TITLE
Allow vercel/render deployment

### ISSUE THREAD

**Issue by damare01** [dipu-bd/lightnovel-crawler#1301]
Vercel supports python scripts. I tried running it and it worked, but it stopped after 40 minutes or so. 

Reason why it stopped running:

Buiding failed because it is not a webapp = might be solve by this [https://www.marclittlemore.com/serverless-telegram-chatbot-vercel/](https://www.marclittlemore.com/serverless-telegram-chatbot-vercel/)

or

because of this 

`WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv`

**Comment by damare01** [comment]
I also tried deploying it on railway and it worked perfectly, I think it has more uptime than heroku.

**Comment by damare01** [comment]
@dipu-bd for discord [https://ianmitchell.dev/blog/deploying-a-discord-bot-as-a-vercel-serverless-function](https://ianmitchell.dev/blog/deploying-a-discord-bot-as-a-vercel-serverless-function)

**Comment by dipu-bd** [comment]
Converting to web app requires rewriting the entire project in JS. It would a completely separate project altogether.
