### ISSUE TITLE
Consider using some free proxy servers

### ISSUE THREAD

**Issue by damare01** [dipu-bd/lightnovel-crawler#1304]
## Let us know

**Novel URL**:     https://www.lightnovelpub.com/novel/bank-of-the-universe-12032016
**App Location**:    Discord and Telegram
**App Version**:   2.29.7

## Describe this issue

Unable to crawl

```
022-03-19 05:04:32,926 [ERROR] (lncrawl.core.downloader)
Body is empty: https://www.lightnovelpub.com/novel/bank-of-the-universe-12032016/1036-chapter-285


2022-03-19 05:04:36,250 [ERROR] (lncrawl.core.downloader)
Body is empty: https://www.lightnovelpub.com/novel/bank-of-the-universe-12032016/1036-chapter-287


2022-03-19 05:04:34,820 [ERROR] (lncrawl.core.downloader)
Body is empty: https://www.lightnovelpub.com/novel/bank-of-the-universe-12032016/1036-chapter-286

```

**Comment by dipu-bd** [comment]
lightnovelpub seems to block consecutive requests for an IP after downloading 200 or so chapters. 

to solve this issue we can consider using some free proxy servers

**Comment by dipu-bd** [comment]
I found a nice package: https://pypi.org/project/free-proxy/

Unfortunately it has become so popular that https proxies are hard to acquire. But there are lots of http proxies available.

Now the crawler will automatically change the proxy servers after 30s interval.
