### ISSUE TITLE
Fix https://ranobes.net

### ISSUE THREAD

**Issue by Drie023** [dipu-bd/lightnovel-crawler#1307]
**Novel URL**:     https://ranobes.net
**App Location**:    PIP 
**App Version**:   v.2.29.7

## Describe this issue
❗ Error: 403 Client Error: Forbidden for url:
![Screenshot_2022_0320_121559](https://user-images.githubusercontent.com/101960869/159147994-ecd12957-f2a7-4137-a5e8-dbf49ffb908c.png)

**Comment by dipu-bd** [comment]
Ranobes is blocking the connection through cloudflare. Can't do anything about it for now
