### ISSUE TITLE
Fix this source: boxnovel.com

### ISSUE THREAD

**Issue by dastrdly6585** [dipu-bd/lightnovel-crawler#1312]
## Let us know

**Novel URL**:     https://boxnovel.com/novel/the-man-picked-up-by-the-gods-reboot/
**App Location**:    EXE
**App Version**:   2.29.7

## Describe this issue

Chapters downloaded after the source refactoring are empty (app states that the body is empty).  

By adding debug print statements to the `boxnovel.py` source, I determined that `contents = soup.select_one('div.text-left')` correctly pulls the contents, but `self.cleaner.extract_contents(contents)` returns nothing.

![boxnovel_empty_body](https://user-images.githubusercontent.com/13990010/160219198-41546e53-e3b7-447c-81c2-461c5e7e3056.png)

**Comment by dipu-bd** [comment]
try the latest version: https://github.com/dipu-bd/lightnovel-crawler/releases/tag/v2.30.0

**Comment by dastrdly6585** [comment]
Using the latest version solves the problem.
