### ISSUE TITLE
Boxnovel and MyBoxnovel

### ISSUE THREAD

**Issue by damare01** [dipu-bd/lightnovel-crawler#1315]
## Describe the bug

`12:02:19 DEBUG    Error: HTTPSConnectionPool(host='boxnovel.com', port=443): Max retries exceeded with url: /novel/i-can-track-everything/chapter-306/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f10643e8e80>, 'Connection to boxnovel.com timed out. (connect timeout=7)')). Retrying...
12:02:19 DEBUG    Error: 'MyBoxNovelCrawler' object has no attribute 'cleaner'. Retrying...
12:02:19 DEBUG    Error: 'MyBoxNovelCrawler' object has no attribute 'cleaner'. Retrying...
12:02:19 DEBUG    Error: 'MyBoxNovelCrawler' object has no attribute 'cleaner'. Retrying...
12:02:28 DEBUG    Downloading chapter 311: https://boxnovel.com/novel/i-can-track-everything/chapter-311/
12:02:28 DEBUG    Error: 'BoxNovelCrawler' object has no attribute 'cleaner'. Retrying...
12:02:28 DEBUG    Downloading chapter 312: https://boxnovel.com/novel/i-can-track-everything/chapter-312/
12:02:28 DEBUG    Error: 'BoxNovelCrawler' object has no attribute 'cleaner'. Retrying...
12:02:29 DEBUG    Downloading chapter 313: https://boxnovel.com/novel/i-can-track-everything/chapter-313/
12:02:29 DEBUG    Downloading chapter 314: https://boxnovel.com/novel/i-can-track-everything/chapter-314/
12:02:29 DEBUG    Error: 'BoxNovelCrawler' object has no attribute 'cleaner'. Retrying...
12:02:29 DEBUG    Error: 'BoxNovelCrawler' object has no attribute 'cleaner'. Retrying...
12:02:31 DEBUG    Downloading chapter 311: https://boxnovel.com/novel/i-can-track-everything/chapter-311/
12:02:31 DEBUG    Downloading chapter 11: https://myboxnovel.com/book/reincarnation-of-the-businesswoman-at-school-boxnovel/chapter-11/
12:02:31 ERROR    Body is empty: https://myboxnovel.com/book/reincarnation-of-the-businesswoman-at-school-boxnovel/chapter-6/
12:02:31 DEBUG    Error: 'BoxNovelCrawler' object has no attribute 'cleaner'. Retrying...
12:02:31 DEBUG    Downloading chapter 312: https://boxnovel.com/novel/i-can-track-everything/chapter-312/
12:02:32 DEBUG    Error: 'BoxNovelCrawler' object has no attribute 'cleaner'. Retrying...
12:02:32 DEBUG    Downloading chapter 12: [https://myboxnovel.com/book/reincarnation-of-](https://myboxnovel.com/book/reincarnation-of-the-businesswoman-at-school-boxnovel/chapter-12/)`

## Let us know

**App source**: Discord and Telegram

**Comment by UltraStudioLTD** [comment]
@damare01,
please close this issue since it ...
1. doesn't match format of **[Source Issue]** type issue
2. is duplicate.
**boxnovel.com** is mentioned in #1312 and **myboxnovel.com** is mentioned in #1291.
