### ISSUE TITLE
https://allnovelfull.com/

### ISSUE THREAD

**Issue by Brian-Zombait** [dipu-bd/lightnovel-crawler#1317]
Attempted to use LC on this site, not supported. Verified that it is not in the README.ME.
Looked in the sources section and it is not listed. Please see about adding it. Thank you.
 Checked, not supported.
 N/A

 did not find anything in the last half year.
 N/A

- Language: English
- Supports Searching: Yes
- Contains Machine Translations: unknown
- Contains Manga/Manhua/Manhwa:  (comic style - no but has stories listed as manhua)
- Has CloudFlare Protection: No

**Comment by dipu-bd** [comment]
You forgot to check #1102 

I will close the other issue however in favor of this one
