### ISSUE TITLE
! Error: 'NoneType' object has no attribute 'find_all'

### ISSUE THREAD

**Issue by SirGryphin** [dipu-bd/lightnovel-crawler#132]
When trying to download "Killing Gods" book, I select the source and site then I get this error. I think it a problem with the site novelonlinefree.info as the second source for the book works okay.

```

? Enter novel page url or query novel:  Killing Gods
Searching |██████████▌                     | 5/15https://readnovelfull.com/search?keyword=killing+gods
Searching |████████████████████████████████| 15/15
? Which one is your novel?  2. Killing Gods [in 2 sources]
? Choose a source to download?  1. https://novelonlinefree.info/novel/killing_gods
Retrieving novel info...

 ! Error: 'NoneType' object has no attribute 'find_all'

```

- Novel URL: https://novelonlinefree.info/novel/killing_gods
- App Version: 2.9.6
- Package: PIP
- OS: Windows 10

**Comment by dipu-bd** [comment]
The problem is with https://novelonlinefree.info/
The site is not available now. It is transfered to https://bestlightnovel.com/
I will update this in the next release.
