### ISSUE TITLE
Posibble solutions for cloudflare

### ISSUE THREAD

**Issue by damare01** [dipu-bd/lightnovel-crawler#1321]
[How to bypass CloudFlare bot protection ?](https://jychp.medium.com/how-to-bypass-cloudflare-bot-protection-1f2c6c0c36fb)
[How to bypass Cloudflare bot protection (and more)](https://www.reddit.com/r/netsec/comments/mdna36/comment/gscwu3l/?utm_source=share&utm_medium=web2x&context=3)
[How to bypass Cloudflare bot protection in selenium](https://stackoverflow.com/questions/67341346/how-to-bypass-cloudflare-bot-protection-in-selenium)

**Comment by damare01** [comment]
[How to Bypass CloudFlare Detection with Selenium](https://sinister.ly/Thread-How-to-Bypass-CloudFlare-Detection-with-Selenium?pid=1069575#pid1069575)
[How to bypass Cloudflare bot protection in selenium](https://errorsfixing.com/how-to-bypass-cloudflare-bot-protection-in-selenium/)

**Comment by yudilee** [comment]
As i remember before lightnovel-crawler use cfscrape, we considering using selenium but it is too slow.

**Comment by damare01** [comment]
How about this two? Will they work?

[How to bypass CloudFlare bot protection ?](https://jychp.medium.com/how-to-bypass-cloudflare-bot-protection-1f2c6c0c36fb)
[How to bypass Cloudflare bot protection (and more)](https://www.reddit.com/r/netsec/comments/mdna36/comment/gscwu3l/?utm_source=share&utm_medium=web2x&context=3)

**Comment by dipu-bd** [comment]
@damare01 no. these won't work. they were patched by cloudflare. only valid solution is to use selenium. but as yudilee says, it is slow and resource hungry.
