### ISSUE TITLE
Not downloading from an URL which previously worked

### ISSUE THREAD

**Issue by joydip1203** [dipu-bd/lightnovel-crawler#1325]
Hello,

it's been months now but currently we are unable to download novels from the below URL
"**https://www.lightnovelpub.com**/"
It had been working earlier but not any more, can you provide the cause of this problem.

.

**Comment by dipu-bd** [comment]
They are using cloudflare captcha protection. It is not possible to bypass via a bot. You can use alternative sites like https://lightnovelreader.org/
