### ISSUE TITLE
Fix this source - https://www.flying-lines.com/

### ISSUE THREAD

**Issue by mesmerlord** [dipu-bd/lightnovel-crawler#1326]
## Let us know

**Novel URL**:    https://www.flying-lines.com/ 
**App Location**:    Source, I'm using this as a PIP package 
**App Version**:   Latest  

## Describe this issue

Flyinglines seems to be the only source(EN one, I could find) that has a base_url variable, that is actually used in the same class. This seems to get converted to a list for some reason, which causes below issue: 

![image](https://user-images.githubusercontent.com/76161333/161864356-88a78bb1-0a3f-471e-b036-4b0291ef34c4.png)

It is an easy fix, at [this line](https://github.com/dipu-bd/lightnovel-crawler/blob/97c9ab328eeb9e88dde7711e9a0a7c49c9d6c3fe/sources/en/f/flyinglines.py#L72) , instead of 

`url = url % (self.base_url.strip('/'), self.novel_id, chapter['id'], time, sign)`

It should be :

`url = url % (self.base_url[0].strip('/'), self.novel_id, chapter['id'], time, sign)`

or just `url = url % (str(self.base_url).strip('/'), self.novel_id, chapter['id'], time, sign)`

I'd create a PR for this, but this seems like an easy enough fix

**Comment by dipu-bd** [comment]
fixed the mentioned issue. please check if it is working now
