### ISSUE TITLE
1stkissnovel - Not Working

### ISSUE THREAD

**Issue by levinuiiy** [dipu-bd/lightnovel-crawler#1328]
Suddenly didn't work today when i checked, 

**Novel URL**:     <your novel url or query> 

Failed to get novel info.
`403 Client Error: Forbidden for url: https://1stkissnovel.love/novel/disaster-artist/`

**App Location**:    PIP | EXE | Discord | Telegram 
Lightnovel Crawler - Bot

**App Version**:   x.y.z  

2.30.0 on Lightnovel Crawler bot

https://www.dropbox.com/s/seyk2erts2t7nom/E4127E59-FE6C-4B28-B6C2-37FD0C869BB5.jpeg?dl=0

**Comment by dipu-bd** [comment]
it's a cloudflare issue
