### ISSUE TITLE
Infer novel page url from chapter url

### ISSUE THREAD

**Issue by dipu-bd** [dipu-bd/lightnovel-crawler#133]
This may require adding a new method `infer_novel_page(any_url)` to all crawler files. There are so many crawlers now. This change will take time.

Benefits of this change: 
- Ability to crawl miscellaneous chapters using `--chapters` option.
- User input will recognize a whole lot of URLs.

Be cautious for:
- This may not be compatible with all sources. Implementing it to some sources may be more complex than it seems. This method should be optional.

**Comment by 161910201001** [comment]
https://indomtl.com/

**Comment by dipu-bd** [comment]
Should be possible after implementing #1001
