### ISSUE TITLE
https://www.mtlnovel.com/

### ISSUE THREAD

**Issue by doodman06** [dipu-bd/lightnovel-crawler#1331]
## Let us know

**Novel URL**: https://www.mtlnovel.com/the-truth-of-magic/
**App Location**:  EXE
**App Version**:   2.30.0

## Describe this issue

Cannot crawl on site

? Enter novel page url or query novel: the truth
Searching: 100%|█████████████████████████████████████████████████████████████████| 135/135 [00:33<00:00,  3.99source/s]
? Which one is your novel? 2. The Truth of Magic [in 17 sources]
? Choose a source to download? 13. https://www.mtlnovel.com/the-truth-of-magic/
Retrieving novel info...
https://www.mtlnovel.com/the-truth-of-magic/
? Do you want to choose another novel? Yes
? Which one is your novel? 2. The Truth of Magic [in 17 sources]
? Choose a source to download? 14. https://www.mtlnovel.com/the-truth-of-magic/
Retrieving novel info...
https://www.mtlnovel.com/the-truth-of-magic/
? Do you want to choose another novel? No

 ! Error: 403 Client Error: Forbidden for url: http://www.mtlnovel.com/the-truth-of-magic/

**Comment by dipu-bd** [comment]
This is a issue caused by cloudflare protection. You can use google colab to bypass it sometimes.
