### ISSUE TITLE
Fix 1stkissnovel.love

### ISSUE THREAD

**Issue by 3dycosmo** [dipu-bd/lightnovel-crawler#1334]
https://1stkissnovel.love/
https://1stkissnovel.love/novel/mecha-hurricane/
**Colab  v2.30.0**
## kissnovel no longer works at all
![Screenshot_20220416_073901](https://user-images.githubusercontent.com/4585442/163655106-e7c9c752-6195-470f-ad8b-4df61d5721ac.jpg)

**Comment by mesmerlord** [comment]
It works now for me at least, either you're downloading from them too often or they recently added some IP block for too many requests. An easy way to fix this would be to change self.executor for just this crawler from 5 workers to something like 2 or even 1. @dipu-bd

**Comment by samanta-widjaja** [comment]
I also cannot use this site. But my error is 400 client error bad request for admin-ajax

**Comment by dipu-bd** [comment]
fixed
