### ISSUE TITLE
Fix www.readwn.com

### ISSUE THREAD

**Issue by 3dycosmo** [dipu-bd/lightnovel-crawler#1335]
Colab v2.30.0
https://www.readwn.com/

> https://www.readwn.com/novel/dont-pretend-to-be-the-heroine.html
**Novel from webnovel less than 100 chaps**
![webnovel novel](https://user-images.githubusercontent.com/4585442/163655444-4db71fa0-2314-4ece-9ded-1273e7a2e889.jpg)

>  https://www.readwn.com/novel/the-archdukes-gorgeous-wedding-was-a-fraud.html 
**Korean novels with less than 100 chaps**
![korean novel](https://user-images.githubusercontent.com/4585442/163655450-34bd1e6e-6d1d-4e95-8612-62a7b1e6d7aa.jpg)

**Comment by mesmerlord** [comment]
@dipu-bd I can take this on, its an easy fix and also relates to lightnovelepub, novelmt, novelmtl and ltnovel sources, since they're probably running off the same code/template.

**Comment by mesmerlord** [comment]
@dipu-bd , please check https://github.com/dipu-bd/lightnovel-crawler/pull/1340 and close this issue if its alright

**Comment by shagunchandel** [comment]
sir i am reciving this error in some sites 
"Detected a cloudflare version 2 challenge, this feature is not available in opensource (free) version."
how should i fix this ?
