### ISSUE TITLE
login to Wuxiaworld.

### ISSUE THREAD

**Issue by Mentole** [dipu-bd/lightnovel-crawler#1337]
Can't login to Wuxiaworld. Many of the completed novels require you to be logged in to access the complete chapters. I use to just use Web to Epub for that site because of this, but it no longer works because of the format change.

**Comment by budikesuma** [comment]
I have also been waiting for the ability to login to wuxiaworld.com for a long time.  
   If it is possible to immediately unlock the chapters with the karma that is in our account, well, our karma is very much not to be wasted.

**Comment by dipu-bd** [comment]
You can login to [WuxiaWorld](https://www.wuxiaworld.com/) now using the Bearer token. However it will be bit tricky to obtain the token for the beginners. I will decribe the entire process here.

- First login to wuxiaworld using your browser (chrome is used for this example).
- Go to your profile page: https://www.wuxiaworld.com/manage/profile/ 
- Now open the **Developer Tools** from the Chrome options > More Tools
<img width="1056" alt="image" src="https://user-images.githubusercontent.com/5158124/168449263-5e92a7ea-675a-4d1b-8f8c-62e578041bc0.png">

- Go to **Network** tab
<img width="876" alt="image" src="https://user-images.githubusercontent.com/5158124/168449284-2cf8ffa2-1bd1-4020-be81-2568ed5d3b7d.png">

- Refresh the page
- Search for "GetMyUser"
<img width="1056" alt="image" src="https://user-images.githubusercontent.com/5158124/168449308-aa11df6a-f6ec-404b-b69e-3fc70a93a1bc.png">

- Copy the value of the Authorization header in **Request headers** section.
<img width="953" alt="image" src="https://user-images.githubusercontent.com/5158124/168449340-293761d6-3f3b-4148-9fe7-9696d7957258.png">

- Now open the lightnovel crawler application using these token as `--login` options:

```
$ lncrawl --login Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjZBOEYzNTkwRDU2MDAyRDAxRDgzQUMyOTJFQjkyN0FENTk2NzFFMDBSUzI1NiIsIng1dCI6ImFvODFrTlZnQXRBZGc2d3BMcmtuclZsbkhnQSIsInR5cCI6ImF0K2p3dCJ9.eyJpc3MiOiJodHRwczovL2lkZW50aXR5Lnd1eGlhd29ybGQuY29tIiwibmJmIjoxNjUyNTY1MDgzLCJpYXQiOjE2NTI1NjUwODMsImV4cCI6MTY1NTE1NzA4MywiYXVkIjoiYXBpIiwic2NvcGUiOlsib3BlbmlkIiwicHJvZmlsZSIsImFwaSIsImVtYWlsIiwib2ZmbGluZV9hY2Nlc3MiXSwiYW1yIjpbInB3ZCJdLCJjbGllbnRfaWQiOiJ3dXhpYXdvcmxkX3NwYSIsInN1YiI6ImZlZjAzNWY5LWExZmUtNGU0ZC1hN2UwLTNjZmQwOWY4ZTgyMyIsImF1dGhfdGltZSI6MTY1MjU2NTA4MSwiaWRwIjoibG9jYWwiLCJuYW1lIjoidGlwb2ZtaW5kIiwiZW1haWwiOiJkaXB1LnN1ZGlwdGFAZ21haWwuY29tIiwic2lkIjoiM0JBMTlDQUFDQTUyRDJGNjUyNTY1MDRCMjc1QjZDQzYiLCJqdGkiOiJBNzk0RTNCMUVCRDMyNkZERTA2NDI1RjhEMEUzQTVBRCJ9.wUm9ot3wRopnVf64GNlZ7p-I8yfI7_fvEmuqfGgpbpVhWtXVOh9jSIErUugMn-0ofPMKKAi3LYtKBzpU2X5ZHH2xru-MgHqzBFadxJM2C3d9GfgPwwQTfvNv0m-Gj_7g9Vi0NY7Ck2kyjys8RJVmU2HE9_96VG8TGu9aB_qLBWVmh7N6szfmFbbjmad7OjWShb8RqdLFTL6AhhIWuZuuJoRzkmZzS-erkQNoxAIqXWS1Rj5Ji1Uc9JXbvig0DUytCkToilK3zptYCuAtRejjzvc6Ohs24Qfe3YXe3Tu-7xjM9vj_8xzZ2X9hlHlwfACad2YJ5XQN_5PLox4YcmzT-Xa95sTw-c9DvTpYKWBam0occsqB0JWyfLUJNJskRysA19H1T9HvOg2-GYpOFcM0iQ3TeOo9eY2QOuj75lKoxJJUKYlgsr9or-iK-dEpiJ7lodMCykICtVC5TzwK3Q17I1qVaxmd27wwbx2qaCcMOsJZeDcpxO09_Nx1zu2AnK1g-D8J5pNUey3tMZtS1cBRG_7S_T0qSwJY0rzuRTlaaE2IlKoAy0pJ4eoUp7mkL1OqMdw_RI-25SIUaTRIWxE3IgHOQTmwIxNk664oVJWMbxB9O38h7PB8egO8HzGbGIG1EM3kHfNoOSUDu1Ujc94wdHFD_9KwjpqTbN2K6biY8cI
```

Now you can access locked contents accessible to your wuxiaworld account.
