### ISSUE TITLE
Add an option to include proxies

### ISSUE THREAD

**Issue by mesmerlord** [dipu-bd/lightnovel-crawler#1341]
I'm relying on this package for a site of mine, so if possible I'd like to add a feature to use proxies for the requests as I crawl the aggregator sites pretty frequently.

You can assign this to me, and I'll create add an argument to the commandline some thing like "--proxy-file={file_location}" which will just read a text file in this format: "{IP_ADDRESS}:{PORT}:{USERNAME}:{PASSWORD}". I've worked with this using Cloudscraper so it won't be an issue, and I'll edit the get_soup function to use proxy for request instead of plain request(random proxy from the list of proxies)

**Comment by dipu-bd** [comment]
I added a `--auto-proxy` option in recent changes. It will automatically load proxies from a free proxy site to use.

**Comment by dipu-bd** [comment]
Please give an example code of how you provide proxy with username & password. I will add support for proxy file as well

**Comment by mesmerlord** [comment]
Hey @dipu-bd , I've created a PR for this. Please take a look

**Comment by dipu-bd** [comment]
I added an option `--proxy-file` to pass the file path where you have the list of proxies:

Here is a sample of allowed value formats:

```
192.168.1.1
192.168.1.1:9898
192.168.1.1@user:pass
192.168.1.1:1551@user:pass
http://10.10.1.1
https://10.10.1.1:9898
http://10.10.1.1@user:pass
https://10.10.1.1:1551@user:pass
```

One proxy per line. In `SCHEME://HOST:PORT@USER:PASS` format. Here all except HOST is optional.
