### ISSUE TITLE
Fix this source: webnovel.com not grabbing most chapters

### ISSUE THREAD

**Issue by Ultros99** [dipu-bd/lightnovel-crawler#1350]
Yes.

================================================================================
                          [#] Lightnovel Crawler v2.30.0
                  https://github.com/dipu-bd/lightnovel-crawler
--------------------------------------------------------------------------------

-> Press  Ctrl + C  to exit

? Enter novel page url or query novel: https://www.webnovel.com/book/throne-of-magical-arcana_6838665602002005
Retrieving novel info...
https://www.webnovel.com/book/throne-of-magical-arcana_6838665602002005
NOVEL: Throne of Magical Arcana
11 volumes and 39 chapters found
? Enter output directory: C:\Users\Raphael\Downloads\Lightnovels\www-webnovel-com\Throne of Magical Arcana

## Describe this issue

Every chapter past 39 is not available for free, and it seems it prevents the crawler from even detecting them in the first place.
As it stands, it's useless, sadly.

**Comment by UltraStudioLTD** [comment]
It's not a issue that crawler is unable to get non-free chapters. This tool isn't paywall bypasser or anything like that.
Want non-free chapters, buy them

**Comment by UltraStudioLTD** [comment]
But even if you bought them crawler still wouldn't get them since it works without login

**Comment by UltraStudioLTD** [comment]
@dipu-bd I suggest closing this issue

**Comment by Ultros99** [comment]
I see, guess it's intentional then. Makes it useless for myself though if it can't even make an epub if I do buy them.

**Comment by UltraStudioLTD** [comment]
> I see, guess it's intentional then. Makes it useless for myself though if it can't even make an epub if I do buy them.

As far as I know there is no official API for Web Novel and only way to get unlocked chapters unofficially would be automating log-in process in minimal browser using **selenium** which would greatly increase size of project and also decrease speed of crawling. If I remember correctly author (@dipu-bd ) already rejected **selenium**'s usage.

**Comment by Ultros99** [comment]
Okay fair enough, have a nice day. I'll close this here.
