### ISSUE TITLE
[Feature] WEB: switching between chapters by keyboard

### ISSUE THREAD

**Issue by idMysteries** [dipu-bd/lightnovel-crawler#1351]
Add switching between chapters, like this
``` js
$(document).keyup((evt) => {
  if (evt.key === 'ArrowLeft')
    prev.click();
  if (evt.key === 'ArrowRight')
    next.click();
});
```

**Comment by mesmerlord** [comment]
Go to https://www.wuxiaworld.eu/ , its created using this package for scraping. You can add any requests for a novel you have an accepted source from here, just post it on the discord
