### ISSUE TITLE
Windows Binary not working

### ISSUE THREAD

**Issue by Suleman-Elahi** [dipu-bd/lightnovel-crawler#1352]
Tried the latest Windows binary on my Windows 11 PC. This error shows. Binary from the release before the latest one seems to be working fine.

![image](https://user-images.githubusercontent.com/24384996/165947539-af3efdc0-a9c8-4f4a-b355-35b72f872d95.png)

Also in the command prompt...

![image](https://user-images.githubusercontent.com/24384996/165947737-5c353dc1-044c-4951-a982-7bfdffb3f4c5.png)

**Comment by dipu-bd** [comment]
Did you put it somewhere that is not accesible? Try putting the exe in your Desktop, and run it
