### ISSUE TITLE
hostednovel.com is not working

### ISSUE THREAD

**Issue by cybrouillard** [dipu-bd/lightnovel-crawler#1366]
**Novel URL**:  https://hostednovel.com/11/novel/legend-of-the-great-sage
**App Location**:  EXE
**App Version**:  2.31.0

I tested a few other novels with that source but I always have the same error :
![image](https://user-images.githubusercontent.com/1230676/170845762-0d87dbca-b8a2-4279-80ed-38c0f4715f8c.png)

Thanks for your hard work !

**Comment by SirGryphin** [comment]
Same problem with PIP version 2.31.0, I've had a quick look at source file but it seems they've done a who site redesign.
