### ISSUE TITLE
Error: 'charmap' codec can't encode character

### ISSUE THREAD

**Issue by Recursiivio** [dipu-bd/lightnovel-crawler#137]
OS : Windows 10
lightnovel-crawler ver : 2.9.10
PIP bundle

Novel page : https://www.readlightnovel.org/is-the-strongest-in-another-world-a-hero-a-demon-lord-no-its-a-fairy-desu

```
? Enter novel page url or query novel:  https://www.readlightnovel.org/is-the-strongest-in-another-world-a-hero-a-demo
n-lord-no-its-a-fairy-desu
Retrieving novel info...

 ! Error: 'charmap' codec can't encode character '\u2019' in position 69: character maps to <undefined>
```

**Comment by dipu-bd** [comment]
Please provide these information:
- OS Name
- lightnovel-crawler version
- are you using pip or exe bundle?

**Comment by Recursiivio** [comment]
My apologies, edited.

**Comment by dipu-bd** [comment]
this should be fixed now
