### ISSUE TITLE
Fix this source: allnovelfull.com

### ISSUE THREAD

**Issue by juh9870** [dipu-bd/lightnovel-crawler#1382]
## Let us know

**Novel URL**:     https://allnovelfull.com/dimensional-descent.html
**App Location**:    EXE
**App Version**:   [v2.31.0](https://github.com/dipu-bd/lightnovel-crawler/releases/tag/v2.31.0)

## Describe this issue

Every other paragraph of text is missing.

Screenshot of how the text loons on a website
![image](https://user-images.githubusercontent.com/15922601/172679320-7d824527-eda6-4c9c-aebf-d178295f1ea3.png)

How it looks in exported book
![image](https://user-images.githubusercontent.com/15922601/172679368-2fc169f3-7e5c-4de2-8c22-2f36dac7123b.png)

Following paragraphs are missing from the text
![image](https://user-images.githubusercontent.com/15922601/172679496-0fc921e3-4d9b-4645-9ff8-032a0697a03e.png)

Exported chapter 1 json: https://pastebin.com/5AbUwmEB

**Comment by shagunchandel** [comment]
same problem here it wasnt there few days ago
