### ISSUE TITLE
Discord invite link doesn't work.

### ISSUE THREAD

**Issue by JasonAimer** [dipu-bd/lightnovel-crawler#1385]
Hello, I just tried to invite the lightnovel-crawler bot to my server with the link in the github page. It does load to where I can choose my server, but after accepting the required permissions it says: "This integration is private. Only the application owner can add it."
![2022-06-12_09-42](https://user-images.githubusercontent.com/66317129/173222794-18341dd4-4857-4c14-92ae-ffe005cf1a8d.png)

**Comment by dipu-bd** [comment]
you can not add the bot to your server. it has reached the integration limit
