### ISSUE TITLE
Encoding error downloading some of the chapters

### ISSUE THREAD

**Issue by miracle152005** [dipu-bd/lightnovel-crawler#139]
Hi

**Describe the bug**
While downloading the chapters for some of them I get the error "encoding error : input conversion failed due to input error, bytes 0x9D 0x3C 0x2F 0x70"

**Let us know**
- Novel URL: http://novelfull.com/battle-through-the-heavens.html
- App Version: 2.9.10
- Package: [pip
- OS: Ubuntu Budgie 18.04

Could you please take a look

Thanks.

Best regards
miracle152005

**Comment by yudilee** [comment]
I have already try and success in getting error. after some checking on that chapter i found that chapter has mandarin/raw text in it like this 
![image](https://user-images.githubusercontent.com/7065691/57991195-9356b000-7ad7-11e9-8d8b-63cecf151519.png)
so i think better to use other source. I recommend you to use this toc link https://www.wuxiaworld.com/novel/battle-through-the-heavens

**Comment by dipu-bd** [comment]
One possible solution is to cleanup these mandarin texts before processing chapter body. It should be better to implement this on `app.py`

**Comment by dipu-bd** [comment]
this should be fixed now
