### ISSUE TITLE
https://travistranslations.com/ "body is empty"

### ISSUE THREAD

**Issue by mygithub-acct** [dipu-bd/lightnovel-crawler#1398]
## Let us know

**Novel URL**: https://travistranslations.com/novel/53820/blue-outline/
**App Location**:    PIP
**App Version**:   2.31.0

## Describe this issue

Body is empty error across all the chapters when try to download

![image](https://user-images.githubusercontent.com/71422313/173705374-11190073-51aa-493f-be59-b3f5ddcb57ad.png)

**Comment by dipu-bd** [comment]
#1397
