### ISSUE TITLE
Fix this source webnovel not working

### ISSUE THREAD

**Issue by Trafford666** [dipu-bd/lightnovel-crawler#1425]
It was once here, but the Webnovel source is still not working... any solutions to this?

**Comment by Jemeni11** [comment]
I have no idea when it will be fixed, but you can use [WebToEpub](https://github.com/dteviot/WebToEpub). 
How to use WebToEpub to download from WebNovel:  https://github.com/dteviot/WebToEpub/issues/754#issuecomment-1150327036

**Comment by dipu-bd** [comment]
Duplicate of #1362
