### ISSUE TITLE
Fix book.qidian.com

### ISSUE THREAD

**Issue by yikaii** [dipu-bd/lightnovel-crawler#1432]
## Let us know

**Novel URL**:     <https://book.qidian.com/info/1887208/> 
**App Location**:    PIP | EXE | **Discord** | Telegram 
**App Version**:   Lightnovel Crawler 

## Describe this issue

bot and google collab wont work. it will say no novel title, probably because its chinese. i assume its because of unicode or something

![image](https://user-images.githubusercontent.com/106315170/179384469-6c12422b-4e7c-4c31-9d42-e1167e241581.png)

**Comment by yikaii** [comment]
forgot to add screenshot for google collab
![image](https://user-images.githubusercontent.com/106315170/179384577-2656c407-1fd5-48f2-97c4-efdf03d9d2c7.png)

**Comment by dipu-bd** [comment]
They are updating cookies using a custom javascript method on page load. To overcome this, a javascript enabled browser is required.

**Comment by dipu-bd** [comment]
Even headless browser is not working. The page falls into infinite loop in selenium. I am going mark qidian as down since this has become too difficult to crawl.
