### ISSUE TITLE
https://bonnovel.com

### ISSUE THREAD

**Issue by levinuiiy** [dipu-bd/lightnovel-crawler#1436]
I checked, & none for now

No, it has not been requested

- Language: English
- Supports Searching: Yes
- Contains Machine Translations: No
- Contains Manga/Manhua/Manhwa: No
- Has CloudFlare Protection: Yes/No, i think its No

**Comment by mooglestiltzkin** [comment]
noticed some chapters were skipped when ripping. but when check the site manually, the chapters were available and working. any ideas why?

http://boxnovel.org/i-have-a-mansion-in-the-post-apocalyptic-world-chapter-652-quantum-computer-research-institute

**Comment by dipu-bd** [comment]
@mooglestiltzkin This is a source request for `bonnovel`. Your issue seems to be about box novel. Create another issue with it.
