### ISSUE TITLE
isuue with comrademao site

### ISSUE THREAD

**Issue by deepand8853** [dipu-bd/lightnovel-crawler#144]
**Describe the bug**
Geting error message as 
      ! Error: 'int' object is not subscriptable
for the Comrade mao site(https://comrademao.com)

**Let us know**
- Novel URL: https://comrademao.com/novel/zhanxian/
- App Version: #2.9.11
- Package: PIP
- OS:  Windows 10

**For Reference**

![image](https://user-images.githubusercontent.com/41732973/58431827-35c0f580-80cd-11e9-9190-5bebba2e7ff6.png)

Thanks for the help

**Comment by yudilee** [comment]
There is change in comradmao sites, they seems to revert to old ways to listing toc so reverting crawler to old version should get it right. Already pull request #145 for this issue

**Comment by dipu-bd** [comment]
merged
