### ISSUE TITLE
Wuxiaworld Login Save

### ISSUE THREAD

**Issue by SirGryphin** [dipu-bd/lightnovel-crawler#1441]
Is there anyway to save login email and password locally and use that so I don't have to paste it in everytime?

**Comment by budikesuma** [comment]
@SirGryphin 

Yup, with the Google colab method, you don't need to think about tokens/passes anymore.

You just need to paste your token/pass into the `Google colab template` available on the official `lightnovel-crawler` server, until the `wuxiaworld.com` site changes its login script...

**Comment by dipu-bd** [comment]
The console app was meant to be run as a standalone single time process. It does not save any states anywhere. You can write a bash/shell script and save your passwords there, and lunch the app using it.

Bash script example:

```bash
#!/usr/bin/env sh

USERNAME="Bearer"
PASSWORD="asdkahsd...asdasdas"

exec lncrawl -u "$USERNAME" -p "$PASSWORD" $@
```

**Comment by SirGryphin** [comment]
@dipu-bd I wrote a simple .bat file called "wux.bat" I put in system32. 

`CD C:\Users\User\Downloads

lncrawl --format epub --login email password`

then when I open command prompt i just type "wux" and it changes to correct folder and launches lncrawl with settings I need.
