### ISSUE TITLE
Fix ranobes.net

### ISSUE THREAD

**Issue by undead2146** [dipu-bd/lightnovel-crawler#1444]
Nobody else posted about ranobes on the support page yet

**Novel URL**:     any novel on https://ranobes.net/ 
**App Location**:    On the EXE launcher
**App Version**:   2.31.0

## Describe this issue
Basically a 403 error
 ! Error: 403 Client Error: Forbidden for url: https://ranobes.net/novels/50188-spirit-realm-v197177.html
 <class 'requests.exceptions.HTTPError'>

 File "lncrawl\core\crawler.py", line 281, in get_soup
    response = self.get_response(*args, **kwargs)
  File "lncrawl\core\crawler.py", line 235, in get_response
    return self.__process_response(response)
  File "lncrawl\core\crawler.py", line 207, in __process_response
    response.raise_for_status()
  File "requests\models.py", line 960, in raise_for_status

**Comment by dipu-bd** [comment]
403 error happens because of cloudflare human captcha which is not solvable by machines.
