### ISSUE TITLE
https://sj.uukanshu.com/

### ISSUE THREAD

**Issue by yikaii** [dipu-bd/lightnovel-crawler#1457]
- Language: Chinese
- Supports Searching: Yes
- Contains Machine Translations: No
- Contains Manga/Manhua/Manhwa: No
- Has CloudFlare Protection: Yes/No (no clue)

**Comment by idMysteries** [comment]
Copy https://github.com/dipu-bd/lightnovel-crawler/issues/515
@dipu-bd

**Comment by idMysteries** [comment]
@dipu-bd can you close the issue?
