### ISSUE TITLE
Fix this source [webnovel.com]

### ISSUE THREAD

**Issue by jimster6543** [dipu-bd/lightnovel-crawler#1463]
## Let us know

**Novel URL**:     https://www.webnovel.com 
**App Location**:    EXE 
**App Version**:   v2.31.0 

## Describe this issue

Program can't grab chapters but can see the novel.

Below is the generic readout of any attempt to grab a novel:
NOVEL:
0 volumes and 0 chapters found

**Comment by idMysteries** [comment]
It should be working now https://github.com/dipu-bd/lightnovel-crawler/pull/1455

**Comment by jimster6543** [comment]
I works now, I'll close this issue.
