### ISSUE TITLE
Fix this source [lightnovelpub.com]

### ISSUE THREAD

**Issue by dastrdly6585** [dipu-bd/lightnovel-crawler#1465]
## Let us know

**Novel URL**:     https://www.lightnovelpub.com/novel/reformation-of-the-deadbeat-noble-31011236, https://www.lightnovelpub.com/novel/the-villainess-lives-twice-11072357
**App Location**:    EXE
**App Version**:   2.31.0
## Describe this issue

Certain novels on lightnovelpub appear to have the chapters incorrectly detected.  When the crawler splits the novel into volumes, each volume is an exact replica of the first volume.

**Comment by idMysteries** [comment]
Doesn't look like a source error @dipu-bd

**Comment by dastrdly6585** [comment]
One common factor between these two novels is that the app claims that both have 400 chapters exactly when they have 358 and 333 chapters. Each volume in the output epub is a copy of the first 100 chapters.  Here's the generated meta.json from one of the two novels (where I've scrubbed the output path):
[meta.txt](https://github.com/dipu-bd/lightnovel-crawler/files/9381848/meta.txt)

**Comment by idMysteries** [comment]
there should be several epub files on the output, it seems.

**Comment by idMysteries** [comment]
There should be several epub files on the output, it seems.

**Comment by idMysteries** [comment]
Oh...the meta file is wrong... Really! OK... I'll look at the code more closely

**Comment by dastrdly6585** [comment]
Just confirmed that this issue appears only in the EXE.  I tested the PIP version and the chapter list returns correctly.

**Comment by idMysteries** [comment]
It looks like you had an old source

**Comment by idMysteries** [comment]
C:\Users\%USERNAME%\.lncrawl maybe it should be deleted

**Comment by idMysteries** [comment]
Have you had this update?
![image](https://user-images.githubusercontent.com/11484976/185622561-19e5865e-40da-4b29-a3d3-9872fbf8fa2f.png)

**Comment by dastrdly6585** [comment]
After reinstalling the PIP version to try to fix something else, the issue is now also popping up in the PIP version.  One thing I'm noticing when using the extra logging is that there are a lot of "301 None" extra lines popping up compared to novels which have chapters correctly being found:

```
https://www.lightnovelpub.com:443 "GET /novel/the-villainess-lives-twice-11072357/chapters/page-2 HTTP/1.1" 301 None
2022-08-19 09:15:25,909 [DEBUG] (urllib3.connectionpool)
https://www.lightnovelpub.com:443 "GET /novel/the-villainess-lives-twice-11072357/chapters/page-3 HTTP/1.1" 301 None
2022-08-19 09:15:25,922 [DEBUG] (urllib3.connectionpool)
https://www.lightnovelpub.com:443 "GET /novel/the-villainess-lives-twice-11072357/chapters/page-4 HTTP/1.1" 301 None
2022-08-19 09:15:26,332 [DEBUG] (urllib3.connectionpool)
https://www.lightnovelpub.com:443 "GET /novel/the-villainess-lives-twice-07082217/chapters HTTP/1.1" 200 None
2022-08-19 09:15:26,344 [DEBUG] (urllib3.connectionpool)
https://www.lightnovelpub.com:443 "GET /novel/the-villainess-lives-twice-07082217/chapters HTTP/1.1" 200 None
2022-08-19 09:15:26,346 [DEBUG] (urllib3.connectionpool)
https://www.lightnovelpub.com:443 "GET /novel/the-villainess-lives-twice-07082217/chapters HTTP/1.1" 200 None
```

**Comment by idMysteries** [comment]
It looks like we need to check novel_url for redirects
@dipu-bd

**Comment by idMysteries** [comment]
Oh no no no.
We can find the correct link inside the page.
