### ISSUE TITLE
[WEB] does not find images

### ISSUE THREAD

**Issue by idMysteries** [dipu-bd/lightnovel-crawler#1475]
I need to copy the images folder to the chapters folder.
if new chapters come out, then I have to copy the pictures again.

https://github.com/dipu-bd/lightnovel-crawler/blob/5b32245c2f64f8148fdf5a976ef79b201ebba059/lncrawl/core/downloader.py#L307

![image](https://user-images.githubusercontent.com/11484976/184915553-9af011da-1f44-4711-8a08-25acf4e6d070.png)

Copy from here:
![image](https://user-images.githubusercontent.com/11484976/184914247-fd630f5b-ff39-4de7-99b7-a3bfd1466e48.png)
To here:
![image](https://user-images.githubusercontent.com/11484976/184914430-a5e84402-62b2-4eaf-91c6-982fbf3a9e12.png)

``` html
<p> <img alt="223a3ee2714544aab63204aa64e85495.jpg" src="images/223a3ee2714544aab63204aa64e85495.jpg"/> </p>
```

``` html
<p> <img alt="223a3ee2714544aab63204aa64e85495.jpg" src="../../images/223a3ee2714544aab63204aa64e85495.jpg"/> </p>
```

**Comment by dipu-bd** [comment]
The web binder was not updated after images were introduced. It should be easy to fix.
