### ISSUE TITLE
Can't handle 403 error correctly

### ISSUE THREAD

**Issue by idMysteries** [dipu-bd/lightnovel-crawler#1480]
For ex.: https://api.mtlnation.com/api/v2/chapters/villain-seized-the-assassin-heroine-at-the-start/chapter-120-the-jiangnan-conference-xue-jiner-the-queen-of-the-double-shadows

``` py
    def download_chapter_body(self, chapter):
        data = self.get_json(chapter['data_url'])
        return data['data']['content']
    # end def
```

``` py
    def get_json(self, *args, **kwargs) -> dict:
        kwargs = kwargs or dict()
        headers = kwargs.setdefault('headers', {})
        headers = {k.lower(): v for k, v in headers.items()}
        headers.setdefault('accept', 'application/json, text/javascript, */*')
        response = self.get_response(*args, **kwargs)
        return response.json()
    # end def

```

No json -> exception -> retry https://github.com/dipu-bd/lightnovel-crawler/blob/5b32245c2f64f8148fdf5a976ef79b201ebba059/lncrawl/core/downloader.py#L100

Need except for bad json?
https://github.com/dipu-bd/lightnovel-crawler/blob/5b32245c2f64f8148fdf5a976ef79b201ebba059/lncrawl/core/downloader.py#L95

**Comment by idMysteries** [comment]
Or is it because of the 403 error hmm... Need a test

**Comment by idMysteries** [comment]
https://github.com/dipu-bd/lightnovel-crawler/blob/a70ab79c567fc261d4673ac8f88dbb8c9228a3ae/lncrawl/core/crawler.py#L201

``` py
    def __process_response(self, response: Response) -> Response:
        if response.status_code == 403 and response.reason == 'Forbidden':
            logger.debug('%s\n%s\n%s', '-' * 60, response.text, '-' * 60)
            raise LNException('403 Forbidden! Could not bypass the cloudflare protection.')
        # end if

        response.raise_for_status()
        response.encoding = 'utf8'
        self.cookies.update({
            x.name: x.value
            for x in response.cookies
        })
        return response
    # end def
```

![image](https://user-images.githubusercontent.com/11484976/185477574-e5b46307-98ba-47af-86de-b40d56f03fa0.png)
![image](https://user-images.githubusercontent.com/11484976/185477642-33dab4c1-8038-4a53-ae7e-c5ba067b7d6f.png)

**Comment by dipu-bd** [comment]
Most of the 403 response was found for cloudflare issues. There were so many tickets created for that. That's why I put the error message specifically for 403.

**Comment by idMysteries** [comment]
Should I add "try" to this code?

``` py
    def download_chapter_body(self, chapter):
        data = self.get_json(chapter['data_url'])
        return data['data']['content']
    # end def
```

**Comment by dipu-bd** [comment]
No need to add `try` 

If exceptions happen it will treat the chapter as empty.

**Comment by idMysteries** [comment]
He is trying to do a reconnect, although he will not help here and only wastes time

**Comment by dipu-bd** [comment]
> He is trying to do a reconnect, although he will not help here and only wastes time

I don't understand. What do you mean?

**Comment by idMysteries** [comment]
https://github.com/dipu-bd/lightnovel-crawler/blob/5b32245c2f64f8148fdf5a976ef79b201ebba059/lncrawl/core/downloader.py#L100

**Comment by dipu-bd** [comment]
Ah yes. Its catching any error and retrying 3 times. It should only catch the HTTP errors. I will update the downloader.py to retry only on HTTP errros

**Comment by dipu-bd** [comment]
Updated the downloader.py in dev branch
