### ISSUE TITLE
Webnovel | Qidian FOCK WITHOUT OBFUSCATION

### ISSUE THREAD

**Issue by idMysteries** [dipu-bd/lightnovel-crawler#1494]
I have the code of the Fock crypto function, including unlock, addKeypool! Without obfuscation!
But it's in javascript.
I need some kind of browser emulator for python, damn.

**Comment by idMysteries** [comment]
Selenium seems to be the only option.

**Comment by idMysteries** [comment]
Although perhaps this is not the only option, for sure. You can also try using Node js.

**Comment by idMysteries** [comment]
I will try to run the decryption code on the nodejs server tomorrow.
Perhaps it will be possible to run obfuscated code on the nodejs...
@dipu-bd

**Comment by dipu-bd** [comment]
Take a look at `js2py`

**Comment by idMysteries** [comment]
Haha
``` py
>>> from fock import fock
Traceback (most recent call last):
  File "<pyshell#8>", line 1, in <module>
    from fock import fock
SyntaxError: too many statically nested blocks
```

**Comment by dipu-bd** [comment]
Which package are you using? Can you give me the pypi link?

**Comment by idMysteries** [comment]
``` py
js2py.translate_file('fock.js', 'fock.py')
```

**Comment by idMysteries** [comment]
https://github.com/pyppeteer/pyppeteer
or selenium, or nodejs

**Comment by dipu-bd** [comment]
you don't need to translate the file. just use the `eval_js`

**Comment by idMysteries** [comment]
js file too big

**Comment by idMysteries** [comment]
I think Nodejs is the only option. Or a headless browser..

**Comment by idMysteries** [comment]
https://pypi.org/project/v8eval/

**Comment by dipu-bd** [comment]
we can use NodeJS. although js2py is slower, it may work as well as nodejs too

**Comment by dipu-bd** [comment]
pyppeteer seems pretty reasonable. we can use it.

**Comment by dipu-bd** [comment]
webnovel works as it is. qidian does not work even with pyppeteer. it falls into inifite loop. i moved it to rejected sources.

since both of the sources are taken care of, closing this issue.
