### ISSUE TITLE
[WEB] Poor arrow design

### ISSUE THREAD

**Issue by idMysteries** [dipu-bd/lightnovel-crawler#1496]
![image](https://user-images.githubusercontent.com/11484976/185986036-22e7f359-9b61-42f7-b035-ba69b3b1e2fe.png)

**Comment by dipu-bd** [comment]
Which browser are you using what is your screen size? It looks fine in Chrome:

![image](https://user-images.githubusercontent.com/5158124/186076215-be66d513-f9b9-4ff7-97c8-df0858d97683.png)

**Comment by idMysteries** [comment]
![изображение](https://user-images.githubusercontent.com/11484976/186096666-73aa763a-9533-47c2-8b0e-3b6679632973.png)
Firefox is OK... I'll remove the Сhrome and Edge.

**Comment by dipu-bd** [comment]
> I'll remove the Сhrome and Edge.

Do you mean that it looks poor on Chrome and Edge?

**Comment by idMysteries** [comment]
> Do you mean that it looks poor on Chrome and Edge?
Yeah, for me
