### ISSUE TITLE
https://novelww.com/

### ISSUE THREAD

**Issue by graciagraciagracia** [dipu-bd/lightnovel-crawler#1504]
No

 Yes

- Language: EN
- Supports Searching: Yes
- Contains Machine Translations: Yes
- Contains Manga/Manhua/Manhwa: No
- Has CloudFlare Protection:

**Comment by idMysteries** [comment]
OK
Template of 888novel

**Comment by idMysteries** [comment]
Supports Searching: NO
Google search
