### ISSUE TITLE
https://www.novelpub.com/

### ISSUE THREAD

**Issue by Krytos** [dipu-bd/lightnovel-crawler#1512]
- Language: English
- Supports Searching: Yes
- Contains Machine Translations: No
- Contains Manga/Manhua/Manhwa: Yes
- Has CloudFlare Protection: Don't think so.

**Comment by idMysteries** [comment]
Copy of lightnovelpub о_О
OK

https://github.com/dipu-bd/lightnovel-crawler/issues/950
