### ISSUE TITLE
https://tamagotl.com/

### ISSUE THREAD

**Issue by graciagraciagracia** [dipu-bd/lightnovel-crawler#1515]
- Language: EN
- Supports Searching: Yes
- Contains Machine Translations: Yes
- Contains Manga/Manhua/Manhwa: No
- Has CloudFlare Protection:

**Comment by graciagraciagracia** [comment]
Hi. How soon will the source be ready for use in LN crawler? Thank you.

**Comment by dipu-bd** [comment]
It should already be available

**Comment by graciagraciagracia** [comment]
Hi. I tried, and here's the result: ![image](https://user-images.githubusercontent.com/84960307/187651726-275b1a59-baeb-45fa-9f53-610d45aa86eb.jpg)

**Comment by dipu-bd** [comment]
The discord bot restart at a specific interval each day. You will get it the next day. But the source is available in terminal app.
