### ISSUE TITLE
https://novelsala.com

### ISSUE THREAD

**Issue by levinuiiy** [dipu-bd/lightnovel-crawler#1520]
Someone did requested, but i found they just put the link
& didn't write other info, so don't know if it was properly done. 

- Language: English
- Supports Searching: Yes
- Contains Machine Translations: Yes & HAS A LOT OF MTL
- Contains Manga/Manhua/Manhwa: No
- Has CloudFlare Protection: i think No

**Comment by idMysteries** [comment]
I'm working on a crawler for this site now. @dipu-bd
