### ISSUE TITLE
Fix this bug: `--range, --index, --chapter` method no longer works

### ISSUE THREAD

**Issue by budikesuma** [dipu-bd/lightnovel-crawler#1521]
@dipu-bd 
Hello dev,

The suppressed method with (--range, --index, --chapter) no longer works.

If I apply any number, for example `--range 1 50`, it does not download chapters 1 to 50, but the whole chapter.

App: Google colab.

Test link:
http://wnmtl.org/book/8510-fenghua-jiujian

**Comment by dipu-bd** [comment]
Please add some logs or screenshot. It is working for me. I can't see the issue if you don't provide any logs.

**Comment by budikesuma** [comment]
> Please add some logs or screenshot. It is working for me. I can't see the issue if you don't provide any logs.

@dipu-bd 

Ok,
I'm currently trying a short chapter novel, containing a total of 80 chapters.
I will take a range of 1-15 chapters.
But it still downloads the whole chapter (80 chapters).

Test link:
https://www.wuxiaworld.com/novel/first-immortal-of-the-sword
.
.
![Screenshot_20220901-154311_Edge](https://user-images.githubusercontent.com/50254552/187873112-d4299eca-7bcb-49a3-bf0a-e08a0c528d2a.jpg)
.
.
![Screenshot_20220901-154345_Edge](https://user-images.githubusercontent.com/50254552/187873128-40f5439d-1f76-465d-9e61-6dc4fe63f5ea.jpg)
