### ISSUE TITLE
https://usefulnovel.com

### ISSUE THREAD

**Issue by levinuiiy** [dipu-bd/lightnovel-crawler#1537]
check & not requested yet

- Language: English
- Supports Searching: Yes
- Contains Machine Translations: Yes
- Contains Manga/Manhua/Manhwa: No
- Has CloudFlare Protection: Not sure, but prob No

**Comment by idMysteries** [comment]
@dipu-bd wtf? Madara.

![изображение](https://user-images.githubusercontent.com/11484976/188264168-4b4999ce-ccf4-43b2-9252-25f22e050e8c.png)

from browser
```
POST /novel/i-have-everything-you-like/ajax/chapters/ HTTP/2
Host: usefulnovel.com
User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:104.0) Gecko/20100101 Firefox/104.0
Accept: */*
Accept-Language: ru-RU,ru;q=0.8,en-US;q=0.5,en;q=0.3
Accept-Encoding: gzip, deflate, br
X-Requested-With: XMLHttpRequest
Origin: https://usefulnovel.com
DNT: 1
Connection: keep-alive
Referer: https://usefulnovel.com/novel/i-have-everything-you-like/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
Content-Length: 0
```

**Comment by dipu-bd** [comment]
@idMysteries I was testing some new things. The post request method was broken in dev. I fixed it.

**Comment by idMysteries** [comment]
@dipu-bd OK
