### ISSUE TITLE
All chapters downloaded even when selecting download remaining chapters only

### ISSUE THREAD

**Issue by gautamz** [dipu-bd/lightnovel-crawler#1543]
Here is the output and selections made -
10 volumes and 5221 chapters found
? Enter output directory: /home//Lightnovels/xxx
? What to do with existing folder? Download remaining chapters only
? Which chapters to download? Everything! (5221 chapters)
? 5221 chapters selected Continue
? Which output formats to create? done (2 selections)
? How many files to generate? Split by volume into multiple files

I already downloaded upto the latest chapters last week. Till last week the app would only download the missing chapters, but now its downloading everything again. 

Has something changed?

**Comment by dipu-bd** [comment]
Yes, a new change has been done in the downloader. A new field "success" is added in the json files. Unless that field is true, the chapter will get downloaded again. I guess you had downloaded chapters from the old version in the folder. According to current change, those chapters will be treated as not downloaded.
