### ISSUE TITLE
2.34.0 Discord Bot not Working

### ISSUE THREAD

**Issue by levinuiiy** [dipu-bd/lightnovel-crawler#1545]
## Describe the bug

Lightnovel Crawler Bot in Discord Version: 2.34.0 
Is not working. 

[
Download failed!
`signal only works in main thread of the main interpreter`
]

It is 2.34.0 problem, since i tried another bot with 2.29.6 & it works, 
& previous version of Lightnovel Crawler Bot Version: 2.33.1 - worked perfectly fine. 

SO PLEASE ROLL BACK THE VERSION OF BOT OR PLEASE FIX IT. 

**App source**: Discord

Lightnovel Crawler Bot in Discord

**App version**:   x.y.z  
Lightnovel Crawler Bot
**Your OS**: 15.6.1 (19G82)

**Comment by jere344** [comment]
I think it was fixed but the bot has not been updated yet

**Comment by budikesuma** [comment]
@levinuiiy 

It was fixed. 
.
![Screenshot_20220906-142846_Discord](https://user-images.githubusercontent.com/50254552/188574689-d2d64c47-b9dd-4cd4-b9af-c1f4d7584dcd.jpg)
![Screenshot_20220906-143331_Discord](https://user-images.githubusercontent.com/50254552/188574703-e653c08e-2ce7-48cf-b629-b9dd6f422b18.jpg)

**Comment by budikesuma** [comment]
@dipu-bd 

The current problem is that sending the prefix `!` is not getting a response from the bot.
.
.
![Screenshot_20220906-151044_Discord](https://user-images.githubusercontent.com/50254552/188582171-87a68469-7308-4fc1-9da8-e5b9d8d8bbb4.jpg)
