### ISSUE TITLE
https://panda-novel.com/

### ISSUE THREAD

**Issue by Sub2Assassin** [dipu-bd/lightnovel-crawler#1548]
Please add this to the programme, it has latest novels which only has less than 50 chps on webnovel too.

- Language: English 
- Supports Searching: Yes
- Contains Machine Translations: No
- Contains Manga/Manhua/Manhwa: Yes
- Has CloudFlare Protection: idk

**Comment by Sub2Assassin** [comment]
Idk about cloudflare protection btw.

**Comment by idMysteries** [comment]
Copy https://github.com/dipu-bd/lightnovel-crawler/issues/1343

**Comment by Sub2Assassin** [comment]
So is it already in process?

**Comment by dipu-bd** [comment]
Duplicate of #1343
