### ISSUE TITLE
Fix this new bug on wattpad.com 

### ISSUE THREAD

**Issue by budikesuma** [dipu-bd/lightnovel-crawler#1551]
@dipu-bd 
Hello dev,

New bugs appeared on wattpad.com, starting from chapter 158 onwards containing empty chapters.

And also can `no longer download images`.

Unexpectedly, the download speed also dropped dramatically compared to a few months back...

`On Google Colab`

Test link:
https://www.wattpad.com/story/246514776-inigualable-ws
.
.
![Screenshot_20220906-140931_MiXplorer](https://user-images.githubusercontent.com/50254552/188571114-e5280aea-0a69-499c-a686-c6cb5fd25a8e.jpg)
![Screenshot_20220906-140948_MiXplorer](https://user-images.githubusercontent.com/50254552/188571121-8a0a9117-b4b5-4aa3-abf8-98b20a40e53f.jpg)
![Screenshot_20220906-134922_Chrome](https://user-images.githubusercontent.com/50254552/188571128-206c27e2-ef1b-4415-b792-d7bfff8d31d8.jpg)
![Screenshot_20220906-134938_Chrome](https://user-images.githubusercontent.com/50254552/188571134-a8a7e66c-018b-42bb-b7d0-aa0b2a9167a5.jpg)
![Screenshot_20220906-135006_Chrome](https://user-images.githubusercontent.com/50254552/188571141-13e78342-efe2-452f-9a05-84bddd9aed10.jpg)

**Comment by dipu-bd** [comment]
should be fixed now

**Comment by budikesuma** [comment]
> should be fixed now


👍👍 Okay, I'm going to test it.
