### ISSUE TITLE
mtlnation.com site authorization error

### ISSUE THREAD

**Issue by LisArits** [dipu-bd/lightnovel-crawler#1552]
Error: Detected a Cloudflare version 2 Captcha challenge, This feature is not available in the opensource (free) version
![Безымянный](https://user-images.githubusercontent.com/113008317/188805835-7548908f-44df-47c6-8116-5386f4cc5ab5.png)

**Comment by idMysteries** [comment]
The site is protected by CloudFlare. There's nothing we can do about it right now.

**Comment by LisArits** [comment]
I see, hmm, my version v2.31.0 seems to bypass the protection and authorize, although some chapters do not download correctly
![Безымянный](https://user-images.githubusercontent.com/113008317/188831997-e5fe346e-e647-4bd4-8f17-03b5106002d3.png)

**Comment by dipu-bd** [comment]
This new version had proxy enabled by default. It will be optional from the next version. And this issue should be fixed.
