### ISSUE TITLE
https://readonlinenovels.com/

### ISSUE THREAD

**Issue by graciagraciagracia** [dipu-bd/lightnovel-crawler#1553]
- Language: EN
- Supports Searching: Yes
- Contains Machine Translations: 
- Contains Manga/Manhua/Manhwa: No
- Has CloudFlare Protection:

**Comment by idMysteries** [comment]
http://readonlinenovels.com/ 
https://github.com/dipu-bd/lightnovel-crawler/blob/851c6a75e52657935de9c91fe52fcc396808693d/sources/en/r/readonlinenovels.py
