### ISSUE TITLE
Browser for crawlers

### ISSUE THREAD

**Issue by dipu-bd** [dipu-bd/lightnovel-crawler#1559]
#1343

**Comment by dipu-bd** [comment]
https://github.com/python-mechanize/mechanize

**Comment by dipu-bd** [comment]
https://github.com/7ws/webkitcrawler

**Comment by dipu-bd** [comment]
https://www.selenium.dev/documentation/webdriver/getting_started/install_drivers/#tabs-2-1

**Comment by dipu-bd** [comment]
https://github.com/ultrafunkamsterdam/undetected-chromedriver

**Comment by dipu-bd** [comment]
https://github.com/brython-dev/brython

**Comment by dipu-bd** [comment]
https://github.com/qutebrowser/qutebrowser

**Comment by idMysteries** [comment]
https://github.com/Hemadou-youcef/LIGHTNOVELS-CRAWLER/blob/3c7f28ede6e69f47b9472ee9f2515575ebbec6a8/modules/wuxia.py

**Comment by idMysteries** [comment]
https://github.com/ryanhutzley/Campaign-Web-Scraper/blob/6adc7fbed487ee967f90963d698002ebfd46f284/tools/setups.py

**Comment by idMysteries** [comment]
Don't forget to detect the captcha and show the captcha window if possible. Or is it not necessary?

**Comment by dipu-bd** [comment]
It is necessary for cloudflare v2 challenge (human captcha verification). I just got the basic interface ready. It will need more time to develop into what we want.

**Comment by idMysteries** [comment]
Can we run javascript in the browser? This can be used for webnovel and qidian to bypass encryption.

**Comment by dipu-bd** [comment]
Yes, we can run javascript, click on elements, submit forms etc.

**Comment by idMysteries** [comment]
Hmmm
https://www.webnovel.com/book/magic-deity-godly-choices_19523622105539105/catalog
===>
wait for ".j_catalog_list" maybe...
===>
volume in ".volume-item"... for a in volume("li > a")....


Ahhh so hard

**Comment by dipu-bd** [comment]
@idMysteries Do not work on this yet. I need a few more days to make the browser is ready

**Comment by dipu-bd** [comment]
The templates for scraping with browser is ready. Have not got the chance to test them yet. For usage and info check these examples:

https://github.com/dipu-bd/lightnovel-crawler/tree/dev/sources/_examples

I will play with these for the next week to fix possible issues and improve the interface.

**Comment by dipu-bd** [comment]
Example crawler:

https://github.com/dipu-bd/lightnovel-crawler/blob/dev/sources/en/w/webnovel.py
