### ISSUE TITLE
Fix this source: www.wuxiaworld.com not working. 

### ISSUE THREAD

**Issue by budikesuma** [dipu-bd/lightnovel-crawler#1579]
@dipu-bd 
Hello, dev,

I don't know what happened to the www.wuxiaworld.com website, but at the moment lncrawler can't find the novel chapters.
   It seems can't reach the address: https://api.wuxiaworld.com/wuxiaworld.api.v2.Novels/GetNovel

I tried termux, discord bot, and Google Colab, but all of them didn't work.

Test link: https://www.wuxiaworld.com/novel/first-immortal-of-the-sword
.
.
![Screenshot_20220915-172352_Termux](https://user-images.githubusercontent.com/50254552/190382238-6a85515a-76d4-4671-8f5d-6f6a8bd468d3.jpg)
.
![Screenshot_20220915-172944_Chrome](https://user-images.githubusercontent.com/50254552/190382394-1bde308d-c2c7-46e3-bd0f-b6f0a4e346fb.jpg)
.
![Screenshot_20220915-173004_Chrome](https://user-images.githubusercontent.com/50254552/190382458-d7631263-002e-45a7-b867-af20f0bc7453.jpg)
![Screenshot_20220915-173016_Chrome](https://user-images.githubusercontent.com/50254552/190382495-ec789b54-1578-4c71-88e5-45f1e4f42dad.jpg)

**Comment by dipu-bd** [comment]
@idMysteries #1580 does not solve this issue. This is maybe a cloudflare issue

**Comment by idMysteries** [comment]
When I checked, the error was in the api url. Changing the api to api2.
But if it doesn't work now, then apparently it's cloudflare. Damn, I'm starting to hate cloudflare.

**Comment by idMysteries** [comment]
I think it's not cloudflare. @dipu-bd 
They don't have cookies in the request.
![изображение](https://user-images.githubusercontent.com/11484976/190482816-88de8a74-b420-4f38-8e50-745dbeaf288e.png)

**Comment by dipu-bd** [comment]
> Damn, I'm starting to hate cloudflare

welcome to the club

**Comment by idMysteries** [comment]
I sent the request again in the browser and it was not blocked.

**Comment by dipu-bd** [comment]
> I sent the request again in the browser and it was not blocked.

This is gonna be difficult to find

**Comment by idMysteries** [comment]
But the program doesn't work for some reason. Maybe a request with an error inside?  I'm 70% sure it's not cloudflare.

**Comment by idMysteries** [comment]
```
POST /wuxiaworld.api.v2.Novels/GetNovel HTTP/2
Host: api2.wuxiaworld.com
User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:104.0) Gecko/20100101 Firefox/104.0
Accept: */*
Accept-Language: ru-RU,ru;q=0.8,en-US;q=0.5,en;q=0.3
Accept-Encoding: gzip, deflate, br
Referer: https://www.wuxiaworld.com/novel/the-max-level-hero-strikes-back
Content-Length: 38
Origin: https://www.wuxiaworld.com
DNT: 1
Connection: keep-alive
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: no-cors
Sec-Fetch-Site: same-site
TE: trailers
authorization: Bearer 1FB7C5BC5F3369F06062EDB20E25C8884E1E07A1E7DFD727F4D873C666FF4E07-1
content-type: application/grpc-web+proto
x-grpc-web: 1
Pragma: no-cache
Cache-Control: no-cache
```

**Comment by idMysteries** [comment]
![изображение](https://user-images.githubusercontent.com/11484976/190485214-bd32578b-0512-44bf-abd4-df59e59474a9.png)
@dipu-bd maybe wrong slug?

**Comment by idMysteries** [comment]
``` py
        slug = re.findall(r'/novel/([^/]+)', self.novel_url)[0]
```

**Comment by idMysteries** [comment]
Okay, I'm too dumb for that.
Maybe they have learned to find not real queries, or it's some kind of deception in the browser. Maybe there are some secret cookies. I can easily send requests in the browser. The browser shows that there are no cookies.

Perhaps the people from wuxiaworld are dozens of times smarter than me.

**Comment by idMysteries** [comment]
@dipu-bd But are they using a certificate from cloudflare?

![изображение](https://user-images.githubusercontent.com/11484976/190493002-b1dc8032-aa5c-4de0-9ed7-5d0289afee28.png)

**Comment by idMysteries** [comment]
I tried to fix it, but now I'm 90% sure it's cloudflare. T_T

**Comment by budikesuma** [comment]
@dipu-bd 

I just used Google colab by forcing an install of lncrawler version 2.29.4, still managed to download the early chapters, although the last few chapters ended up empty.
Maybe you need to check your old version files there?
.
Tested link: https://www.wuxiaworld.com/novel/law-of-space-and-time
.
.
![Screenshot_20220916-062311_Chrome](https://user-images.githubusercontent.com/50254552/190526175-d341c655-b833-4703-9c7d-65b91e72bec0.jpg)

![Screenshot_20220916-062337_Chrome](https://user-images.githubusercontent.com/50254552/190526203-cfb5ceeb-37af-4262-ad48-ab4fd97e7f7a.jpg)
.
![Screenshot_20220916-062404_Chrome](https://user-images.githubusercontent.com/50254552/190526251-20d0be60-afe6-4162-b60a-4cd586b86046.jpg)

![Screenshot_20220916-062426_Chrome](https://user-images.githubusercontent.com/50254552/190526281-50e6973c-9299-4922-b9bb-7dff6fecf2eb.jpg)

**Comment by idMysteries** [comment]
@dipu-bd what is this dark magic? Is the problem in the proto file (string)? I copied the code from version 2.29.4 and there is nothing interesting.

I'm not good at python's dark magic.

**Comment by budikesuma** [comment]
@idMysteries 

Maybe it's not a problem at `wuxiacom.py`, maybe the problem is in the `downloader.py` section? 🤔

**Comment by zerty** [comment]
Ive got kind of an ugly solution idk if it can help:
https://github.com/zerty/Wuxiaworld-to-epub
Basically I use undetected-chromedriver and run JS in it to get the data using a POST

**Comment by budikesuma** [comment]
@dipu-bd 
@idMysteries 

This article might be useful for this issue?

https://www.scrapingbee.com/blog/pyppeteer/

**Comment by ShakeBake** [comment]
Same issue for me on windows and termux.

**Comment by budikesuma** [comment]
I finally managed to get version 2.29.4 working on pyDroid3, to be able to scrape wuxiaworld.com again.

I suggest developers take another look at the code in that version, to re-implement it to be able to crawl wuxiaworld.com.

**Comment by avggeek** [comment]
I just upgraded to `3.0.1` and tried to download a wuxiaworld novel ([this one](https://www.wuxiaworld.com/novel/overgeared)) using the following command:

~~~
lncrawl --login Bearer ey.. -s https://www.wuxiaworld.com/novel/overgeared --format epub --filename "Overgeared - rainbowturtle" --filename-only --output . --single
~~~

The download errors out with the following message:

~~~
Failed to get chapter: Message: no such element: Unable to locate element: {"method":"css selector","selector":".chapter-content"}
  (Session info: headless chrome=106.0.5249.103)
Stacktrace:
#0 0x56271decf2c3 <unknown>
#1 0x56271dcd883a <unknown>
#2 0x56271dd11985 <unknown>
#3 0x56271dd11b61 <unknown>
#4 0x56271dd49d14 <unknown>
#5 0x56271dd2ff6d <unknown>
#6 0x56271dd47a50 <unknown>
#7 0x56271dd2fd63 <unknown>
#8 0x56271dd047e3 <unknown>
#9 0x56271dd05a21 <unknown>
#10 0x56271df1d18e <unknown>
#11 0x56271df20622 <unknown>
#12 0x56271df03aae <unknown>
#13 0x56271df212a3 <unknown>
#14 0x56271def7ecf <unknown>
#15 0x56271df41588 <unknown>
#16 0x56271df41706 <unknown>
#17 0x56271df5b8b2 <unknown>
#18 0x7f9da4bc5ea7 <unknown>

Chapters:   0%|                           | 2/1705 [01:38<19:20:13, 40.88s/item]Failed to get chapter: Message: no such element: Unable to locate element: {"method":"css selector","selector":".chapter-content"}
  (Session info: headless chrome=106.0.5249.103)
Stacktrace:
#0 0x56271decf2c3 <unknown>
#1 0x56271dcd883a <unknown>
#2 0x56271dd11985 <unknown>
#3 0x56271dd11b61 <unknown>
#4 0x56271dd49d14 <unknown>
#5 0x56271dd2ff6d <unknown>
#6 0x56271dd47a50 <unknown>
#7 0x56271dd2fd63 <unknown>
#8 0x56271dd047e3 <unknown>
#9 0x56271dd05a21 <unknown>
#10 0x56271df1d18e <unknown>
#11 0x56271df20622 <unknown>
#12 0x56271df03aae <unknown>
#13 0x56271df212a3 <unknown>
#14 0x56271def7ecf <unknown>
#15 0x56271df41588 <unknown>
#16 0x56271df41706 <unknown>
#17 0x56271df5b8b2 <unknown>
#18 0x7f9da4bc5ea7 <unknown>

Chapters:   0%|                           | 3/1705 [03:09<30:13:48, 63.94s/item]Chapters:   0%|                           | 3/1705 [04:21<41:10:25, 87.09s/item]
Traceback (most recent call last):
  File "/home/avggeek/.local/bin/lncrawl", line 8, in <module>
    sys.exit(main())
  File "/home/avggeek/.local/lib/python3.9/site-packages/lncrawl/__init__.py", line 14, in main
    start_app()
  File "/home/avggeek/.local/lib/python3.9/site-packages/lncrawl/core/__init__.py", line 68, in start_app
    run_bot(bot)
  File "/home/avggeek/.local/lib/python3.9/site-packages/lncrawl/bots/__init__.py", line 16, in run_bot
    ConsoleBot().start()
  File "/home/avggeek/.local/lib/python3.9/site-packages/lncrawl/bots/console/integration.py", line 92, in start
    self.app.start_download()
  File "/home/avggeek/.local/lib/python3.9/site-packages/lncrawl/core/app.py", line 155, in start_download
    fetch_chapter_body(self)
  File "/home/avggeek/.local/lib/python3.9/site-packages/lncrawl/core/downloader.py", line 88, in fetch_chapter_body
    for progress in app.crawler.download_chapters(app.chapters):
  File "/home/avggeek/.local/lib/python3.9/site-packages/lncrawl/templates/browser/basic.py", line 111, in download_chapters
    chapter.body = self.download_chapter_body_in_browser(chapter)
  File "/home/avggeek/.lncrawl/sources/en/w/wuxiacom.py", line 221, in download_chapter_body_in_browser
    content = self.browser.find("chapter-content", By.CLASS_NAME).as_tag()
  File "/home/avggeek/.local/lib/python3.9/site-packages/lncrawl/core/browser.py", line 162, in find
    return self._driver.find_element(by, selector)
  File "/home/avggeek/.local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 856, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/home/avggeek/.local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 427, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/home/avggeek/.local/lib/python3.9/site-packages/selenium/webdriver/remote/remote_connection.py", line 344, in execute
    return self._request(command_info[0], url, body=data)
  File "/home/avggeek/.local/lib/python3.9/site-packages/selenium/webdriver/remote/remote_connection.py", line 366, in _request
    response = self._conn.request(method, url, body=body, headers=headers)
  File "/usr/lib/python3/dist-packages/urllib3/request.py", line 78, in request
    return self.request_encode_body(
  File "/usr/lib/python3/dist-packages/urllib3/request.py", line 170, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/usr/lib/python3/dist-packages/urllib3/poolmanager.py", line 375, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.9/http/client.py", line 1347, in getresponse
    response.begin()
  File "/usr/lib/python3.9/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.9/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
~~~
