### ISSUE TITLE
https://mangabuddy.com/

### ISSUE THREAD

**Issue by SirGryphin** [dipu-bd/lightnovel-crawler#1597]
- Language: English
- Supports Searching: Yes
- Contains Machine Translations: No
- Contains Manga/Manhua/Manhwa: Yes
- Has CloudFlare Protection: Unsure

**Comment by idMysteries** [comment]
Are you going to write the code for this site or should I write it?

**Comment by idMysteries** [comment]
I will take up this issue. If I can't do it, I'll write to you. OK?

**Comment by SirGryphin** [comment]
That's fine thank you.

**Comment by idMysteries** [comment]
@SirGryphin Mobilization in Russia... eh... I hope I will finish this issue before they send me to die in the war.

**Comment by dipu-bd** [comment]
> Mobilization in Russia... eh... I hope I will finish this issue before they send me to die in the war.

@idMysteries Wow! I heard from some of my Russian friends, people are leaving Russia anyhow. Air ticket price reaching $10,000! Since it's a big country, even by road it takes 4-10 days to get out of there. It's crazy... Hope you stay safe!

**Comment by yudilee** [comment]
> @SirGryphin Mobilization in Russia... eh... I hope I will finish this issue before they send me to die in the war.

Wish you all the best. Stay safe

**Comment by yudilee** [comment]
> @SirGryphin Mobilization in Russia... eh... I hope I will finish this issue before they send me to die in the war.

Wish you all the best. Stay Safe

**Comment by idMysteries** [comment]
@dipu-bd closed
