### ISSUE TITLE
https://bato.to/

### ISSUE THREAD

**Issue by SirGryphin** [dipu-bd/lightnovel-crawler#1601]
- Language: English
- Supports Searching: Yes
- Contains Machine Translations: No
- Contains Manga/Manhua/Manhwa: Yes
- Has CloudFlare Protection: Unknown

Would really like this site, I've tried making it myself but something in the chapter body is blocking the scrape and I don't have free time to figure it out.

Note: This site also has many many domains as well, if you do get it working you might want to these to base url list.

```
https://battwo.com/
https://mto.to/
https://mangatoto.net/
https://dto.to/
https://batocc.com/
https://batotoo.com/
https://wto.to/
https://mangatoto.com/
https://comiko.net/
https://batotwo.com/
https://mangatoto.org/
https://hto.to/
https://mangatoto.net/
```

**Comment by idMysteries** [comment]
![изображение](https://user-images.githubusercontent.com/11484976/191697185-98ef2472-c4fa-4046-8895-5b088c8d84d0.png)

Easy for Russian hacker :smile_cat:
I will try to do it, but without guarantees.

**Comment by SirGryphin** [comment]
@idMysteries thanks for making this so quickly. Just testing it now. Saves me using another manga downloader then converting images to epub.

**Comment by idMysteries** [comment]
Perhaps it is necessary to implement a search function.

**Comment by idMysteries** [comment]
> Update: only problem now is the epub is 750mb lol.

Maybe we need to convert to another format

**Comment by idMysteries** [comment]
But no. It already converts to jpeg

**Comment by idMysteries** [comment]
The file size does not seem to be able to be reduced. T_T

**Comment by idMysteries** [comment]
@SirGryphin search is ready

**Comment by idMysteries** [comment]
> thanks for making this so quickly.

I was just curious about how encryption was done here. :smiley_cat: 

As a result, I wrote such a terrible code:
``` py
def decode_pass(code):
    code = code.replace('!+[]', '1').replace('!![]', '1').replace('[]', '0')
    code = code.lstrip('+').replace('(+', '(').replace(' ', '')
    code = code.replace('+((1+[+1]+(1+0)[1+1+1]+[1+1]+[+0])+0)[+1]+', '.')
    code = code.replace(']+[', ' ').replace('[', '').replace(']', '')

    res = ''
    for num_part in code.split('.'):
        for num in num_part.split():
            res += str(num.count('1'))
        res += '.'

    return res.strip('.')
```

**Comment by SirGryphin** [comment]
as long as it works, terrible codes okay lol. The manga I download is like 200 chapters 2000+ images.

**Comment by idMysteries** [comment]
I have a lot of work now, I will have to pay less attention to this project. If there is no work today, I will make another crawler for website with manga (your prev issue).

**Comment by SirGryphin** [comment]
@idMysteries no worries, thanks for all the work anyway.

**Comment by dipu-bd** [comment]
@idMysteries Thanks for the contributions
