### ISSUE TITLE
New volumes and madara

### ISSUE THREAD

**Issue by idMysteries** [dipu-bd/lightnovel-crawler#1613]
https://bestmanga.club/manga/utakata_dialog_o_tom_o_sem/

``` json
"volumes": [
    {
      "id": 1,
      "title": "Volume 1",
      "start_chapter": 18,
      "final_chapter": 0,
      "chapter_count": 18
    }
  ],
```
https://github.com/dipu-bd/lightnovel-crawler/blob/d2c1519cd3040eab677ce7c2fa6b3978cdc563e4/lncrawl/core/novel_info.py#L16
![изображение](https://user-images.githubusercontent.com/11484976/192094501-4bf90fbb-fa2a-4548-9b74-527a19addf8e.png)

Madara extra text
![изображение](https://user-images.githubusercontent.com/11484976/192094568-b8abe713-9647-4b37-baef-86c552a1ed50.png)

**Comment by idMysteries** [comment]
https://github.com/dipu-bd/lightnovel-crawler/pull/1615 
``` py
    def read_novel_info(self) -> None:
        soup = self.get_soup(self.novel_url)
        self.parse_title(soup)
        self.parse_image(soup)
        self.parse_authors(soup)
        self.parse_chapter_list(soup) <----------------------------- Maybe we should check here whether the number of chapters is equal to zero?
        self.parse_chapter_list(self.get_chapter_list_soup(soup)) <--
```

**Comment by dipu-bd** [comment]
Fixed the issue

**Comment by idMysteries** [comment]
Volumes start_chapter and "a" tag with javascript href fixes needed

**Comment by dipu-bd** [comment]
Volumes `start_chapter` is being modified later inside the next function, There is nothing to fix.

Fixed `<a>` tag with javascript href issue

**Comment by idMysteries** [comment]
> Volumes start_chapter is being modified later inside the next function, There is nothing to fix.
```
"volumes": [
    {
      "id": 1,
      "title": "Volume 1",
      "start_chapter": 18,
      "final_chapter": 0,
      "chapter_count": 18
    }
  ],
```

**Comment by dipu-bd** [comment]
This was the issue:
```
        volume["start_chapter"] = max(volume["start_chapter"], item["id"])
        volume["final_chapter"] = min(volume["final_chapter"], item["id"])
```

The min, max methods were in wrong places. I must have been drunk while editing this section 😵
