### ISSUE TITLE
Not producing PDF files

### ISSUE THREAD

**Issue by Vantageright** [dipu-bd/lightnovel-crawler#163]
After downloading the light novel no pdf files are in the folder, the window shows it fails to add any of them before the task is complete. Everything else is produced without issue.

**Let us know**
- Novel URL: https://novelplanet.com/Novel/Saikyou-Juzoku-Tensei-Cheat-Majutsushi-no-Slow-Life
- App Version: 2.10.1
- Package: pip
- OS: W7

**Comment by dipu-bd** [comment]
You need to have GTK3 Runtime to generate PDF. Download link:

https://github.com/tschoonj/GTK-for-Windows-Runtime-Environment-Installer/releases/download/2019-07-02/gtk3-runtime-3.24.9-2019-07-02-ts-win64.exe
