### ISSUE TITLE
Failure to extract all chapters

### ISSUE THREAD

**Issue by graciagraciagracia** [dipu-bd/lightnovel-crawler#1635]
## Let us know

**Novel URL**:     <your novel url or query> https://puretl.com/baifumei-in-the-70s
**App Location**:    PIP | EXE | Discord | Telegram  Discord
**App Version**:   x.y.z   Lightnovel Crawler

## Describe this issue

 Cannot extract all chapters; chapters extracted are in reverse

 
![1](https://user-images.githubusercontent.com/84960307/192178374-c492add8-5ba3-4ea4-ae40-947c8ecb34d2.jpg)

**Comment by idMysteries** [comment]
Ohh I understand

**Comment by budikesuma** [comment]
@idMysteries 

Somehow it doesn't work on this novel, but it works on other novels on the same site.
Can you check again?

Novel link:
https://puretl.com/assassin-farmer
.
.
![Screenshot_20220930-235132_Discord~2](https://user-images.githubusercontent.com/50254552/193320153-2edaf53e-f091-4d12-bf60-cbb051f82f05.jpg)

**Comment by idMysteries** [comment]
Crawler is now broken for me too... haha
![image](https://user-images.githubusercontent.com/11484976/193321251-ba1271d4-2249-474f-9965-72288b5a5498.png)

**Comment by idMysteries** [comment]
@budikesuma I think @dipu-bd was drunk again...

**Comment by idMysteries** [comment]
@dipu-bd failed to get cover again... https://github.com/dipu-bd/lightnovel-crawler/pull/1662
http://static1.squarespace.com/static/61d631c6bb5b2a1ff76d5426/t/62253455e3cd1828c1d8bb25/1646605397532/unsplash-image-rdVLN3UFmpU.jpg?format=1500w
