### ISSUE TITLE
Cannot generate complete chapters from the source

### ISSUE THREAD

**Issue by dietmilk33** [dipu-bd/lightnovel-crawler#164]
I tried to generate epub in telegram, but BOT unable to detect complete chapters from the source (1000+ chapters). Bot only detected 2 first volume (150 chapters). 

I will appreciate if you can fix this issue. Thank you.

Here is the source:
https://novelraw.blogspot.com/2019/02/a-wizards-secret-mtl.html?m=1

**Comment by dipu-bd** [comment]
`novelraw` limited their api to send only 150 chapters. will fix it in the next update

**Comment by dipu-bd** [comment]
fixed. wait for new release
