### ISSUE TITLE
[template] WordPress MangaStream (WP MangaStream)

### ISSUE THREAD

**Issue by idMysteries** [dipu-bd/lightnovel-crawler#1644]
https://github.com/dipu-bd/lightnovel-crawler/issues/1643

eplister (eplisterfull)
![image](https://user-images.githubusercontent.com/11484976/192339058-8ef7623a-48ad-4103-8be3-490e9e5cab4d.png)
https://themesia.com/mangastream-wordpress-theme/

Our crawlers:
https://github.com/dipu-bd/lightnovel-crawler/blob/2d631a85cd214775b629f8864e3469996afb8efa/sources/en/n/novelsemperor.py
https://github.com/dipu-bd/lightnovel-crawler/blob/f772831b61192828184ec692d50d45a774e57d08/sources/en/t/tamagotl.py
https://github.com/dipu-bd/lightnovel-crawler/blob/b40a99846a6af0666cb81d8aa1af1567de2a7425/sources/en/m/mltnovels.py
https://github.com/dipu-bd/lightnovel-crawler/blob/b30a47fd2832f618c462274e302663124c4c23cc/sources/pt/centralnovel.py

**Comment by idMysteries** [comment]
Realization on js:
https://github.com/manga-download/hakuneko/blob/master/src/web/mjs/connectors/templates/WordPressMangastream.mjs

**Comment by idMysteries** [comment]
https://github.com/manga-download/hakuneko/blob/master/src/web/mjs/connectors/templates/WordPressMangastream.mjs

this.queryChapters = 'div#chapterlist ul li div.eph-num a';

https://github.com/manga-download/haruneko/blob/322a1b4c71925649b4aa8bce6656e66ea96be031/src/engine/websites/KolNovel.ts

@MangaStream.MangasSinglePageCSS('div#content div.soralist ul li a.series', '/series/list-mode/')
@MangaStream.ChaptersSinglePageCSS('div.eplister ul li a', 'div:not(.epl-date)')

**Comment by idMysteries** [comment]
https://imperfectcomic.org/manga/it-starts-with-a-kingpin-account/
div#chapterlist ul li div.eph-num a

**Comment by idMysteries** [comment]
There is no WP MangaStream code on github. Maybe I'll find it on the Internet to find out what principle it works on.
Why do some use eplister and others use chapterlist

**Comment by idMysteries** [comment]
OK. I found MangaStream 1.1.3

**Comment by idMysteries** [comment]
Hmmm...
<url>/series/<slug> -> eplisterfull
<url>/manga/<slup> -> div#chapterlist ul li div.eph-num a

**Comment by idMysteries** [comment]
https://github.com/dipu-bd/lightnovel-crawler/issues/659

**Comment by idMysteries** [comment]
https://github.com/dipu-bd/lightnovel-crawler/issues/1539

**Comment by dipu-bd** [comment]
After changes in #501, now we can test a novel url against templates. Having more templates will be very useful.

**Comment by idMysteries** [comment]
Can this test be run in github actions?

**Comment by dipu-bd** [comment]
Since you have already done some research on this template, can you make a PR creating one?

**Comment by idMysteries** [comment]
OK... I'll try

**Comment by idMysteries** [comment]
@dipu-bd I have a question about the Chapter id. Should it be an order from 1 to N or can it be a random order, for example from 342 to 101. Will the result then be sorted by id?
![image](https://user-images.githubusercontent.com/11484976/193628689-9e866003-8ca5-4104-8231-45e6896fd286.png)
![image](https://user-images.githubusercontent.com/11484976/193628900-f18cb78d-11fa-4d4b-bd78-7e1473c5bf1d.png)
![image](https://user-images.githubusercontent.com/11484976/193629188-727935c7-feff-406f-96ae-abb60e9b3b36.png)


I noticed that some chapters are sorted in descending order and some in ascending order. And they have an id that seems to be correct.

**Comment by idMysteries** [comment]
Or should I just write a small order detector? Like... "if next_id > prev_id then reverse else no"

**Comment by dipu-bd** [comment]
Chapters will not be sorted. Please assign 1 to N for now. I will add some logic for checking it later

**Comment by idMysteries** [comment]
https://github.com/dipu-bd/lightnovel-crawler/issues/1687

**Comment by dipu-bd** [comment]
@idMysteries Are you working on this eplister template?

**Comment by idMysteries** [comment]
> @idMysteries Are you working on this eplister template?

Yes, I haven't had time in the last couple of days. But now I will do it according to the new templates.
