### ISSUE TITLE
Cleaner blacklist_patterns

### ISSUE THREAD

**Issue by idMysteries** [dipu-bd/lightnovel-crawler#1646]
```
self.cleaner.blacklist_patterns.update([
            "Prev", "ToC", "Next"
        ])
```

do I understand correctly that if there is a "Next" in the text, then it will delete this text? It's a terrible thing.

**Comment by idMysteries** [comment]
``` <p>Next</p>```

**Comment by dipu-bd** [comment]
You can pass `regex` there to be safe. But more things you pass, slower your crawler will be.

**Comment by idMysteries** [comment]
![изображение](https://user-images.githubusercontent.com/11484976/192601425-5516c174-9e40-411c-94c4-0ace1200134f.png)

**Comment by dipu-bd** [comment]
If the pattern contains in a paragraph, the entire paragraph will be discarded.

**Comment by idMysteries** [comment]
``` py
nav_tags = contents.find_all("a", string="Table of Contents")
        for nav in nav_tags:
            nav.parent.extract()
```

Is it better???

**Comment by idMysteries** [comment]
![изображение](https://user-images.githubusercontent.com/11484976/192601683-d005e6b5-61d6-4ea2-81a1-aef7e345d66e.png)

**Comment by dipu-bd** [comment]
Yes, It looks better.

**Comment by idMysteries** [comment]
I mean there are a lot of places with blacklist_patterns in the code right now

**Comment by dipu-bd** [comment]
Sometimes, when texts are separated by `<br>` tags, you can not select elements like that. That is what made me introduce blacklist_patters.

**Comment by dipu-bd** [comment]
```
 return "\n".join(
            [
                "<p>" + x + "</p>"
                for x in body.split(LINE_SEP)
                if not self.is_in_blacklist(x.strip())
            ]
        )
```

Check this part. Only here the blacklist_pattern is applied. When making a paragraph, it is checking if a bad text exists in a paragraph, and skips it.

**Comment by dipu-bd** [comment]
The paragraph extraction work like this: The `p_block_tags` are considered as a like-break. and `plain_text_tags` are considered as a part of same paragraph. I split paragraph by `p_block_tags` , and join lines together to make a single paragraph when I find `plain_text_tags`

**Comment by idMysteries** [comment]
![изображение](https://user-images.githubusercontent.com/11484976/192602796-1acc4bf2-1af1-4fd0-816d-a8e9ffcef68d.png)
So...

**Comment by dipu-bd** [comment]
Yeah, it will delete paragraphs with any of these texts. As far as we checked, these texts does not appear in the content body. If by any chance they appear in a paragraph, that will get deleted.

**Comment by idMysteries** [comment]
``` py
    def download_chapter_body(self, chapter):
        soup = self.get_soup(chapter["url"])
        contents = soup.select_one(".entry-content")
        
        nav_tags = contents.find_all("a", string="Table of Contents")
        for nav in nav_tags:
            nav.parent.extract()

        self.cleaner.clean_contents(contents)
        
        return str(contents)
```
Is it OK?

**Comment by idMysteries** [comment]
It seemed more logical to me to make not only deletion by text, but also by tag along with the text.

**Comment by dipu-bd** [comment]
Yes, it is okay. You can go with it.


> It seemed more logical to me to make not only deletion by text, but also by tag along with the text.

what if the text is not wrapped by a tag. many sources has unwanted text like that

**Comment by idMysteries** [comment]
> what if the text is not wrapped by a tag. many sources has unwanted text like that

blacklist_patterns :)

**Comment by idMysteries** [comment]
blacklist_patterns for text
and blacklist_tag_patterns.update([["a", "Next"]])

**Comment by idMysteries** [comment]
find(blacklist_tag_patterns[0][0], string=re.compile(blacklist_tag_patterns[0][1]))

**Comment by idMysteries** [comment]
can use tuple? ('a', 'Next')

**Comment by idMysteries** [comment]
In general, I just realized that someone, like me, can write a bad blacklist_patterns
And then that someone will wonder why the paragraph is missing.

**Comment by idMysteries** [comment]
I'm sorry, I demand a lot from you. Even I got a little nervous. :disappointed:

**Comment by dipu-bd** [comment]
It is a good idea. I will change the cleaner.

**Comment by dipu-bd** [comment]
> In general, I just realized that someone, like me, can write a bad blacklist_patterns And then that someone will wonder why the paragraph is missing.

blacklist_patterns are dangerous. I review all the code deeply that are using them. The optimal behavior is maybe to only remove the texts matching these patterns

**Comment by dipu-bd** [comment]
> I'm sorry, I demand a lot from you. Even I got a little nervous. 😞

Hey, that's okay. If we don't share and discuss our ideas, learning and progress won't happen.

**Comment by dipu-bd** [comment]
I did some changes to blacklist_pattern behavior. I do not know how it will fare before testing. 

https://github.com/dipu-bd/lightnovel-crawler/commit/a99680bc3d7f9b9f9e12bc8b660bd330ab6f5b77

**Comment by idMysteries** [comment]
Does it will make empty links?
```<a...>Next</a>``` -> `<a...></a>```?

**Comment by idMysteries** [comment]
![изображение](https://user-images.githubusercontent.com/11484976/192619259-30459935-7fa7-4ad2-a757-91174302c274.png)
Yes... I think it will work incorrectly.
^Translator:.*$

**Comment by idMysteries** [comment]
You forgot to delete "#end if, #end for, etc." :smile:

**Comment by dipu-bd** [comment]
> Does it will make empty links? `<a...>Next</a>` -> `<a...></a>`?

Yes, it can make empty link.

**Comment by dipu-bd** [comment]
> ![изображение](https://user-images.githubusercontent.com/11484976/192619259-30459935-7fa7-4ad2-a757-91174302c274.png) Yes... I think it will work incorrectly. ^Translator:.*$

I plan to revise all the sources that uses this `bad_text_regex`

**Comment by dipu-bd** [comment]
https://github.com/dipu-bd/lightnovel-crawler/commit/617dac993466cefa4d087576269b2be92f484c16

I think it should remove empty tags now. Need to test.

**Comment by idMysteries** [comment]
Alas, even so, I don't trust this method to remove navigation buttons. He can remove the text from the paragraph from the word "Next". And it is desirable for me to know clearly that I am deleting the link.

I don't want to leave it to chance. Although the chance of such a paragraph is very small.

**Comment by idMysteries** [comment]
```
<p>Bla bla bla... bla bla</p>
<p>Next</p>
<p>Bla bla bla... bla bla</p>
```
|>
```
<p>Bla bla bla... bla bla</p>
<p>Bla bla bla... bla bla</p>
```

The probability of this is small, but not zero.

**Comment by idMysteries** [comment]
Maybe I'm being paranoid.

**Comment by dipu-bd** [comment]
Yes, you are right. The tag based text cleaner should be added.

**Comment by idMysteries** [comment]
Deleting tags with text is the right way.
As a result, there were 2 methods. Deleting only text, or a tag with text. You're a genius))

**Comment by idMysteries** [comment]
And you decided to delete the whole paragraph with the text anyway...

**Comment by idMysteries** [comment]
![изображение](https://user-images.githubusercontent.com/11484976/192637126-9c91fb27-c834-4c1b-ace4-06b8081117c2.png)
https://github.com/dipu-bd/lightnovel-crawler/blob/c2d113aac647f9af37f2b414405284b0676c1675/sources/zh/uukanshu.py#L97

**Comment by dipu-bd** [comment]
> I liked the idea of deleting only part of the paragraph better.

It will break existing crawlers.

**Comment by idMysteries** [comment]
If we need to delete the entire paragraph, then we can use deletion with the "p" tag. Else delete only part of the paragraph.

**Comment by idMysteries** [comment]
> It will break existing crawlers.

You can use a temporary fix. Replace the deletion in all scanners with the deletion of the p tag

**Comment by idMysteries** [comment]
> > ![изображение](https://user-images.githubusercontent.com/11484976/192619259-30459935-7fa7-4ad2-a757-91174302c274.png) Yes... I think it will work incorrectly. ^Translator:.*$
> 
> I plan to revise all the sources that uses this `bad_text_regex`

**Comment by dipu-bd** [comment]
From now on let's use `bad_tag_text_pairs`. After cleaning all `bad_text_regex`, we can remove the logic.

**Comment by idMysteries** [comment]
Ahahahaha I saw heart

**Comment by dipu-bd** [comment]
let's keep this ticket open untill all bad_text_regex has been cleaned up. 

good night.

**Comment by idMysteries** [comment]
> From now on let's use `bad_tag_text_pairs`. After cleaning all `bad_text_regex`, we can remove the logic.

Don't remove! The logic of deleting a part of a paragraph will be useful for such cases. And there are quite a lot of them actually. Many sites insert ads inside the paragraph.
![изображение](https://user-images.githubusercontent.com/11484976/192637126-9c91fb27-c834-4c1b-ace4-06b8081117c2.png)

**Comment by idMysteries** [comment]
vtf? Why is bad_tag_text_pairs a dict???

**Comment by dipu-bd** [comment]
I won't remove the logic, just the usage of it. Upon checking the existing sources, I saw there are too many places it has been misused. I will fix those.

**Comment by idMysteries** [comment]
``` py
        self.cleaner.bad_text_regex.update(
            {
                'a': r"""(PREVIOUS CHAPTER)
                |(CHAPTER LIST)
                |(NEXT CHAPTER)""",
                'p': r"""(FOLLOW / LIKE / SUBSCRIBE)
                |(FOLLOW AND LIKE THIS BLOG)
                |(SUBSCRIBE and LIKE)
                |(SUBSCRIBE AND LIKE)
                |(Please donate any amount to support our group!)
                |(Please donate to support our group!)"""
            }
        )
```

![image](https://user-images.githubusercontent.com/11484976/192833824-3461e9ec-bfca-4ba3-b0db-4d7ab197fcf3.png)
https://ancientheartloss.wordpress.com/i-am-my-wife-chapters/chapter-1-turbulent-hours/

**Comment by idMysteries** [comment]
Oh no... hmmm invalid syntax

**Comment by idMysteries** [comment]
DICT IS TOO HARD!!!!! :sob:

**Comment by dipu-bd** [comment]
```
self.cleaner.bad_text_regex.update(
            {
                'a': r"(PREVIOUS CHAPTER)|(CHAPTER LIST)|(NEXT CHAPTER)",
                'p': r"(FOLLOW / LIKE / SUBSCRIBE)|(FOLLOW AND LIKE THIS BLOG)" 
                      +"|(SUBSCRIBE and LIKE)|(SUBSCRIBE AND LIKE)|(Please donate any "
                      +"amount to support our group!)|(Please donate to support our group!)",
            }
        )
```

**Comment by idMysteries** [comment]
Oh wait... I'm stupid

**Comment by idMysteries** [comment]
bad_tag_text_pairs

**Comment by idMysteries** [comment]
``` py
self.cleaner.bad_tag_text_pairs.update(
            {
                "a": r"""(PREVIOUS CHAPTER)
                |(CHAPTER LIST)
                |(NEXT CHAPTER)""",
                "p": r"""(FOLLOW / LIKE / SUBSCRIBE)
                |(FOLLOW AND LIKE THIS BLOG)
                |(SUBSCRIBE and LIKE)
                |(SUBSCRIBE AND LIKE)
                |(Please donate any amount to support our group!)
                |(Please donate to support our group!)""",
            }
        )

```

**Comment by idMysteries** [comment]
![image](https://user-images.githubusercontent.com/11484976/192835300-d1d1b1df-4357-405c-ba81-61ebb643d791.png)
ahahahahah i'm sooooo stupid...

**Comment by idMysteries** [comment]
Ammm your code also don't work

**Comment by budikesuma** [comment]
@idMysteries 

Let's try this regex:

```
((PREVIOUS|NEXT) CHAPTER|CHAPTER LIST)

(FOLLOW / LIKE / SUBSCRIBE|FOLLOW AND LIKE THIS BLOG|SUBSCRIBE [Aa][Nn][Dd] LIKE|Please donate( any amount)? to support our group\!)
```

**Comment by dipu-bd** [comment]
> Ammm your code also don't work

fixed
