### ISSUE TITLE
Bug on Disord 

### ISSUE THREAD

**Issue by levinuiiy** [dipu-bd/lightnovel-crawler#1666]
## Let us know

**App source**:    PIP | EXE | Discord | Telegram 
**App version**:   x.y.z  
**Your OS**:       Linux | Windows | Mac

**Comment by budikesuma** [comment]
@levinuiiy 
Well, here's an example of a lazy human being...
You should at least provide screenshots if you don't have the hands to type the details of the error you are facing!!!
