### ISSUE TITLE
Images downloader issue on Dev V3.0.0

### ISSUE THREAD

**Issue by budikesuma** [dipu-bd/lightnovel-crawler#1675]
## Describe the bug

I'm testing Lncrawler dev `version 3.0.0` through `Google Colab`.
I'm not convinced by reports of some discord members using discord bots having problems with images not appearing in their novels.
Well, not just the cover image but also the images in the chapters on any novels.

I finally figured out that there was a problem downloading the images.

Please see my images capture below for the log.

**App source**:    Discord | Google Colab

**App version**:   3.00  
.
.
![Screenshot_20221003-105123_Browser](https://user-images.githubusercontent.com/50254552/193499730-373853b9-11f4-4b6a-8376-fe0383e2322c.jpg)
![Screenshot_20221003-105051_Browser](https://user-images.githubusercontent.com/50254552/193499746-54fe80f3-5ed8-4e57-a5d1-f537f0bb514b.jpg)
![Screenshot_20221003-105007_Browser](https://user-images.githubusercontent.com/50254552/193499760-16b30937-b02b-4a5d-8f2c-a96cbb14a3fa.jpg)

**Comment by dipu-bd** [comment]
This should be a source issue. Becuase happens only in creativenovels. I fixed the issue for the source.
