### ISSUE TITLE
Fix this source: https://readlightnovels.net/

### ISSUE THREAD

**Issue by budikesuma** [dipu-bd/lightnovel-crawler#1677]
**Novel URL**:     https://readlightnovels.net/a-will-eternal.html 

**App Location**:    PIP | Discord | Google Colab 

**App Version**: 2.29.4, 2.29.6, 2.34.0, maybe 3.0.0?  

## Describe this issue

I found that the `readlightnovels.net` script is based on `pagination` order.
Causing the chapter order to be hard to detect.
I tried the novel `AWE` for easy detection the 1st chapter later which happened to have images for later I tried to dev version 3.0.0.

The 1st chapter, which contains illustrations with pictures, was thrown to 146th place.
For the 2nd chapter, which contains the glossary, I don't know where it was thrown.

Maybe it also happened to the `novelfull.com` script? Because the script was taken from it?

**Comment by budikesuma** [comment]
This SS capture from dev V 3.0.0
`Failed` to packs to epub, after finished crawling chapters. 
. 
.
![Screenshot_20221003-190537_Browser](https://user-images.githubusercontent.com/50254552/193573430-ff9a5d5b-5ba4-4cfb-acb8-f31e74abea6f.jpg)
![Screenshot_20221003-190559_Browser](https://user-images.githubusercontent.com/50254552/193573448-9633b3ce-b97c-4985-9c86-1e903511c90c.jpg)

**Comment by idMysteries** [comment]
Today I downloaded 1000 chapters from novelfull.com and everything was fine.

**Comment by budikesuma** [comment]
> Today I downloaded 1000 chapters from novelfull.com and everything was fine.

It's because novelfull.com doesn't have 2 beginning chapters contains illustration & glossary (for AWE novel).

**Comment by idMysteries** [comment]
@dipu-bd I have checked the code and understand that it is not very good. It doesn't work very well if there is no chapter number in the chapter title.

**Comment by idMysteries** [comment]
> It's because novelfull.com doesn't have 2 beginning chapters contains illustration & glossary (for AWE novel).
No, it's because there are no numbers in these chapters.

**Comment by idMysteries** [comment]
@dipu-bd 
``` py
            chapter_id = len(self.chapters) + 1
            match = re.findall(r"ch(apter)? (\d+)", title, re.IGNORECASE)
            if len(match) == 1:
                chapter_id = int(match[0][1])
```
