### ISSUE TITLE
https://freewebnovel.com/

### ISSUE THREAD

**Issue by budikesuma** [dipu-bd/lightnovel-crawler#1678]
Since the source code wasn't available yet, I requested it. (Perhaps this will be a duplicate of a previous request that has not been fulfilled, so please forgive...)

Actually, this aggregate site has been around for a while.

It's quite clean and formatted according to the original source as in the footnotes of the chapters that other aggregate sites often ignore.

There are also illustration images if the original source has them.

Novel url:
https://freewebnovel.com/a-will-eternal.html

**Comment by idMysteries** [comment]
Looks good, I'll write the crawler for this site.
