### ISSUE TITLE
Source index wrong version number and contributors list

### ISSUE THREAD

**Issue by idMysteries** [dipu-bd/lightnovel-crawler#1686]
![image](https://user-images.githubusercontent.com/11484976/193889472-fb60d419-f774-41d2-82bf-f34c209bf7bc.png)
![image](https://user-images.githubusercontent.com/11484976/193890794-a835d7c4-2c88-48fc-8b88-a12e6496ddbb.png)

@dipu-bd sadly...

**Comment by dipu-bd** [comment]
version number are just being calculated from git commit history:

```
git log --follow --diff-filter=ACMT --pretty="%at||%aN||%aE||%s" .\sources\en\n\novelbin.py
```

It just behaves this way. I did not find any better alternatives.

**Comment by idMysteries** [comment]
74?????

**Comment by dipu-bd** [comment]
it means there were 74 changes in git history for this file

**Comment by idMysteries** [comment]
New files! It should be 1 or <10

**Comment by idMysteries** [comment]
![image](https://user-images.githubusercontent.com/11484976/193890988-83aac9e8-774f-4bf7-a4fc-f533a7e760cd.png)

**Comment by dipu-bd** [comment]
maybe git matches it with other existing file and say it has 74 older versions

**Comment by dipu-bd** [comment]
Check the `--diff-filter=ACMT` option in the command. That is where we tell what changes to track.

![image](https://user-images.githubusercontent.com/5158124/193891405-3156ac01-ffd9-47e3-8581-8268401eb6ec.png)

**Comment by dipu-bd** [comment]
We can just change the option to a better one.

**Comment by idMysteries** [comment]
6 contributors... Impossible

**Comment by dipu-bd** [comment]
I think using `ACT` will give better results

**Comment by dipu-bd** [comment]
> 6 contributors... Impossible

some people can copy crawler other people write. combining them together it is possible to have 6 contributors. but in our case, most of the time it unexpected number because of the limitation of git log filter.

**Comment by dipu-bd** [comment]
what do you think about the current list?

**Comment by idMysteries** [comment]
It doesn't seem that way. It turned out 3 contributors for the new file.

**Comment by idMysteries** [comment]
symlink, submodule... idk what is it

**Comment by idMysteries** [comment]
![image](https://user-images.githubusercontent.com/11484976/193893815-eea16be2-9a37-43ac-bd4c-74be13f11930.png)
1 commit...

**Comment by idMysteries** [comment]
If there is no other way, then so be it. I just don't understand why there are 3 contributors when I was the only one dealing with these files.

**Comment by idMysteries** [comment]
![image](https://user-images.githubusercontent.com/11484976/193896982-08577759-73fd-4b2f-be7e-521bfa356e96.png)
ACM maybe?? Or just AM?
You and I have been removed.

**Comment by idMysteries** [comment]
Does diff-filer needed? "Select only files..."

**Comment by idMysteries** [comment]
```
git log --oneline --pretty="%at||%aN||%aE||%s" .\sources\en\n\novelbin.py
```
?

**Comment by idMysteries** [comment]
![image](https://user-images.githubusercontent.com/11484976/193902763-18fc1d1d-a553-43ad-8e6f-adaf200a1285.png)
git log --pretty="%at||%aN||%aE||%s" .\sources\en\n\novelbin.py

**Comment by idMysteries** [comment]
In general, it seems that the diff-filter works poorly.

**Comment by idMysteries** [comment]
@dipu-bd yeeaaaaaahh!!!!

**Comment by idMysteries** [comment]
```
git log --follow --pretty="%at||%aN||%aE||%s" .\sources\en\s\scribblehub.py
```

**Comment by idMysteries** [comment]
@dipu-bd no... ffffffuuuuuuuuu.... Whyyy????

**Comment by idMysteries** [comment]
![image](https://user-images.githubusercontent.com/11484976/193907673-a2ae23d9-847b-49b2-80d5-c795b1029181.png)

**Comment by dipu-bd** [comment]
Check that the first commit that shows here is `Organize sources`. All the changes prior to that is not appearing. But there were a lot of changes before that too. Without `--follow` and `M`, they do not appear

**Comment by idMysteries** [comment]
Should we sacrifice old (before rename) versions?
git log --pretty="%at||%aN||%aE||%s" "%s"

![image](https://user-images.githubusercontent.com/11484976/193915439-611bea7d-89fb-4003-89a1-3282bfed4161.png)
![image](https://user-images.githubusercontent.com/11484976/193915493-9dc0b7a1-e91d-4e2c-adb1-7bfd36d524bf.png)

**Comment by dipu-bd** [comment]
Currently this version is being used to check whether the file is updated in old releases.

Although it does not matter at this point since we are releasing a major version next.

**Comment by idMysteries** [comment]
After renaming, the data will be lost, alas.

**Comment by idMysteries** [comment]
https://stackoverflow.com/questions/30443906/git-log-follow-show-all-commits-including-merges

**Comment by dipu-bd** [comment]
> Should we sacrifice old (before rename) versions? Start a new version count. git log --pretty="%at||%aN||%aE||%s" "%s"
> 
> ![image](https://user-images.githubusercontent.com/11484976/193915439-611bea7d-89fb-4003-89a1-3282bfed4161.png) ![image](https://user-images.githubusercontent.com/11484976/193915493-9dc0b7a1-e91d-4e2c-adb1-7bfd36d524bf.png)

No it removes a lot of original contributors. Let's keep it as it was before.

If someone copy-pastes code from another file, we should give value to the author of that another file too.

**Comment by dipu-bd** [comment]
![image](https://user-images.githubusercontent.com/5158124/193919034-9e7e3dd9-82ef-4dd3-bf43-8d354d063711.png)

I have a rough guess why this new crawler for file novelhulk has such a high version and so many contributors.

Since the code is very similar to novelfull, the git diff matcher probably though it was renamed from novelfull. I found proof of this theory by comitting another file created using novelfull template and generating index.

**Comment by idMysteries** [comment]
Wow....

**Comment by dipu-bd** [comment]
If in the future, somebody copy you novelhulk crawler, and create another one, I think it will be proper for you to be added in the contributor list too.

**Comment by idMysteries** [comment]
It's strange why --follow has this behavior.

**Comment by idMysteries** [comment]
GitHub somehow handles files normally.

**Comment by dipu-bd** [comment]
Yeah, they have their internal database
