### ISSUE TITLE
No idea what kind of bug this is?

### ISSUE THREAD

**Issue by budikesuma** [dipu-bd/lightnovel-crawler#1698]
On Google Colab. 

Novel url: https://88tangeatdrinkread.wordpress.com/2020/05/04/remarry-no-way-%e6%83%b3%e5%a4%8d%e5%a9%9a-%e6%b2%a1%e9%97%a8-by-nan-lin-%e5%8d%97%e5%87%9b-table-of-content/

I don't know what these error logs mean?
I have tried 2 versions.

So the first test was on `version 3.0.0`.
No luck downloading the images in the novel. I didn't need to look at the epub, when I checked the folder file tree there was no image folder there. (The size of the epub is also very small).
.
.
![Screenshot_20221009-154309_Browser](https://user-images.githubusercontent.com/50254552/194748656-59055d11-0fd8-453f-abc8-c25f894b8483.jpg)

![Screenshot_20221009-154347_Browser](https://user-images.githubusercontent.com/50254552/194748669-024846b5-f0d5-4db1-94df-deb6ce65f058.jpg)

![Screenshot_20221009-154409_Browser](https://user-images.githubusercontent.com/50254552/194748697-c82a43ac-d5e0-4861-8a86-cd11f93aecbd.jpg)

![Screenshot_20221009-154515_Browser](https://user-images.githubusercontent.com/50254552/194748710-05f3f6cb-aee0-4332-9feb-d20874014e55.jpg)

**Comment by budikesuma** [comment]
The Second test on `version 2.34.0`.
Successfully downloaded all the images in the active image link.
Proven by the existence of the `image folder` in the folder file tree.
.
.
![Screenshot_20221009-155909_Browser](https://user-images.githubusercontent.com/50254552/194748910-ba8f52e2-0941-4c17-9fb0-3ab4666b0786.jpg)

![Screenshot_20221009-155929_Browser](https://user-images.githubusercontent.com/50254552/194748921-ec06e862-0c8c-42d0-a9d8-8540ae70e301.jpg)

![Screenshot_20221009-155948_Browser](https://user-images.githubusercontent.com/50254552/194748932-1a8562a6-3c52-4a85-81a8-88326c948fd8.jpg)

![Screenshot_20221009-155457_Browser](https://user-images.githubusercontent.com/50254552/194748958-f565a717-a198-4f2b-bebe-07d09341a696.jpg)

**Comment by dipu-bd** [comment]
Found the cause. Removing the `# -*- coding: utf-8 -*-` from the top of files was showing encoding error. I will fix this.
