### ISSUE TITLE
Fix this source - webnovel is not working 

### ISSUE THREAD

**Issue by read-novel** [dipu-bd/lightnovel-crawler#1700]
## Let us know webnovel is not working its say no chapter found

**Novel URL**:     <your novel url or query>  https://m.webnovel.com/book/reincarnated-as-a-second-generation-villain_24177590106821405
**App Location**:     in Discord.                  
   Where did you find this issue - in discord bot 
**App Version**:   x.y.z   lightnovel crawler 3.0

## Describe this issue

![tmp-cam-490505429482425117](https://user-images.githubusercontent.com/107703937/194769711-e367b423-a764-486f-9706-8e5f5179b277.jpg)

**Comment by read-novel** [comment]
![Uploading Screenshot_20221009_221028.jpg…]()

**Comment by dipu-bd** [comment]
![image](https://user-images.githubusercontent.com/5158124/194774170-cdaa275c-2a08-4e0f-8fb6-8fb92dd0316f.png)

It is working for me though

**Comment by dipu-bd** [comment]
The link posted here does not match the link in your image. Check again please.

**Comment by idMysteries** [comment]
> The link posted here does not match the link in your image. Check again please.

.... @dipu-bd maybe this?
https://m.webnovel.com/

**Comment by idMysteries** [comment]
Maybe the thing is that the link to the mobile version? And you tested the link to the desktop version. @dipu-bd

**Comment by dipu-bd** [comment]
It is the discord bot. Mobile or desktop it goes to the same server.

**Comment by dipu-bd** [comment]
Strange, for some reason m.webnovel.com does not redirect to www.webnovel.com in the selenium grid

**Comment by budikesuma** [comment]
Not both of them of course, this is because the link from @read-novel  has the `!` character, which is not allowed.

You have to cut the link down to just this: https://www.webnovel.com/book/24321566405563505

**Comment by dipu-bd** [comment]
Changing `m` to `www` is being done in the crawler now. only proper name formatting is required for now.
