### ISSUE TITLE
https://readmtl.com/

### ISSUE THREAD

**Issue by levinuiiy** [dipu-bd/lightnovel-crawler#1704]
idk

No, it has not been requested

- Language: English
- Supports Searching: Yes
- Contains Machine Translations: Yes
- Contains Manga/Manhua/Manhwa: No
- Has CloudFlare Protection: i think No

**Comment by idMysteries** [comment]
``` py
# dev notes
madara template
```

**Comment by idMysteries** [comment]
@dipu-bd 
![image](https://user-images.githubusercontent.com/11484976/194864970-80df9871-81fb-4fa8-945b-886b42a91933.png)
![image](https://user-images.githubusercontent.com/11484976/194864999-958d6298-774c-446e-875c-9f6caecc4e21.png)

**Comment by dipu-bd** [comment]
Well... how do we decide then which API to hit? I have a simple solution for now: using a `try...except`

**Comment by idMysteries** [comment]
> Well... how do we decide then which API to hit? I have a simple solution for now: using a `try...except`

try new (ajax/chapters/) if chapters == 0 then try old api...

**Comment by dipu-bd** [comment]
> try new (ajax/chapters/) if chapters == 0 (or HTTPError) then try old api...
> 
> @dipu-bd default is "ajax/chapters/"... try except HTTPError?

Okay, I will use ajax/chapters by default
