### ISSUE TITLE
Scribblehub direct link not working

### ISSUE THREAD

**Issue by slanesteve** [dipu-bd/lightnovel-crawler#1705]
any url posted for scribblehub no longer works in v. 3.1...used to work in 2.34

**Comment by dipu-bd** [comment]
Please report a `source-issue` with URL you are trying. Use the following link to reopen this issue:

https://github.com/dipu-bd/lightnovel-crawler/issues/new?assignees=&labels=source-issue&template=3_source-issue.md&title=Fix+this+source
