### ISSUE TITLE
HTTPError 400

### ISSUE THREAD

**Issue by SirGryphin** [dipu-bd/lightnovel-crawler#1707]
So with latest version I noticed this error on a lot of sites.

`requests.exceptions.HTTPError: 400 Client Error: Bad Request for url:`

Looks like any site using the `wp-admin/admin-ajax.php` to get chapters is failing. I tried zinnovel which is same template but using `chapters = soup.select("ul.main li.wp-manga-chapter a")` and it working fine.

**App source**:    PIP
**App version**:   3.0.1
**Your OS**:       Windows

**Comment by dipu-bd** [comment]
Maybe `Host`, `Origin` etc. header is causing the issues. Have to check to be sure.

**Comment by idMysteries** [comment]
"Ru: jaomix" error 400 @dipu-bd T_T

**Comment by dipu-bd** [comment]
should be fixed now
