### ISSUE TITLE
boxnovel.org

### ISSUE THREAD

**Issue by SirGryphin** [dipu-bd/lightnovel-crawler#1719]
boxnovel.org has not changed to novelfull.live. The original link http redirect to correct site but https redirects to beautymanga.com. I was just going to change code below but I noticed the original source isn't working correctly, it shows double/triple the amount of  chapters and there completely out of order.

Having a quick look it seems like it using `csrf token` instead of ajax like other novelfull sites and I'm not sure how to make source using that.

https://github.com/dipu-bd/lightnovel-crawler/blob/9225c27e65435a9fb467615653fd2bec02805b59/sources/en/b/boxnovelorg.py#L13-L17

**App Location**:    PIP
**App Version**:   3.0.1

**Comment by dipu-bd** [comment]
now it shows an empty website. time to move it to rejected list
