### ISSUE TITLE
Webnovel is not working 

### ISSUE THREAD

**Issue by read-novel** [dipu-bd/lightnovel-crawler#1722]
## Let us know The discord bot say (No chapter found). Yesterday bot was working perfect but now this 

**Novel URL**:     <https://m.webnovel.com/book/conquering-the-novel_24244163506313605> 
**App Location**:    | Discord |   in discord bot 
**App Version**:   x.y.z   
Lightnovel crawler 3.0
## Describe this issue i even change M to WWW and even delete name of the novel  in link but didn't work 

![Screenshot_20221014_183903](https://user-images.githubusercontent.com/107703937/195856248-c001316f-5008-417e-a6d1-4110591b7b56.jpg)
![Screenshot_20221014_183856](https://user-images.githubusercontent.com/107703937/195856332-96754ea1-3a69-4306-83be-3705ea6ab522.jpg)

**Comment by dipu-bd** [comment]
Looks like a issue with the selenium grid. Restarted the discord bot server. I hope it will be alright now.

**Comment by read-novel** [comment]
Thank, it working properly nowv

**Comment by read-novel** [comment]
It again say no chapter found, bro restart the bot of disord

**Comment by read-novel** [comment]
![Uploading Screenshot_20221019_214339.jpg…]()

**Comment by read-novel** [comment]
![Screenshot_20221019_214339](https://user-images.githubusercontent.com/107703937/196747819-e0c3ba2c-6965-41fc-87e1-ff662c3790bb.jpg)

**Comment by dipu-bd** [comment]
> It again say no chapter found, bro restart the bot of disord

you can use the python app or the exe package. do not rely on the bots.
