### ISSUE TITLE
Fix this source: wuxiaworld.com in chromedriver mode

### ISSUE THREAD

**Issue by alethiophile** [dipu-bd/lightnovel-crawler#1726]
**Novel URL**:     https://www.wuxiaworld.com/novel/absolute-resonance 
**App Location**:    PIP 
**App Version**:   3.0.1  

## Describe this issue

When crawling wuxiaworld.com using chromedriver, if not logged in, after ten chapter loads wuxiaworld will show its "chapter limit for anonymous viewers" screen. Likewise, on occasion the server connection to the backend server will hang inside chromedriver, and the frontend will get stuck in a loading animation.

In both of these cases, where the chromedriver code can't find the data it's looking for, lncrawl just hangs forever. Ideally, it would either retry after a timeout, or exit on error so that the user can do so.

**Comment by dipu-bd** [comment]
It should not hang forever. Timout is 5 minutes. How long have it been waiting for you?
