### ISSUE TITLE
[mtlnation] Failed to download chapter body

### ISSUE THREAD

**Issue by WorldlyDemon** [dipu-bd/lightnovel-crawler#1727]
![Photos 17-10-2022 08_17_34](https://user-images.githubusercontent.com/115963407/196078594-3bc35d05-1473-469a-aefc-d13ce7e05c23.png)

And I get this error when downloading chapter 
![Screenshot 17-10-2022 08_15_07](https://user-images.githubusercontent.com/115963407/196078299-68e1e32e-a2eb-4cc0-9d11-0bffd57a5983.png)
Btw I havent tried to download from other sites so dont know if its only for mtlnation

**Comment by dipu-bd** [comment]
Because cloudflare is blocking them.
