### ISSUE TITLE
No chapters found. (www.isotls.com)

### ISSUE THREAD

**Issue by graciagraciagracia** [dipu-bd/lightnovel-crawler#1738]
No

## Let us know

**Novel URL**:     <your novel url or query> https://www.isotls.com/looting-equipment-from-npc/
**App Location**:   Discord
**App Version**:   Lightnovel Crawler 3.0.1

## Describe this issue

 The bot cannot find any chapters.

![image](https://user-images.githubusercontent.com/84960307/198217018-cf8dcaae-17ec-4df8-9801-5876075bf713.png)

**Comment by zerty** [comment]
Probably cloudflare protection
