### ISSUE TITLE
[novelsemperor.com] Error: No chapters found (cloudflare v2)

### ISSUE THREAD

**Issue by LisArits** [dipu-bd/lightnovel-crawler#1743]
Novel URL: https://novelsemperor.com/series/horror-resurgence-maam-please-respect-my-profession/
Version: Lightnovel Crawler 3.0.1

![Безымянн2222ый](https://user-images.githubusercontent.com/113008317/198837663-7c79c8d0-cb73-4cae-8a08-e642ab7bdfac.png)

**Comment by mesmerlord** [comment]
Its a cloudflare issue, either wait for the site owner to lower the cloudflare security level or search for the novel in other supported sources.
