### ISSUE TITLE
[mangabuddy.com] HTTPError: 403 Client Error

### ISSUE THREAD

**Issue by jere344** [dipu-bd/lightnovel-crawler#1752]
**Novel URL**:     https://mangabuddy.com/hellsing
**App Location**:    run from source
**App Version**:   3.0.1

## Describe this issue

Images download are forbidden.
Even on the website when I open image in new tab I randomly get blocked.

Cover `src` and `data-src` are also set after loading, so the crawler is downloading a placeholder instead of the actual cover

![image](https://user-images.githubusercontent.com/86294972/199363873-542da618-8402-41a1-b50e-170175323526.png)

**Comment by dipu-bd** [comment]
most probably this error is from the website itself. This shows up in my browser:

![image](https://user-images.githubusercontent.com/5158124/203661116-daff0145-af9e-4808-986a-2dff41583acc.png)

**Comment by dipu-bd** [comment]
fixed the cover issue however
