### ISSUE TITLE
Post requests from `self.submit_form` fail where `requests.post` works

### ISSUE THREAD

**Issue by jere344** [dipu-bd/lightnovel-crawler#1758]
Some sources including : 
https://novelsite.net/
https://listnovel.com/
https://myboxnovel.com/
https://readlightnovels.net/
https://clicknovel.net/
can't scrape chapter list because of a bug somewhere in crawlers `submit_form` as replacing submit_form by a standard post requests fix it.

Does not work currently :
```
response = self.submit_form(
     chapter_list_url, data="action=manga_get_chapters&manga=" + self.novel_id
)
```
![image](https://user-images.githubusercontent.com/86294972/199871871-63205b4e-f4d4-4015-b514-d7afa76bd6d2.png)
Work : 
```
import requests
response = requests.post(
     chapter_list_url, data={"action": "manga_get_chapters", "manga": self.novel_id}
)
```
![image](https://user-images.githubusercontent.com/86294972/199873647-f0233f64-f42e-4e25-9b34-3fa441c12fee.png)

**App source**:    run from source
**App version**:  3.0.1
**Your OS**:       Linux | Windows

PS : I can't find a way to add the `bug` label, sry about that

**Comment by dipu-bd** [comment]
should work now
