### ISSUE TITLE
[novels.pl] No chapters found

### ISSUE THREAD

**Issue by stbooks** [dipu-bd/lightnovel-crawler#1765]
**Novel URL**:     https://www.novels.pl/novel/Hidden-Blade
**App Location**:    run from source
**App Version**:  3.0.1

## Describe this issue

 Can't get any chapters

![Issue](https://user-images.githubusercontent.com/96806134/200097775-4cbea507-bfac-481b-a711-60998747dbe8.jpeg)

**Comment by dipu-bd** [comment]
fixed
