### ISSUE TITLE
https://www.xunovel.com/

### ISSUE THREAD

**Issue by levinuiiy** [dipu-bd/lightnovel-crawler#1774]
No, & checked it was not requested yet

- Language: English 
- Supports Searching: Yes
- Contains Machine Translations: Yes
- Contains Manga/Manhua/Manhwa: No
- Has CloudFlare Protection: i think No, since i didn't see any of it pop up, [& also Has alot of MTL Novels]

**Comment by dipu-bd** [comment]
Duplicate of #1703
