### ISSUE TITLE
The browser templates are using soup read_novel_info templates functions 

### ISSUE THREAD

**Issue by zerty** [dipu-bd/lightnovel-crawler#1778]
https://github.com/dipu-bd/lightnovel-crawler/blob/1019e751d20a7b8d72243b7d03c97bddd6069901/lncrawl/templates/browser/general.py#L19

As seen this line call for GeneralSoupTemplate read_novel_info() and not the BasicBrowserTemplate
The main problem is that in that behavior if the read_novel_info fails when executing self.read_novel_info_in_browser() the browser is not initialized properly.

a solution would be to switch to `self.read_novel_info()` or switch  `GeneralBrowserTemplate(GeneralSoupTemplate, BasicBrowserTemplate):` to `GeneralBrowserTemplate( BasicBrowserTemplate,GeneralSoupTemplate):`.

The same problem is present in the searchable browser

**Comment by dipu-bd** [comment]
You are right. I fixed the issues.
