### ISSUE TITLE
Fix this source: www.novels.pl

### ISSUE THREAD

**Issue by Marokarr** [dipu-bd/lightnovel-crawler#1785]
## Let us know

**Novel URL**: https://www.novels.pl/novel/A-Demon-Lords-Tale-Dungeons-Monster-Girls-and-Heartwarming-Bliss-Novel
**App Location**:   EXE
**App Version**:  3.0.1

## Describe this issue

When using the Search function to find the novel in question and selecting the source listed above, it does not download. It just asks if you want to choose another novel? If you provide the URL to the novel, it gives an error message stating that no chapters are found

## Screenshots
![Screenshot 2022-11-22 035000](https://user-images.githubusercontent.com/7029039/203271102-6d76f781-3481-452c-80a4-0670b5ab5a24.png)

**Comment by dipu-bd** [comment]
#1765
