### ISSUE TITLE
Crashing at start

### ISSUE THREAD

**Issue by Mugworth** [dipu-bd/lightnovel-crawler#1787]
OS: Linux mint 21
Python: 3.10.6

I downloaded multiple versions none of them seems to work, when i tried to open by st -e lncrawl, i got this output

X Error of failed request:  BadLength (poly request too large or internal Xlib length error)
  Major opcode of failed request:  139 (RENDER)
  Minor opcode of failed request:  20 (RenderAddGlyphs)
  Serial number of failed request:  1028
  Current serial number in output stream:  1054

**Comment by dipu-bd** [comment]
Please provide more information. It is difficult to understand where the problem is from your description. Give some screenshots or full console log.

**Comment by Mugworth** [comment]
Ok i tried to open it lncrawl with urxvt and it worked, i installed font emojione, font-symbola and st didnt crash, sorry for taking your time
