### ISSUE TITLE
FanFiction.net

### ISSUE THREAD

**Issue by thegreatestminer** [dipu-bd/lightnovel-crawler#179]
I know this is for light novel hosts, but I noticed Wattpad was on this list, so I thought that this could fall under the category too.

Many thanks!

**Comment by dipu-bd** [comment]
The sources added here all have same structure:
- first we need a way to get the Table of Contents for a books, that is a list of all chapters.
- next, a way to get the texts of each chapters.

I did not found any clear way to identify chapters for books in https://www.fanfiction.net

**Comment by dipu-bd** [comment]
closing since there is no further response

**Comment by Veedrac** [comment]
The chapters are just at https://www.fanfiction.net/s/$STORY_ID/$CHAPTER_NUMBER.

At https://www.fanfiction.net/s/$STORY_ID/ there is both a “Chapters: 123” that tells you the number of chapters, and a drop-down with a list of chapters and their names. These will both be missing if there is only one chapter.

Here's an example with multiple chapters, if that was your issue https://www.fanfiction.net/s/11952352.

(The source looks pretty clean so if I have energy I might just do this myself. I assume I just add a file to spiders/ and register it somewhere.)

**Comment by dipu-bd** [comment]
at first I misunderstood the site. each of the listed books has some fan-written stories. each of the stories has some chapters. it will be fairly simple to integrate it in this app. i will add it soon.

**Comment by dipu-bd** [comment]
will be available in 2.16.1
