### ISSUE TITLE
Freezing when downloading chapters

### ISSUE THREAD

**Issue by SirGryphin** [dipu-bd/lightnovel-crawler#1794]
So I'm not sure where to post this, so I created a general issue.

I've noticed that the latest "DEV" version locks up or freezes when downloading chapters, then unfreezes when the operation is finished and asks if you want to open the output folder, but I don't see it downloading the chapter (loading bar) or anything.

It freezes at `? How many files to generate? Pack everything into a single file` and unfreezes at `? Open the output folder? (Y/n)`

It doesn't cause any problems with novels as far as I can see, but if you're impatient, it might seem like it crashed for some people.

**Comment by dipu-bd** [comment]
I pushed a commit to fix this issue. Can you check now?

**Comment by SirGryphin** [comment]
@dipu-bd working perfectly now, thanks.
