### ISSUE TITLE
Feature request: add karma unlock system to wuxiaworld.com login option.

### ISSUE THREAD

**Issue by budikesuma** [dipu-bd/lightnovel-crawler#1796]
Since it is no longer possible to scrape Wuxiaworld novels for free, it is time to add an auto unlock chapter feature with karma (default).
Hopefully the developer will approve it soon. 👍

Test Ongoing novel url (locked chapters started from chapter 51): https://www.wuxiaworld.com/novel/nine-star-hegemon

**Comment by alzamer2** [comment]
hello
new update was issued for wuxiaworld.com
update your sources and try scraping

ps: to use auto unlock make sure you enabled it in your wuxiaworld setting, and the script will do the unlocking while it scrap the chapters
