### ISSUE TITLE
Incorrect Chapter Titles [www.lightnovelpub.com]

### ISSUE THREAD

**Issue by dastrdly6585** [dipu-bd/lightnovel-crawler#1797]
## Let us know

**Novel URL**:  All novels (e.g. [https://www.lightnovelpub.com/novel/im-really-not-the-demon-gods-lackey-24111314](https://www.lightnovelpub.com/novel/im-really-not-the-demon-gods-lackey-24111314))
**App Location**:    EXE
**App Version**:   3.1.1

## Describe this issue

Previously, chapter titles were parsed from the website following the convention: `Chapter X: <Chapter Title>` (unless the chapter title is literally `Chapter X`).  After the recent update, the chapter titles now follow the convention: `X <Chapter Title> <Chapter Age>`.  The chapter title parsing should at minimum remove the chapter age (since that's not actually part of the chapter title), and if possible revert back to the original parsed format.

Example screenshot of chapter title parsing change: 

![image](https://user-images.githubusercontent.com/13990010/204199120-a914bed0-da31-45e5-82d7-79194c57135f.png)

**Comment by dipu-bd** [comment]
fixed
