### ISSUE TITLE
Fix this source

### ISSUE THREAD

**Issue by Luth22** [dipu-bd/lightnovel-crawler#1818]
yes

## Let us know

**Novel URL**:     <your novel url or query>  https://chapmanganato.com
**App Location**:    PIP | EXE | Discord | Telegram  discord and googlecollab

## Describe this issue

 There's something wrong.  It keeps on saying error.

 
![206824248-7b880f35-dd1e-4784-b5c7-423b945cb10d](https://user-images.githubusercontent.com/110596020/207042406-b95e037e-26e5-4d1d-9d8a-1f410f546c1a.jpg)

**Comment by dipu-bd** [comment]
There should be image urls right next to these error message. If you try them on your browser, you may see the same message there too. The site itself has broken content, the app can not do anything else in this situation.

**Comment by dipu-bd** [comment]
Try again now. It should work.
