### ISSUE TITLE
Fix this source: Webnovel

### ISSUE THREAD

**Issue by adithyasn1797** [dipu-bd/lightnovel-crawler#1819]
Yes

## Let us know

**Novel URL**:     https://m.webnovel.com/book/hero-of-darkness_20433994506434305 
**App Location**:    PIP 
**App Version**:   3.2.2  

## Describe this issue

The text on the chapters are incomplete. Mostly with chapters behind paywall.

This is how it looks
![image](https://user-images.githubusercontent.com/38696290/207274956-d9f706af-d340-49d2-b133-11ce9db371dc.png)

The same chapter in another site https://noveltop.net/novel/hero-of-darkness/ in web browser
![image](https://user-images.githubusercontent.com/38696290/207275331-1c46a268-6b4e-4413-9c21-d8fb158f71be.png)
![image](https://user-images.githubusercontent.com/38696290/207275541-3271ebe0-c005-48ed-8e25-70d4bb700aa7.png)
![image](https://user-images.githubusercontent.com/38696290/207275660-c99bb07b-4492-4117-9558-0258ab22e2f5.png)
![image](https://user-images.githubusercontent.com/38696290/207276105-d794d11b-ff74-4d09-bb14-f83059f658c5.png)

The error from console 
![image](https://user-images.githubusercontent.com/38696290/207276361-745732a0-112b-45ef-9745-9612bacae1ae.png)

The problem occurs with some other novels i tried to download. I can add the links for you if you would like to test with them.

**Comment by dipu-bd** [comment]
> The text on the chapters are incomplete. Mostly with chapters behind paywall.

Yeah! Behind paywall means, you have to pay for the full text. This app can't magically make text appear when there is none.

> The error from console

How did you get this error from console? I have never seen this kind of logs before.

**Comment by adithyasn1797** [comment]
I thought it might be the case. Just wanted to make sure. Thanks for the info

As for the logs, I am using linux with KDE. It might just be some package dependency issue
