### ISSUE TITLE
WuxiaWorld not signing in with bearer token

### ISSUE THREAD

**Issue by chrisdma** [dipu-bd/lightnovel-crawler#1822]
lncrwl 3.2.2 
Windows bundle EXE

Hello,

I am using lncrawl with a bearer token to get the chapters of https://www.wuxiaworld.com/novel/nine-star-hegemon however in the popup browser that is used to crawl for the volumes/chapters, it is not signed in and after 10 or so chapters I get the below error:

![image](https://user-images.githubusercontent.com/43798323/208524755-582686d1-8698-479f-8c7c-afc00ce497da.png)

It seems to not use the bearer token when crawling wuxiaworld.

Thanks,
Chris

**Comment by ShakeBake** [comment]
+1

**Comment by chrisdma** [comment]
If I do the exact same command on Ubuntu, I eventually get the below error after about 10 minutes:

![image](https://user-images.githubusercontent.com/43798323/208778728-9f75b3cb-0050-48c6-9993-437967205447.png)

**Comment by dipu-bd** [comment]
Refer to #1826
