### ISSUE TITLE
Support Browser login for wuxiaworld

### ISSUE THREAD

**Issue by dipu-bd** [dipu-bd/lightnovel-crawler#1826]
Am I doing something wrong? I log in with the bearer key and point it to the novel, but the script opens a new chrome window which isn't logged in and just takes the teasers/cut-off chapters. I would log in to the new window but it disappears and creates a new one to start getting chapters. 
![image](https://user-images.githubusercontent.com/29230146/208550952-6442c338-a1d7-4c21-848a-4f478d4028d8.png)

_Originally posted by @ShakeBake in https://github.com/dipu-bd/lightnovel-crawler/discussions/1360#discussioncomment-4452900_

**Comment by chrisdma** [comment]
@dipu-bd This doesn't only affect Windows; In my issue I created I showed the below screenshot of lightnovel-crawler running on Ubuntu:

![image](https://user-images.githubusercontent.com/43798323/208952053-62548e78-f4da-4468-b31f-ace4c5468068.png)

No matter what OS I am running it won't complete the download.

**Comment by alzamer2** [comment]
hello
new update was issued for wuxiaworld.com
update your sources and try scraping

Browser login is supported
