### ISSUE TITLE
Standalone Bundle for Windows link is dead

### ISSUE THREAD

**Issue by zapxcero** [dipu-bd/lightnovel-crawler#1832]
Current link: https://[rebrand.ly](https://rebrand.ly/lncrawl)/lncrawl

Can be found in:
 [Standalone Bundle (Windows, Linux)](https://github.com/dipu-bd/lightnovel-crawler#standalone-bundle-windows-linux)

**Comment by dipu-bd** [comment]
I checked the link and found it is working. Maybe the problem is in your ISP or browser security.
