### ISSUE TITLE
HTTP Error: 429 client error: Too many requests for ur

### ISSUE THREAD

**Issue by topo123** [dipu-bd/lightnovel-crawler#1835]
I am trying to download Ancient Thunder Dragon spell but I keep getting the error I think it has something to do with the rate limit and even if I change MAX_REQUESTS_PER_DOMAIN in the taskman file to a smaller number it does not help and I still get the same error. Could someone please help?

@dipu-bd

**Comment by dipu-bd** [comment]
Related to #1846 #1870
