### ISSUE TITLE
Enhancement - Novel log and update check

### ISSUE THREAD

**Issue by Vantageright** [dipu-bd/lightnovel-crawler#185]
as is the crawler doesn't know whats been downloaded or when. I suggest the crawler save a log of what was downloaded, from where and how many chapters it had at the time then an option to check each of the LNs for updates and download.

**Comment by dipu-bd** [comment]
Are you suggesting this enhancement for discord and telegram bots?

**Comment by Vantageright** [comment]
I meant for manual usage, no bot but whichever would be good.

**Comment by dipu-bd** [comment]
I think you want an option to resume download right? You can do it easily by using `-i` or `--ignore` option. If this option is provided, crawler will not delete the old folder and will only download chapters that are not found in json file.

**Comment by dipu-bd** [comment]
You can create a `bash` or `batch` file with the following content. Run the file to download only new chapters.

```
lncrawl -s <novel-1-content-page-url-here> --all -i --suppress --format epub pdf mobi
lncrawl -s <novel-2-content-page-url-here> --all -i --suppress --format epub pdf mobi
lncrawl -s <novel-3-content-page-url-here> --all -i --suppress --format epub pdf mobi
.
.
.
```
