### ISSUE TITLE
Android Install Instructions don't work

### ISSUE THREAD

**Issue by pwd-github** [dipu-bd/lightnovel-crawler#1856]
It fails to install. First the package webp doesn't exist and later grpcio have a legacy install error. 

Also the Termux on the Play Store is old and newer versions are only available via FDroid

**Comment by dipu-bd** [comment]
sorry, the android platform is not supported.

**Comment by FunMan1995** [comment]
Found solution [referenced](https://github.com/dipu-bd/lightnovel-crawler/pull/2248#issuecomment-2385158700)
