### ISSUE TITLE
problem 

### ISSUE THREAD

**Issue by suerfang** [dipu-bd/lightnovel-crawler#1888]
I am from another country and I wanted to see if it is possible to add another page to the project. This is "es.mtlnovel.com" and "wuxiaworld.site" are pages where you can read novels in Spanish, the program you made is fantastic, but there is no novel in Spanish. Additionally, it seems there is an error with the formatters because when I try to download in pdf format, it doesn't download in that format.

**Comment by yasel2219** [comment]
bro descárgalas en inglés y conviértelas en docx y después tradúcelas en español en https://translate.google.com como documento y después conviértela de nuevo con calibre en tu formato de lectura de preferencia . 
{Esto es como yo lo hago si quieres te paso la web de donde descargo mis novelas}

{ojo tienes que tener este programa https://calibre-ebook.com/download  instalado para que te convierta en .pdf y .docx}
