### ISSUE TITLE
PDF conversion not working

### ISSUE THREAD

**Issue by jimster6543** [dipu-bd/lightnovel-crawler#1931]
## Describe the bug
PDF conversion not working even updated to newest version of calibre, still nothing.
Tried on multiple sources all the same problem.

![scribblehuh-pdf-failed](https://user-images.githubusercontent.com/6154621/230751962-5a0be9e1-a2d0-4511-a8dd-b1b4649d1fc9.PNG)
![webnovel-pdf-failed](https://user-images.githubusercontent.com/6154621/230751964-e530211d-6cef-43b5-9a70-6954712f5836.PNG)
![royalroad-pdf-failed](https://user-images.githubusercontent.com/6154621/230751965-7b8f5a77-5484-47f4-8603-37aed63d6110.PNG)

## Let us know

**App source**:   EXE
**App version**:   3.2.4
**Your OS**:       Windows

**Comment by dipu-bd** [comment]
Fixed in 3.2.5
