### ISSUE TITLE
https://www.tapread.com 

### ISSUE THREAD

**Issue by sureshchhatwani12** [dipu-bd/lightnovel-crawler#194]
Hi,

Downloading from https://www.tapread.com for any novel getting error **bookid**

Can someone please let me know the correct way to download or is this the bug in app.

Thanks
![light-novel-crawler-taperead-issue](https://user-images.githubusercontent.com/31374067/64618120-4cc9f000-d3fd-11e9-8a65-f0491b907703.jpg)

**Comment by yudilee** [comment]
Just fixed it on pull request  #197
