### ISSUE TITLE
Babel Novel not working

### ISSUE THREAD

**Issue by 13kirito** [dipu-bd/lightnovel-crawler#200]
I have been trying to download this particular novel from Bablle Novel, but its showing 
! Error: 'data'

can u Please fix this...
![Screenshot_20190920-203415](https://user-images.githubusercontent.com/55593373/65338001-1ec37900-db7e-11e9-9d82-1247d6f7e08c.png)

- Novel URL: https://babelnovel.com/books/martial-god-asura
- App Version: 2.14
- Package: pip
- OS: Android

**Comment by dipu-bd** [comment]
already fixed. see #195 for more info
