### ISSUE TITLE
LNReader previously updated to readlightnovel.online now changed domain to readlightnovel.app

### ISSUE THREAD

**Issue by ghus3rz** [dipu-bd/lightnovel-crawler#2019]
Yes
## Let us know

readlightnovel.online  to readlightnovel.app

## Describe this issue

the site readlightnovel.online is now redirecting to readlightnovel.app. This means source now is not recognized in LNCrawler.

Thanks

**Comment by jere344** [comment]
I don't think readlightnovel.online was supported. I can only find the .cc .me and .org

**Comment by ghus3rz** [comment]
> I don't think readlightnovel.online was supported. I can only find the .cc .me and .org

the website started as lightnovelreader/lnreader.  The name change to readlightnovel.XXX is pretty recent

**Comment by jere344** [comment]
Thank you, I ctrl+f for `readlightnovel.online` but somehow missed it, it was in `lightnovelreader` like you said
