### ISSUE TITLE
https://www.69shu.com/

### ISSUE THREAD

**Issue by zGadli** [dipu-bd/lightnovel-crawler#2023]
- Language: ZH/Chinese
- Supports Searching: Yes
- Contains Machine Translations: Yes
- Contains Manga/Manhua/Manhwa: No
- Has CloudFlare Protection: No

**Comment by jere344** [comment]
Added earlier 
#2022

**Comment by zGadli** [comment]
> Added earlier #2022

Thank you so much @jere344 .
