### ISSUE TITLE
Fix this source: infinitenoveltranslations

### ISSUE THREAD

**Issue by AmazingJayy** [dipu-bd/lightnovel-crawler#2041]
I skimmed the existing issues, but didn't find this source listed

[
**Novel URL**:    https://infinitenoveltranslations.net/the-spearmaster-and-the-black-cat
**App Location**:   EXE
**App Version**:  v3.2.8

## Describe this issue

No chapters are found, despite there being over 400 listed on the given url.

Erros log:
 ! Error: No chapters found
<class 'Exception'>
File "lncrawl\bots\console\integration.py", line 107, in start
    raise e
  File "lncrawl\bots\console\integration.py", line 101, in start
    _download_novel()
  File "lncrawl\bots\console\integration.py", line 85, in _download_novel
    self.app.get_novel_info()
  File "lncrawl\core\app.py", line 137, in get_novel_info
    raise Exception("No chapters found")

**Comment by zGadli** [comment]
0:36:15 [DEBUG] (lncrawl.core)
Arguments: Namespace(log=3, log_file=None, list_sources=False, crawler=[], novel_page=None, query=None, login=None, output_formats=[], add_source_url=False, single=False, multi=False, output_path=None, filename=None, filename_only=False, force=False, ignore=False, all=False, first=None, last=None, page=None, range=None, volumes=None, chapters=None, proxy_file=None, auto_proxy=False, bot=None, shard_id=0, shard_count=1, selenium_grid=None, suppress=False, close_directly=False, extra={})

-> Press  Ctrl + C  to exit

20:36:16 [INFO] (lncrawl.core.app)
Initialized App
20:36:16 [DEBUG] (asyncio)
Using proactor: IocpProactor
? Enter novel page url or query novel: https://infinitenoveltranslations.net/the-spearmaster-and-the-black-cat
20:36:21 [INFO] (lncrawl.bots.console.integration)
Detected URL input
20:36:21 [INFO] (lncrawl.core.sources)
Initializing crawler for: https://infinitenoveltranslations.net/ [lightnovel-crawler\sources\en\i\infinitetrans.py]
Retrieving novel info...
20:36:22 [DEBUG] (036c256dbd577dc8733390d4810ab168)
Visiting https://infinitenoveltranslations.net/the-spearmaster-and-the-black-cat
20:36:22 [DEBUG] (lncrawl.core.scraper)
[GET] https://infinitenoveltranslations.net/the-spearmaster-and-the-black-cat
timeout=(7, 301), allow_redirects=True, proxies={}, headers={b'Origin': b'https://infinitenoveltranslations.net', b'Referer': b'https://infinitenoveltranslations.net/', b'User-Agent': b'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36'}
20:36:22 [DEBUG] (urllib3.connectionpool)
Starting new HTTPS connection (1): infinitenoveltranslations.net:443
20:36:22 [DEBUG] (urllib3.connectionpool)
https://infinitenoveltranslations.net:443 "GET /the-spearmaster-and-the-black-cat HTTP/1.1" 301 None
20:36:23 [DEBUG] (urllib3.connectionpool)
https://infinitenoveltranslations.net:443 "GET /the-spearmaster-and-the-black-cat/ HTTP/1.1" 200 None
utf-8
20:36:23 [INFO] (036c256dbd577dc8733390d4810ab168)
Novel title: The Spearmaster and the Black Cat
20:36:23 [INFO] (036c256dbd577dc8733390d4810ab168)
Novel cover: https://i0.wp.com/infinitenoveltranslations.net/wp-content/uploads/2021/11/001-scaled.jpg?resize=900%2C1323&ssl=1
20:36:23 [INFO] (036c256dbd577dc8733390d4810ab168)
Novel author: Infinite Novel Translations

 ! Error: No chapters found
<class 'Exception'>
File "lncrawl\bots\console\integration.py", line 107, in start
    raise e
  File "lightnovel-crawler\lncrawl\bots\console\integration.py", line 101, in start
    _download_novel()
  File "lightnovel-crawler\lncrawl\bots\console\integration.py", line 85, in _download_novel
    self.app.get_novel_info()
  File "lightnovel-crawler\lncrawl\core\app.py", line 137, in get_novel_info
    raise Exception("No chapters found")

20:36:23 [INFO] (lncrawl.core.app)
App destroyed

**Comment by zGadli** [comment]
Debug Logs for anyone who wants to fix the source. I'll try too.

**Comment by zGadli** [comment]
This issue should be closed. @dipu-bd
