### ISSUE TITLE
There is no such driver by url https://chromedriver.storage.googleapis.com/LATEST_RELEASE_116.0.5845

### ISSUE THREAD

**Issue by KijinSeijaa** [dipu-bd/lightnovel-crawler#2045]
## Describe the bug

================================================================================
                          [#] Lightnovel Crawler v3.2.8
                  https://github.com/dipu-bd/lightnovel-crawler
--------------------------------------------------------------------------------

-> Press  Ctrl + C  to exit

? Enter novel page url or query novel: https://www.lightnovelpub.com/novel/shadow-slave-30071448
Retrieving novel info...
TOC: 100%|███████████████████████████████████████████████████████████████████████████| 11/11 [00:04<00:00,  2.63page/s]

[#] Shadow Slave
11 volumes and 1089 chapters found.
- https://www.lightnovelpub.com/novel/shadow-slave-30071448

? Enter output directory: C:\Users\Name\Downloads\Lightnovels\www-lightnovelpub-com\Shadow Slave
? What to do with existing folder? Remove old folder and start fresh
? Which chapters to download? Custom range using index
? Enter start index (1 to 1089): 759
? Enter final index (1 to 1089): 1089
? 331 chapters selected Continue
? Which output formats to create? [epub]
? How many files to generate? Pack everything into a single file
Chapters:   8%|█████████████▊                                                                                                                                                      | 28/331 [00:06<01:06,  4.53item/s]
Chapters:   0%|                                                                                                                                                                             | 0/331 [00:00<?, ?item/s]Failed to get chapter: There is no such driver by url https://chromedriver.storage.googleapis.com/LATEST_RELEASE_116.0.5845
Chapters:   0%|▍                                                                                                                                                                    | 1/331 [00:05<29:40,  5.40s/item]Failed to get chapter: There is no such driver by url https://chromedriver.storage.googleapis.com/LATEST_RELEASE_116.0.5845
Chapters:   1%|▉                                                                                                                                                                    | 2/331 [00:10<29:01,  5.29s/item]Failed to get chapter: There is no such driver by url https://chromedriver.storage.googleapis.com/LATEST_RELEASE_116.0.5845
Chapters:   1%|█▍                                                                                                                                                                   | 3/331 [00:15<28:45,  5.26s/item]Failed to get chapter: There is no such driver by url https://chromedriver.storage.googleapis.com/LATEST_RELEASE_116.0.5845
Chapters:   1%|█▉                                                                                                                                                                   | 4/331 [00:21<28:29,  5.23s/item]Failed to get chapter: There is no such driver by url https://chromedriver.storage.googleapis.com/LATEST_RELEASE_116.0.5845
Chapters:   2%|██▍                                                                                                                                                                  | 5/331 [00:25<27:11,  5.00s/item]Failed to get chapter: There is no such driver by url https://chromedriver.storage.googleapis.com/LATEST_RELEASE_116.0.5845
Chapters:   2%|██▉                                                                                                                                                                  | 6/331 [00:30<26:26,  4.88s/item]Failed to get chapter: There is no such driver by url https://chromedriver.storage.googleapis.com/LATEST_RELEASE_116.0.5845
Chapters:   2%|███▍                                                                                                                                                                 | 7/331 [00:34<25:43,  4.76s/item]Failed to get chapter: There is no such driver by url https://chromedriver.storage.googleapis.com/LATEST_RELEASE_116.0.5845
Chapters:   2%|███▉                                                                                                                                                                 | 8/331 [00:39<24:58,  4.64s/item]

## Let us know

**App source**:    EXE
**App version**:   3.2.8
**Your OS**:       Windows

**Comment by alzamer2** [comment]
try updating webdriver_manager
pip install -U webdriver_manager

**Comment by DomID00** [comment]
> try updating webdriver_manager pip install -U webdriver_manager

the same, my webdriver is version: 4.0.0 but it still does not work

**Comment by KijinSeijaa** [comment]
> try updating webdriver_manager pip install -U webdriver_manager

I did this and lncrawl.exe is showing the same error.

**Comment by zGadli** [comment]
Try updating to the 3.2.9 version of lignovel-crawler/

**Comment by Nillth** [comment]
This appears to happen when you hit a API rate limit on the site.

**Comment by alzamer2** [comment]
say are you using beta version of chrome?
