### ISSUE TITLE
Translating the novel chapters if it's not in English.

### ISSUE THREAD

**Issue by zGadli** [dipu-bd/lightnovel-crawler#2055]
I was thinking that the user could get the option to choose whether to translate a novel to English when the language code for the source website is not `en`. The options can be `y` or `n`. The google translate API can be used for the translation or any other machine translation API.

**Comment by alexrambles** [comment]
Not sure how much good I'll be at this but I did implement this on a ln scraper I wrote, so I'm gonna give it a shot! No promises lol. I may just implement a CLI trigger for it.
