### ISSUE TITLE
Please please add this new source :D ---> https://www.xbanxia.com/

### ISSUE THREAD

**Issue by bonnetchuu** [dipu-bd/lightnovel-crawler#2058]
**https://www.xbanxia.com/**

- Language: **ZH / Chinese**
- Supports Searching: **Yes**
- Contains Machine Translations: **No**
- Contains Manga/Manhua/Manhwa: **No**
- Has CloudFlare Protection: **No**

Please please do add this site to your program!! Thank you very much!!

**Comment by zGadli** [comment]
This issue should be closed.
