### ISSUE TITLE
Please please add password input for this source! :D

### ISSUE THREAD

**Issue by vanessabluellie** [dipu-bd/lightnovel-crawler#2064]
Hello! I'm a new user of your brilliant program!! If it's permissible, I would like to request that a password input be integrated into the parser for the source: **https://chrysanthemumgarden.com/**

If it's possible, when the parser is scanning the novel page for the chapters, could it also detect whether some chapters within the Table of Contents are password-locked and will then **prompt the user to input the password** in order to proceed further? If the user chooses not to input the password, then Lightnovel Crawler will not result in any error, but it will just output only the accessible unlocked chapters? So this also means that if the **entire novel has no password-locked chapters**, the program will simply **skip over this input** and **give no prompt about the password**.

I saw that Webtoepub has integrated a password input specifically for this source (because it hosts lots of novels) which was able to successfully bypass it. But I like the format for your program and it's crawling ability (in not grabbing too many html elements) so I was wondering if maybe it'd be possible for Lightnovel Crawler to also implement this function? And your program was already able to completely fix the gibberish text which was a separate issue, so I was really amazed by that!

![image](https://github.com/dipu-bd/lightnovel-crawler/assets/55352222/97eea773-585d-4768-af6a-64a3655d1bc4)

Hoping this is possible!! Thank you very much!!! :D

P.S. But I sincerely apologise if someone else has already made this request and it wasn't permitted. Thank you regardless.

**Comment by jere344** [comment]
I think it already work similarly. When downloading from here it will ask you to login. If you do you can put anything in the username field (it's useless) and the password field is the password of the week. It will then download locked or unlocked chapters without issues.
If you don't it will download unlocked chapter, and just get `failed to download chapter body` for locked ones.

**Comment by vanessabluellie** [comment]
@jere344

AH okay!! I see, thank you very much! I shall wait for the new update. But I apologise for another question, I only just started using Lightnovel Crawler a couple days ago and I was wondering how to update the file? Does my existing downloaded .exe file automatically update when new commits are merged into the master branch? Or do I need to download the new .exe file that releases each time?

Apologies for the inconvenience and thank you very much for your speedy response!

**Comment by zGadli** [comment]
@vanessabluellie You could fork the dev branch from this repo and follow the steps in Readme.md to run the latest version.

**Comment by vanessabluellie** [comment]
@zGadli

Oh okay!! I umm actually just tried generating a novel from ChrysanthemumGarden with the new commit but umm **the source is completely broken now**...

Regardless of whether I choose "**Yes**" or "**No**" for **login option**, **nothing will generate into the epub** at all. Every chapter will only contain the text "**Failed to download chapter body**".

I used the password for "Yes" and nothing generated (not even the unlocked chapters that don't require a password). But then I switched and selected "No" for login and still the same result? No chapter text at all, only the headings and error message.

**This was the error:**

![image](https://github.com/dipu-bd/lightnovel-crawler/assets/55352222/1b2becf1-3e84-47c6-9b68-a4ccb0f2701e)

It appears for every single selected chapter when it attempted to grab the chapters and generate the epub :'(

I apologise again for the inconvenience!

**Comment by jere344** [comment]
@vanessabluellie 
You need to update the app to the dev branch too, not only the source because it needs #2040 to work.
There was also another issue fixed here #2066 not yet implemented

You can wait until it get fully updated or if you want to use the source right now you can go to `sources\en\c\chrysanthemumgarden.py` and edit it :
remove `encoding="utf8",` line 82
remove `multipart=True,` line 75
remove` , encoding="utf8"` line 70

**Comment by zGadli** [comment]
@vanessabluellie The app is updated. Try and check if the issue is fixed. If it is close the issue.

**Comment by vanessabluellie** [comment]
@zGadli

AH yes, it works perfectly!!! :D Thank you for all your time and effort! <3
