### ISSUE TITLE
unlimitednovelfailures

### ISSUE THREAD

**Issue by Flwk** [dipu-bd/lightnovel-crawler#213]
Hello

There is this source who publish one light novel  https://unlimitednovelfailures.mangamatters.com/

I think that's not too complicated to make it 

Thanks in advance :)

**Comment by dipu-bd** [comment]
It only has two novels. and there are no novels page. And both of the novels can be found in alternate sites:
- https://www.readlightnovel.org/risou-no-himo-seikatsu
- https://www.readlightnovel.org/tsuki-tsuki
