### ISSUE TITLE
Fix this source Novelhi.com

### ISSUE THREAD

**Issue by Nariod14** [dipu-bd/lightnovel-crawler#2142]
## Existing Issue?

I have searched the existing issues and see nothing about this source.

## Let us know

**Novel URL**:     https://novelhi.com/s/index/Transcending-the-Nine-Heavens
**App Location**:     PIP installed, through command line.
**App Version**:   3.3.0  

## Describe this issue

The below Error happens whenever I input the novel URL, but this source seems to be supported. Thus here I am reporting this. WEb2Epub also crashes on this site now as well. This is the only site where I can get a fully compiled novel so any help on this would be greatly appreciated!

![image](https://github.com/dipu-bd/lightnovel-crawler/assets/21109756/64e85262-2963-49f5-8cc0-4e521082f6a0)

**Comment by zGadli** [comment]
You are trying with the wrong link. This `https://novelhi.com/s/Transcending-the-Nine-Heavens` is the correct link. I tried with the latest version of lncrawler and it's working fine.

**Comment by Nariod14** [comment]
That did work! thank you, closing the issue now.
