### ISSUE TITLE
Fix this source: HostedNovel

### ISSUE THREAD

**Issue by marcussacana** [dipu-bd/lightnovel-crawler#2146]
**Novel URL**:  https://hostednovel.com/novel/theres-absolutely-no-problem-with-the-magic-cards-i-made/chapter-1
**App Location**:    EXE
**App Version**:   [#] Lightnovel Crawler v3.3.0

![WindowsTerminal_n0FuFnBL8v](https://github.com/dipu-bd/lightnovel-crawler/assets/10576957/0b1b3571-24a9-4ed2-90e7-f55d4857c634)

I tried the root url: https://hostednovel.com/novel/theres-absolutely-no-problem-with-the-magic-cards-i-made as well

**Comment by zGadli** [comment]
IF you want you can fork the repo and apply changes in the latest pending pull request by me and try again. It should work, It's working for me.
