### ISSUE TITLE
Fix this bug

### ISSUE THREAD

**Issue by 3dycosmo** [dipu-bd/lightnovel-crawler#215]
**Babelnovel being locked**
Could not get the lock chapter, nowadays even MTL website need to be lock, please @dipu-bd have this will you, thx bro

**Comrademao, you mind adding this site again?*
- Novel URL: [e.g. https://babelnovel.com/books/juvenile-medical-god/chapters/c63]
- App Version: [e.g. 2.16.0]
- Package: [pip3]
- OS: [e.g. MacOS Catalina]

**Comment by yudilee** [comment]
I don't think we can do anything about that(locked chapter) except adding method to login which then you should pay to babel novel for the locked chapter using your account to login

**Comment by dipu-bd** [comment]
I think it is best to search for your novel in alternate sources. We can only get what we see. With locking feature, there is nothing we can do.

**Comment by 3dycosmo** [comment]
Thx, and could you add Comrademao

**Comment by 3dycosmo** [comment]
> I don't think we can do anything about that(locked chapter) except adding method to login which then you should pay to babel novel for the locked chapter using your account to login. I looking for that title and found it available on https://www.mtlnovel.com. but currently not supported by this app. i will add issue on this. It seems web to epub plugin has support for https://www.mtlnovel.com. you can try using that plugin for now.

Yeah, thx, fix

**Comment by dipu-bd** [comment]
comrademao was removed on request from the site owner

**Comment by dipu-bd** [comment]
I will remove locked chapters from appearing in TOC #221
