### ISSUE TITLE
Retry failed chapters

### ISSUE THREAD

**Issue by TunayAdaKaracan** [dipu-bd/lightnovel-crawler#2156]
Instead of skipping failed chapters, it should wait a few seconds or minutes and try to continue again. It is a big problem when you want to download a novel with a lot of chapters and pack them to a single file.

**Comment by zGadli** [comment]
In the `scraper.py` function `_process_request` takes in a `retry` parameter so that it can retry the GET/POST request.

**Comment by dipu-bd** [comment]
it retries a single time on failure now. any more than that is not optimal. the cause of failure could be rate limiting issues of the specific sites. we can configure the rate limiting using `self.init_executor`
