### ISSUE TITLE
Fix this source: re-library.com (novelupdates links only)

### ISSUE THREAD

**Issue by arromdee** [dipu-bd/lightnovel-crawler#2160]
Yes I searched the existing issues.

**Novel URL**:  https://www.novelupdates.com/series/after-genderswap-reincarnation-i-raised-the-strongest-player/    
**App Location**:  PIP 
**App Version**:   3.3.0  

lncrawl is not able to download anything from novelupdates.com that links to re-library.com, even though it is able to download *directly* from re-library.com.  If you try the above location you'll find that the first 11 chapters link to re-library but they link to an intro page with "click here to start reading".  So the resulting downloaded novel only contains the intro page and "click here to start reading".
lncrawl should check for this and follow the second link to the actual chapter.  (If it can't find the chapter link, of course you should still show the intro page.)

Using lncrawl directly on https://re-library.com/translations/strongest-player-cultivation/ works because that goes directly to the chapters.

**Comment by neoryd** [comment]
I think this is not the problem of the crawler, I checked the novelupdates url you give and there's no link there on every chapter.

![image](https://github.com/dipu-bd/lightnovel-crawler/assets/125942725/9aeaff4b-1de9-4675-88f0-f7e7c8b8fc47)

**Comment by arromdee** [comment]
Novelupdates has been changed to require logging in.  lncrawl is capable of handling this.

Once you're logged in, the links work, but the problem that I described happens for Re: Library links.

**Comment by CryZFix** [comment]
The problem you describe is related to the fact that with updatenovels crawler gets to the re-library page with a teaser of chapters, not with their list. Therefore, it captures only the text of the teaser and the proposal to start reading.

Please wait a bit, let's see what we can do.
