### ISSUE TITLE
Please add this source https://nyx-translation.com/

### ISSUE THREAD

**Issue by blarghbl123** [dipu-bd/lightnovel-crawler#2163]
- Language: English
- Supports Searching: No
- Contains Machine Translations: No
- Contains Manga/Manhua/Manhwa: No
- Has CloudFlare Protection: No

**Comment by camp00000** [comment]
Added here https://github.com/dipu-bd/lightnovel-crawler/pull/2268
If you're technically adept, feel free to locally install this branch or the dev branch once it's merged.
Otherwise wait for a release and use the official app / bots.
