### ISSUE TITLE
https://faqwiki.us/

### ISSUE THREAD

**Issue by Kulon1** [dipu-bd/lightnovel-crawler#2233]
- Language: English
- Supports Searching: Yes
- Contains Machine Translations: Yes
- Contains Manga/Manhua/Manhwa: No
- Has CloudFlare Protection: No

**Comment by camp00000** [comment]
I've made a pull request #2238 to add the source you requested, you can either wait a while for it to be merged & available in an update or if you're technically well-versed you can get it here right now https://github.com/camp00000/lightnovel-crawler/tree/faqwiki & run it on your machine locally.

**Comment by Kulon1** [comment]
some novel resulted in "no chapters found" like
- https://faqwiki.us/i-obtained-a-mythic-item/
i don't know if i should put this in a new issue as this pull isn't implemented in new update yet so i'm commenting here
