### ISSUE TITLE
readlightnovel.app source changed its domain to readlitenovel.com

### ISSUE THREAD

**Issue by zillafox** [dipu-bd/lightnovel-crawler#2236]
yes

## Let us know

**Novel URL**:  https://readlightnovel.app/the-beginning-after-the-end-535558/
**App Location**:  EXE
**App Version**:  lightnovel-crawler 3.4.0

## Describe this issue
website change its domain to https://readlitenovel.com/
![asd](https://github.com/dipu-bd/lightnovel-crawler/assets/24423458/da4da359-eba9-41ef-8265-7d148fb2f4c2)
![111](https://github.com/dipu-bd/lightnovel-crawler/assets/24423458/ffdc68b7-9b2f-4eb7-872b-649eb1bc283a)

**Comment by zillafox** [comment]
the current working website for this title now:

https://readlitenovel.com/the-beginning-after-the-end-535558

**Comment by camp00000** [comment]
@zillafox you can either wait for #2237 to be merged and then checkout dev (or wait for merge back into master).

Or you can clone my fork / branch directly or download the zip here https://github.com/camp00000/lightnovel-crawler/tree/readlitenovel


I was able to download the first 10 chapters as a test of the novel you linked without issue.
