### ISSUE TITLE
https://tw.m.ixdzs.com/ or https://www.aixdzs.com/ now redirects to https://ixdzs8.com/ please add support

### ISSUE THREAD

**Issue by abh966** [dipu-bd/lightnovel-crawler#2252]
**Novel URL**:     https://ixdzs8.com/
**App Location**:   any
**App Version**:   latest

## Describe this issue
 So these two sites now redirect to https://ixdzs8.com/ so please add the support

**Comment by camp00000** [comment]
They acutally redirect to https://ixdzs8.tw/ and https://ixdzs8.com/ respectively.
I fixed them in my pull request, not sure when that'll get merged but if you're technically adept, feel free to checkout my branch and use that for now, otherwise wait for the next update.
