### ISSUE TITLE
Enable login for babelnovel to access locked chapters

### ISSUE THREAD

**Issue by 3dycosmo** [dipu-bd/lightnovel-crawler#226]
Can not download all pages on https://babelnovel.com/books/weapon-master
Somehow always so only 50 chaps, nevertheless the novel should have 2279 chaps

- Novel URL: [https://babelnovel.com/books/weapon-master]
- App Version: [2.16.1]
- Package: [pip3]
- OS: [macOS 10.15.1]

![Screen Shot 2019-10-30 at 16 27 21](https://user-images.githubusercontent.com/4585442/67845604-58e74980-fb32-11e9-8c41-280b2833e484.png)

**Comment by yudilee** [comment]
That's because you need to login to get access to all the locked chapter.
lightnovel-crawler have yet implement login to it's babelnovel crawler. so
my suggestion is using using web-to-epub plugin in firefox or chrome. The
step for using this is:
1. install web to epub plugin on your firefox/chrome
2. browse to babelnovel and log on
3. access weapon master page
4. use web to epub to scrape it and generate epub

**Comment by 3dycosmo** [comment]
Thx
Webtoepub works and there are others link to
https://novelplanet.com/Novel/Weapon-Master

**Comment by dipu-bd** [comment]
I am searching for a simple solution to login and access the locked chapters. Until I find anything useful, locked chapters will not be available.

**Comment by dipu-bd** [comment]
I see two options to implement this feature. 

One way is to use a headless browser and try login with it. It will require users to download and install proper webdriver version matching with their current browser version. Adding selenium will further increase package size. 

Another is to maintain a browser extension. Users will login to babelnovel through browser, and the extension will then generate a file containing login config. The config file will then have to pass to console app.

Although first method will be hard for non-tech-savvy users, I do not see any other easy way.

**Comment by yudilee** [comment]
If possible I prefer second method because adding selenium because selenium
not fast enough unlike using request. And quite resource hungry.

**Comment by dipu-bd** [comment]
In second method, we need to maintain a browser extension, it will be a little troublesome in the long run. But I will try it out first to check how good it will be.

**Comment by mraleksander** [comment]
What about an option to add the cookie from the site
