### ISSUE TITLE
Fix this source

### ISSUE THREAD

**Issue by Sayurifighter** [dipu-bd/lightnovel-crawler#2261]
Yes

## Let us know

**Novel URL**:     <your novel url or query> https://chrysanthemumgarden.com/novel-tl/rsg/
**App Location**:    PIP | EXE | Discord | Telegram Discord
**App Version**:   x.y.z  Lightnovel Crawler

## Describe this issue

No chapters found. Website broke down a few days ago and when it's restored, it cannot work using the bot anymore.

![Screenshot 2024-02-08 114836](https://github.com/dipu-bd/lightnovel-crawler/assets/159401926/0d47360f-ccac-4ff4-b75d-75ffc49ccdaa)

**Comment by zGadli** [comment]
Just ran this URL by the latest version of the dev branch and it seems to be working just fine. You can try to install the latest version of lncrawl.exe and it should work just fine. You do however need to input a username and password for this website. So if the discord bot is not asking for it, then that's it's crashing.

**Comment by Sayurifighter** [comment]
Thanks for your fast reply. I don't owe my own PC, hence I can't download your app, which is why I'm using the bot. Thanks for trying anyway. Just for your info, the website was working fine with the bot just a few days ago. And yes it didn't ask for a password. Some of those novels doesn't need a password, or a log in to read them.

    On Thursday, 8 February 2024 at 04:44:32 pm SGT, zGadli ***@***.***> wrote:  
 
 


Just ran this URL by the latest version of the dev branch and it seems to be working just fine. You can try to install the latest version of lncrawl.exe and it should work just fine. You do however need to input a username and password for this website. So if the discord bot is not asking for it, then that's it's crashing.

**Comment by zGadli** [comment]
@Sayurifighter Your parents might have a laptop you can clone the repo there. If you want you can tell me your discord and I can send you the novel.

**Comment by Sayurifighter** [comment]
Haha I'm not that young, just broke as I have other priorities. I'll install the app once I get a new Pc in the future. Thanks for the offer.

**Comment by zGadli** [comment]
@Sayurifighter you might wanna close this issue.
