### ISSUE TITLE
Using lncrawl on 69xinshu has some issues

### ISSUE THREAD

**Issue by itsyahma** [dipu-bd/lightnovel-crawler#2262]
## Let us know

**Novel URL**:    https://www.69xinshu.com/book/10021708.htm-->
**App Location**:    PIP  -->
**App Version**:   3.4.2

**Comment by camp00000** [comment]
I fixed this in #2256, currently it's merged into dev but not yet back in master so not released yet.

If you're technically adept, feel free to check out / install the dev branch instead and use that.

Also please close the issue afterwards, thanks.
