### ISSUE TITLE
Fix this source libread.com

### ISSUE THREAD

**Issue by Jcoth** [dipu-bd/lightnovel-crawler#2271]
[Source added 11/30/23](https://github.com/dipu-bd/lightnovel-crawler/issues/2205)

**Novel URL**:    (https://libread.org/libread/invincible-novel-78469)
**App Location**:     EXE   
**App Version**:  3.4.0

## Describe this issue

! Sorry! I do not recognize this website yet.

![Capture](https://github.com/dipu-bd/lightnovel-crawler/assets/152507714/6ea9a838-f27b-4dde-9624-f797f491ffe5)

**Comment by camp00000** [comment]
New .org domain added here & also updated promo-removal [freewebnovel add new mirror](https://github.com/dipu-bd/lightnovel-crawler/commit/0aaf17045db7222d68a89f171fc46cd4ef665d21)
