### ISSUE TITLE
Bug: Fanfiction.net hardcoded to specific story

### ISSUE THREAD

**Issue by Veedrac** [dipu-bd/lightnovel-crawler#228]
https://github.com/dipu-bd/lightnovel-crawler/blob/9f0c03a16fd23864e3a51b91ae010b03e3c6eecd/src/spiders/fanfiction.py#L10

The 6291747 should be replaced with `self.novel_id` instead.

**Comment by dipu-bd** [comment]
will be available from v2.16.2
