### ISSUE TITLE
Babelnovel.com: get limited free novels

### ISSUE THREAD

**Issue by 43Highground** [dipu-bd/lightnovel-crawler#229]
In Babelnovel there are 4 free novels that come out everyday and when I want to download them I can only get like the first 50, can you change that.

**Comment by yudilee** [comment]
check issue #226

**Comment by dipu-bd** [comment]
@43Highground can you give me a novel name for which the some free chapters are available everyday? It will help in development.

**Comment by 43Highground** [comment]
@SudiptoChandra, You see everyday the free novels change at a certain time
on the website and it is impossible to predict which novels will be turned
into free novels for a limited time, but all I know is that for all free
novels during the certain day, all the chapters will be unlocked for 2 days
and then the system resets and chooses a new novel.

**Comment by dipu-bd** [comment]
Thanks for the info @43Highground I will be working on this issue soon. Hopefully version 2.17.0 will have a fix

**Comment by dipu-bd** [comment]
done. will be available from v2.17.0

**Comment by dipu-bd** [comment]
it requires login. need to solve #226 first
