### ISSUE TITLE
Discord Bot Error: Failed to upload file

### ISSUE THREAD

**Issue by Azrox01** [dipu-bd/lightnovel-crawler#2323]
The Discord bot is having this error.

Failed to upload file: Library Of Heaven S Path c1-2271.epub.
`Error: HTTPSConnectionPool(host='api.anonfiles.com', port=443): Max retries exceeded with url: /upload (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f26fc6f6560>: Failed to establish a new connection: [Errno -2] Name or service not known'))`

![Screenshot_20240402_191903_Discord](https://github.com/dipu-bd/lightnovel-crawler/assets/78945850/482f47e5-c4f9-4c31-9690-5ddb7c9ca3fb)

**Comment by dipu-bd** [comment]
anonfiles.com was shutdown sadly. We will be using GoFile from now on
