### ISSUE TITLE
cloudflare protection issues

### ISSUE THREAD

**Issue by Ateile** [dipu-bd/lightnovel-crawler#2326]
so recently, ive been tryin to download a novel but i cant, more like i couldnt because the cloudflare keeps making it error so it had me like RAHHHH
hope this gets attention

**Comment by dipu-bd** [comment]
can't do anything against cloudflare. we all feel the same pain too

**Comment by zGadli** [comment]
@dipu-bd maybe check this out: [nodriver](https://github.com/ultrafunkamsterdam/nodriver) this package claims to be able to bypass Cloudflare and claims to be "the official successor of the [Undetected-Chromedriver](https://github.com/ultrafunkamsterdam/undetected-chromedriver/) python package".

**Comment by dipu-bd** [comment]
@zGadli This one seems great. Have to test it. Thanks for bringing it to my attention.

**Comment by Af-50** [comment]
@zGadli how do i use nodrive with crawler to get the chapters?

**Comment by zGadli** [comment]
@Af-50 Checkout nodriver documentation. You can get the html of the whole page and parse it using bs4 .
