### ISSUE TITLE
search not working properly Fix this bug

### ISSUE THREAD

**Issue by PrincejiCoder** [dipu-bd/lightnovel-crawler#2334]
! Error: decoding to str: need a bytes-like object, NoneType found
<class 'TypeError'>
File "lncrawl\core\app.py", line 103, in search_novel
    search_novels(self)
  File "lncrawl\core\novel_search.py", line 125, in search_novels
    app.search_results = _combine_results(results)
  File "lncrawl\core\novel_search.py", line 46, in _combine_results
    key = slugify(item.title)
  File "slugify\slugify.py", line 115, in slugify

i am getting this  error for whatever i search, help we fix it please.

**Comment by LielinaH** [comment]
Having the same issue.

**Comment by zGadli** [comment]
If you can clone and use the dev branch this error does not occur.

**Comment by jlneder** [comment]
@zGadli When can we expect the dev branch to land on pypi?
I have a nix derivation with pypi and I really prefer not to change it.

**Comment by zGadli** [comment]
@jlneder  depends on @dipu-bd .
