### ISSUE TITLE
Integration with Flaresolverr

### ISSUE THREAD

**Issue by nixos-s** [dipu-bd/lightnovel-crawler#2339]
https://github.com/FlareSolverr/FlareSolverr

**Comment by zGadli** [comment]
The packages/dependencies used by them we are also using. They don't solve the corporate problem fully.

**Comment by zGadli** [comment]
The packages/dependencies used by them we are also using. They don't solve the corporate problem fully.

**Comment by nixos-s** [comment]
Closing this, I might raise a pr for this after looking at the implementation as its not working for me
