### ISSUE TITLE
Unable to Produce Epub due to 'Missing Cover Image'

### ISSUE THREAD

**Issue by odfu** [dipu-bd/lightnovel-crawler#2342]
**Novel URL**:     <https://chrysanthemumgarden.com/novel-tl/icy/>
**App Location**:    EXE  
**App Version**:   v3.5.1

## Describe this issue

I'm unable to produce an epub file due to the app not being to pull the cover image from the webpage. The chapters seem to be extracting properly due to json and web files for each chapters being produced properly. I was wondering if there was a way to produce the epub without the cover.

![Screenshot 2024-04-15 171840](https://github.com/dipu-bd/lightnovel-crawler/assets/167141676/67c62b9d-30de-4df4-959b-b4cb1e9592f1)
![Screenshot 2024-04-15 171825](https://github.com/dipu-bd/lightnovel-crawler/assets/167141676/b1e0d7dd-ecf3-46db-8036-c18def74b69e)

**Comment by zGadli** [comment]
@odfu I fixed this in the latest pull request. You can clone the dev branch and add my changes from the pr to get the epub. Otherwise you just have to wait for the next update.
