### ISSUE TITLE
A bug i think not sure?

### ISSUE THREAD

**Issue by motty4** [dipu-bd/lightnovel-crawler#2356]
A error message up saying like failed to get any result ..
here is the error message.

? Enter novel page url or query novel: I Will Kill The Author
Searching:  49%|████████████████████████████████▏                                | 140/283 [00:04<00:04, 31.20source/s]Failed to get any results, likely auth failure
Searching:  59%|██████████████████████████████████████▏                          | 166/283 [01:22<01:57,  1.00s/source]
 ! Error: decoding to str: need a bytes-like object, NoneType found
<class 'TypeError'>
File "lncrawl\core\app.py", line 103, in search_novel
    search_novels(self)
  File "lncrawl\core\novel_search.py", line 125, in search_novels
    app.search_results = _combine_results(results)
  File "lncrawl\core\novel_search.py", line 46, in _combine_results
    key = slugify(item.title)
  File "slugify\slugify.py", line 115, in slugify

Searching: 100%|█████████████████████████████████████████████████████████████████| 283/283 [01:22<00:00,  3.44source/s]
Press ENTER to exit...

**Comment by pj2at** [comment]
i have the same issue like this to be fixt so i can pull more books of the internet

**Comment by lukholo3015** [comment]
I also have this problem!

**Comment by lukholo3015** [comment]
FOUND SOLUTION!
Use url method (NOTE: Some sources still don't work)
================================================================================
                          [#] Lightnovel Crawler v3.5.0
                  https://github.com/dipu-bd/lightnovel-crawler
--------------------------------------------------------------------------------

-> Press  Ctrl + C  to exit

? Enter novel page url or query novel: https://boxnovel.com/novel/the-eternal-supreme/
Retrieving novel info...

[#] The Eternal Supreme
23 volumes and 2210 chapters found.
- https://boxnovel.com/novel/the-eternal-supreme/

? Enter output directory: C:\Users\Admin\Downloads\Lightnovels\boxnovel-com\The Eternal Supreme
? Which chapters to download? First 10 chapters
? 10 chapters selected Continue
? Which output formats to create? done (4 selections)
? How many files to generate? Pack everything into a single file
Chapters: 100%|██████████████████████████████████████████████████████████████████████| 10/10 [00:03<00:00,  3.19item/s]
  Images: 100%|████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  3.84item/s]
Created: The Eternal Supreme c1-10.epub
Created: 10 text files
* Task completed

? Open the output folder? Yes
Press ENTER to exit...
