### ISSUE TITLE
i am getting the following when trying to search

### ISSUE THREAD

**Issue by baqirNemer** [dipu-bd/lightnovel-crawler#2361]
<img width="980" alt="Screenshot 2024-04-29 at 21 08 47" src="https://github.com/dipu-bd/lightnovel-crawler/assets/88574788/82c9b627-5fbb-4e1d-a0b6-0a7ab865bdf2">

**Comment by baqirNemer** [comment]
every thing i enter for searchh give the same error

**Comment by zGadli** [comment]
@baqirNemer This fixed in the next version update.
