### ISSUE TITLE
Fix this source tl.rulate.ru

### ISSUE THREAD

**Issue by Terofe** [dipu-bd/lightnovel-crawler#2386]
## Let us know

**Novel URL**:    [ <your novel url or query> ](https://tl.rulate.ru/book/35913)https://tl.rulate.ru/book/35913
**App Location**:   EXE
**App Version**:   x.y.z  Last One

## Describe this issue

stopped working

<img width="853" alt="Снимок экрана 2024-05-27 193810" src="https://github.com/dipu-bd/lightnovel-crawler/assets/111743738/861c07f6-6cc1-46ec-b6dc-c64421cfb718">

**Comment by CryZFix** [comment]
@Terofe 
Пожалуйста, попробуйте снова. С сайтом вчера наблюдались проблемы, был временно включен CloudFlare.

**Comment by zGadli** [comment]
If it's working close the issue.
