### ISSUE TITLE
Anaconda: 'lncrawl' is a package and cannot be directly executed

### ISSUE THREAD

**Issue by ttpro1995** [dipu-bd/lightnovel-crawler#239]
`pip install --user -U lightnovel-crawler `

After restart terminal, and also restart PC, I cannot call `lightnovel-crawler` or `lncrawl`

It said 

`command not found: lncrawl`

**Comment by yudilee** [comment]
Can you give more detailed info of your system such as operating system, python version, etc

**Comment by dipu-bd** [comment]
@ttpro1995 Please run the following commands and send the output here:

1. `python --version`
2. `pip --version`
3. `python -m lncrawl --version`
4. `lncrawl --version`

**Comment by ttpro1995** [comment]
I use Digital Ocean, Ubuntu 16.04 LTS image, default firewall setting (I don't set anything related to network, firewall, just use it as is).

I install python via anaconda script. 

Welcome to Ubuntu 16.04.6 LTS (GNU/Linux 4.4.0-165-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  Get cloud support with Ubuntu Advantage Cloud Guest:
    http://www.ubuntu.com/business/services/cloud

53 packages can be updated.
1 update is a security update.


```
*** System restart required ***
Last login: Sun Nov 17 12:52:52 2019 from 171.232.249.43
➜  ~ python --version
Python 3.6.5 :: Anaconda, Inc.
➜  ~ pip --version
pip 19.3.1 from /home/tthien/miniconda3/lib/python3.6/site-packages/pip (python 3.6)
➜  ~ python -m lncrawl --version
/home/tthien/miniconda3/bin/python: No module named lncrawl.__main__; 'lncrawl' is a package and cannot be directly executed
➜  ~ lncrawl --version
zsh: command not found: lncrawl
➜  ~ hostname
thaithienme-20180210-s-1vcpu-2gb-sgp1-01
```

=======================
If I git clone whole git and install requirement, I can use the program just fine with `python . `

**Comment by ttpro1995** [comment]
This is how I install python 

https://docs.conda.io/en/latest/miniconda.html

**Comment by dipu-bd** [comment]
I have not tested this package with Anaconda python yet. I am configuring my environment to work with it and will fix this issue soon

**Comment by dipu-bd** [comment]
@ttpro1995 please run this and send the result:

```
➜  ~ export PATH=~/.local/bin:$PATH
➜  ~ lncrawl --version
```

**Comment by ttpro1995** [comment]
It seem work. 

```
Welcome to Ubuntu 16.04.6 LTS (GNU/Linux 4.4.0-165-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  Get cloud support with Ubuntu Advantage Cloud Guest:
    http://www.ubuntu.com/business/services/cloud

56 packages can be updated.
1 update is a security update.


*** System restart required ***
Last login: Wed Nov 20 07:11:15 2019 from 27.65.196.73
➜  ~ export PATH=~/.local/bin:$PATH
➜  ~ lncrawl --version
================================================================================
                           📒 Lightnovel Crawler 🍀2.16.2 
                  https://github.com/dipu-bd/lightnovel-crawler 
--------------------------------------------------------------------------------
Lightnovel Crawler 2.16.2
```

**Comment by dipu-bd** [comment]
It was because local pip packages put executable inside `~/.local/bin` directory. It must be added to PATH variable to access installed apps with `pip install --user`
