### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by sproid-i** [dipu-bd/lightnovel-crawler#2401]
When trying to install on Manjaro Linux it gives the error of needing to create Python venv as it needs a pip virtual environment. I was able to learn how to do so but now is giving error due to needing distutils package but I still haven't find a fix even after trying the recommendations to fix it. 
The Docker install also have errors and doesn't install but I guess that would be a separate issue.

**Comment by dipu-bd** [comment]
distutils has been discontinued in the latest python. try using earlier versions. i.e. python 3.8, 3.10 etc.
