### ISSUE TITLE
Fix:  https://www.webnovel.com

### ISSUE THREAD

**Issue by LordHarkon** [dipu-bd/lightnovel-crawler#241]
**Describe the bug**
After I select the novel I wish to download and finish setting everything and the program moves to download, it shows errors after errors. I tried the same thing with the discord bot that is on the official server of this crawler, and it worked just fine.

**Let us know**
- Novel URL: https://www.webnovel.com/book/11766562205519505
- App Version: 2.16.2
- Package: exe
- OS: Windows 10 PRO
![unknown](https://user-images.githubusercontent.com/12067203/69250538-7f8c2380-0bb8-11ea-9457-a929d1e83e41.png)

**Comment by yudilee** [comment]
This issue should have been fixed at 15 November but not yet release. @LordHarkon you can try using code from github instead of pip to try latest fix

**Comment by dipu-bd** [comment]
will be available in the next version

**Comment by dipu-bd** [comment]
it is fixed in 2.17.0
