### ISSUE TITLE
Fix babelnovel: no content in chapter body

### ISSUE THREAD

**Issue by 13kirito** [dipu-bd/lightnovel-crawler#242]
**Describe the bug**
Whenever i'm trying to download any Novel From Babelnovel, it shows that its downloaded completely in the crawler, but the content only have "Please update the Babelnovel app" in every chapter.

**Let us know**
- Novel URL: https://babelnovel.com/books/against-the-gods
- App Version: 2.16.2
- OS: Windows 8 and Android
![snap](https://user-images.githubusercontent.com/55593373/69480138-a9e51780-0e2a-11ea-8f6a-76600c0d5a41.jpg)

![Untitled](https://user-images.githubusercontent.com/55593373/69480029-cf255600-0e29-11ea-93ef-b9a6ef8d3edf.jpg)

**Comment by 13kirito** [comment]
Thanks, it fixed.

**Comment by shagunchandel** [comment]
can we download lightnovel from babelnovel app as i have premium so have more free capters in app then in web
