### ISSUE TITLE
novelplanet.com - maximum recursion depth exceeded.

### ISSUE THREAD

**Issue by greenaar** [dipu-bd/lightnovel-crawler#243]
**Describe the bug**
crawler fetches from novelplanet.com started failing 11/25/19.

Each download fails with "Error: maximum recursion depth exceeded".  This occurs not only with the current version, but with previously used, known good versions.

**Let us know**
- Novel URL: [https://novelplanet.com/Novel/Legend]
- App Version: [e.g. 2.16.2 (and all earlier versions]
- Package: [both pip and github builds tested.]
- OS: [Linux (bare and docker)]

**Comment by yudilee** [comment]
Problem with cfscrape, it happen to site that using cloudflare to protect it's site. Still waiting for cfscrape to be updated with latest fix. if we change cfscrape with cloudscraper i guess it will works. not only happened to novelplanet but also kisslightnovel

**Comment by greenaar** [comment]
Initial tests with 2.17.0 look good.  Novelplanet urls are now scraping properly.  Thank you.
