### ISSUE TITLE
Feature: Metadata only mode

### ISSUE THREAD

**Issue by Immortalin** [dipu-bd/lightnovel-crawler#2434]
Many [fiction downloaders](https://github.com/JimmXinu/FanFicFare) have a JSON metadata (e.g. title, author, chapter list, latest update date etc.) only mode which downloads the metadata without crawling the entire fiction. This is pretty important for integrating the downloader with third party [ebook managers](https://calibre-ebook.com/) as a plugin. Would it be possible to add support for this to lncrawler?

**Comment by dipu-bd** [comment]
it is already possible. check the commands available, and just download one chapter
