### ISSUE TITLE
https://www.machine-translation.org

### ISSUE THREAD

**Issue by 13kirito** [dipu-bd/lightnovel-crawler#248]
Can you Please try to Add "https://www.machine-translation.org" in the sources of the Crawler.
Thank you.

**Comment by yudilee** [comment]
it is already supported

**Comment by 13kirito** [comment]
But its Showing 
" ! Error: 'NoneType' object has no attribute 'text' "
![mt error](https://user-images.githubusercontent.com/55593373/70022454-48efd900-15ba-11ea-90ec-c78974e957a6.jpg)

**Comment by yudilee** [comment]
ok, fixed in pull request #249

**Comment by 13kirito** [comment]
I tried doing so on Bot, first it went till
" Your request has been received.I will generate book in "epub" format "
and stoped.
But now it only goes till " Reading novel info..." after taking URL input, then Stops.
![photo6285256193689626989](https://user-images.githubusercontent.com/55593373/70056914-43b67c80-1602-11ea-859e-e76877cd7156.jpg)

**Comment by yudilee** [comment]
Maybe bot being used by other user, you may try discord bot or other bot, I just try it and it worked, I will post link on general channel on discord channel

**Comment by 13kirito** [comment]
I tried it on discord bot just now, but its showing the same error as PIP

'NoneType' object has no attribute 'text' "

![discord issue](https://user-images.githubusercontent.com/55593373/70061493-6056b280-160a-11ea-8648-4f10ce1e923b.jpg)

**Comment by dipu-bd** [comment]
Both bots needs some refactoring... it is long overdue

**Comment by 13kirito** [comment]
Thanks for the effort guys..
