### ISSUE TITLE
https://www.mtlnovels.com/

### ISSUE THREAD

**Issue by WaifuSensei** [dipu-bd/lightnovel-crawler#2524]
Yes In have checked. Its not supported. Its a replacement of mtlnovel

 yes
 yes

- Language: English
- Supports Searching: Yes
- Contains Machine Translations: Yes
- Contains Manga/Manhua/Manhwa: No
- Has CloudFlare Protection: Yes

**Comment by change-n** [comment]
I was about to add the same request..

**Comment by WaifuSensei** [comment]
Hey,
mtlnovels source need to be added.
mtlnovel is there but it doesnt work now
Pls add mtlnovels
