### ISSUE TITLE
https://www.foxaholic.com/

### ISSUE THREAD

**Issue by aeggcl** [dipu-bd/lightnovel-crawler#2529]
Yes and it's still not supported

 Yes and unfortunately no one is requesting it

- Language: English
- Supports Searching: Yes
- Contains Machine Translations: Yes but mostly HTL
- Contains Manga/Manhua/Manhwa: No
- Has CloudFlare Protection: Yes

**Comment by dipu-bd** [comment]
https://github.com/dipu-bd/lightnovel-crawler/blob/master/sources/multi/foxaholic.py
