### ISSUE TITLE
Fix webnovel: chapter contents do not have space between paragraphs

### ISSUE THREAD

**Issue by Abyssrain421** [dipu-bd/lightnovel-crawler#253]
the epubs created from the site webnovel.com are poorly organized ,without any space between paragraphs. 

- Novel URL : [https://www.webnovel.com/book/7176992105000305/The-King's-Avatar]
- App Version: [2.17.0]
- Package: [EXE]
- OS: [Windows 10]

**Comment by dipu-bd** [comment]
This issue is confirmed. It will be fixed in the upcoming versions

**Comment by dipu-bd** [comment]
already pushed a fix. it will be up in the next version
