### ISSUE TITLE
Fix this source: Royal Road watermark is back

### ISSUE THREAD

**Issue by Xampa5** [dipu-bd/lightnovel-crawler#2531]
**App Version**:   3.7.4

## Describe this issue

Royal Road's 'invisible' text watermark is back. 

I download novels to read them offline on my oled smartphone screen and this permanent nagging in the middle of every chapter is infuriating and gets me out of the story.

I know it's supposed to be handled around line 80 of royalroad.py, but not how to fix it

`if style.endswith("{display:none;speak:never;}"):
                classnames.append(style[1:-27])`

EDIT: I've been able to fix it in post using Calibre editor. At least for the 8 novels I downloaded today, the only time there's a paragraph followed by a div, it's the nagging watermark. Which can be found with the regex
`<\/p><div>.*<\/div>`

Ctrl+F, Find: `<\/p><div>.*<\/div>`, Replace: `</p>`, Mode: Regex, All text files, click Replace all.

**Comment by zGadli** [comment]
Close issue. The issue will be resolved in the next update.
