### ISSUE TITLE
flying-lines crawler got no chapter

### ISSUE THREAD

**Issue by yudilee** [dipu-bd/lightnovel-crawler#255]
Problem :
when flying-lines crawler read page , it found 0 chapter

Info :
- Novel URL: [https://www.flying-lines.com/novel/longest-day-in-chang-an]
- App Version: [2.17.0]
- Package: [pip]
- OS: [Ubuntu 19.10]

**Comment by dipu-bd** [comment]
strange. I am getting correct amount of chapters too. check out the test-bot running on discord

**Comment by yudilee** [comment]
Ok, I will test it, thank you

**Comment by yudilee** [comment]
it worked, fresh git clone fixed it
