### ISSUE TITLE
Chapter Title from TOC and from chapter page is different

### ISSUE THREAD

**Issue by yudilee** [dipu-bd/lightnovel-crawler#26]
While converting scrapper to new style, i found that in the new style template chapter title is scrapped from TOC page not from chapter page. In old template the crawler get it from chapter page. In some source in toc they only write the title in number like in boxnovel and novel planet. I think we need to get chapter title from chapter page rather than from toc page.

**Comment by dipu-bd** [comment]
You can set the chapter title inside `download_chapter_body`. It will replace the title from TOC

```
    def download_chapter_body(self, chapter):
        '''Download body of a single chapter and return as clean html format.'''
        chapter['title'] = 'My Custom Chapter'
```

**Comment by yudilee** [comment]
it's works. Thank a lot
