### ISSUE TITLE
Only title is downloaded. No content.

### ISSUE THREAD

**Issue by derrickquan81** [dipu-bd/lightnovel-crawler#260]
Here's the novel: https://readnovelfull.com/trial-marriage-husband-need-to-work-hard.html
Output format: Any. I tried epub, mobi, pdf
For Chapter 1-792, only title is downloaded. The rest of the page is blank.
Chapter 793 onwards, it's downloaded fine.

**Comment by dipu-bd** [comment]
It is because 1-792 has different html content, which we did not handle while parsing the page. Thanks for reporting. It will be fixed in the next version

**Comment by dipu-bd** [comment]
fixed in the last commit
