### ISSUE TITLE
epubs created from webnovel have unrelated text

### ISSUE THREAD

**Issue by Abyssrain421** [dipu-bd/lightnovel-crawler#265]
in every chapthers downloaded from webnovel you can see the line [Find authorized novels in Webnovel，faster updates, better experience，Please click www.webnovel.com www.webnovel.com for visiting.]. This isn't at problem at reading time but i mention it so you are aware of it.

**Comment by dipu-bd** [comment]
thanks for reporting. I was not aware of it, and will fix it soon.

**Comment by Abyssrain421** [comment]
https://www.webnovel.com/book/7176992105000305/The-King's-Avatar
Chapther: 020
althought like i said any chapther have the same issue.

**Comment by dipu-bd** [comment]
I pushed a fix. It will be available after next release
