### ISSUE TITLE
wuxiacom – dialogue missing line breaks

### ISSUE THREAD

**Issue by mara42** [dipu-bd/lightnovel-crawler#273]
**Describe the bug**
Line breaks are removed from dialogue meaning, conversations between characters are all placed in a single line rather than a line per statement if the conversation is contained in the same paragraph but separated by `<br />`-tags, which are removed by `Crawler.clean_contents`.

E.g. 
"hello"
"hi" 

becomes:

"hello" "hi"

**to reproduce**

Download [example](https://www.wuxiaworld.com/novel/trash-of-the-counts-family/tcf-chapter-25) in any format to see that conversations are indeed rendered in the same line when the only separator would be a line break.

**potential fix**
Override the `clean_contents` function in `WuxiaComCrawler` to keep linebreaks in the text. 

```python
    def clean_contents(self, div):
        ...
        for tag in div.findAll(True):
            if isinstance(tag, Comment):
                tag.extract()   # Remove comments
            elif tag.name == 'br':
                continue
            elif tag.name in self.bad_tags:
                tag.extract()   # Remove bad tags
        ...
```

I'm a bit concerned this fix might cause issues elsewhere after seeing #87 and not being able to easily find what the actual problem/fix for that issue was. So in general, I don't know if this would cause issues elsewhere. 

**Let us know**
- Novel URL: [example](https://www.wuxiaworld.com/novel/trash-of-the-counts-family/tcf-chapter-25)
- App Version: 2.17.1
- Package: pip
- OS: macOS / irrelevant

**Comment by dipu-bd** [comment]
Thanks @mara42 I will fix this soon. Thumbs up for well organized description 👍
