### ISSUE TITLE
https://webnovelindonesia.com

### ISSUE THREAD

**Issue by sisterabigail12** [dipu-bd/lightnovel-crawler#274]
Please Add

https://translate.googleusercontent.com #275 
http://www.indonovels.net/ #278
https://gudangnovel.com/ #279
https://wbnovel.com #276 
https://webnovelindonesia.com #274

**Comment by dipu-bd** [comment]
it's been a difficult source. contents are so badly protected by cloudflare that I can not access them even on my browser.
