### ISSUE TITLE
[gravitytales] Fix novel info parsing

### ISSUE THREAD

**Issue by dipu-bd** [dipu-bd/lightnovel-crawler#282]
**Describe the bug**
The novel has 853 chapters, but app shows 1706

![image](https://user-images.githubusercontent.com/5158124/71421656-6ccca900-26a6-11ea-8e14-ab86bfe5e86d.png)

**Let us know**
- Novel URL: http://gravitytales.com/novel/shuras-wrath
- App Version: 2.17.1
- Package: pip

**Comment by diogenes895** [comment]
https://github.com/dipu-bd/lightnovel-crawler/pull/290 this should fix it
