### ISSUE TITLE
[webnovel.com] Chapters in "Table of Contents" isn't numbered.

### ISSUE THREAD

**Issue by Abyssrain421** [dipu-bd/lightnovel-crawler#285]
The Chapters in Table of Contents isn't numbered, this dificult the search of specific chapthers.
----
- Novel URL: [https://www.webnovel.com/book/7176992105000305/The-King's-Avatar]
- App Version: [2.18.0]
- Package: [exe]
- OS: [Windows 10]

**Comment by diogenes895** [comment]
please describe your problem a little bit more, cannot duplicate the bug.

**Comment by dipu-bd** [comment]
fixed by last commit
