### ISSUE TITLE
Blank Chapters | Wuxiaworld.site

### ISSUE THREAD

**Issue by SirGryphin** [dipu-bd/lightnovel-crawler#286]
When checking epub after download most of the chapters are blank with only the Chapters Title.

- Novel URL: https://wuxiaworld.site/novel/the-great-ruler/
- App Version: 2.18.0
- Package: pip
- OS: Windows 10

**Comment by diogenes895** [comment]
https://github.com/dipu-bd/lightnovel-crawler/pull/289 should fix this bug
