### ISSUE TITLE
https://exiledrebelsscanlations.com/

### ISSUE THREAD

**Issue by sumit7** [dipu-bd/lightnovel-crawler#287]
Hi, I love your script and have used it extensively for wuxiaworld novels like issth , renegade immortal, desolate era and a will eternal. Can you please add the following site:
https://exiledrebelsscanlations.com/gdc-chapter-126/

**Comment by sumit7** [comment]
Also I do not mind helping with the code if you give me some pointers as to what I need to do...

**Comment by dipu-bd** [comment]
@sumit7 Hello sumit. To add a new site, you can start by taking a look inside [src/spiders](https://github.com/dipu-bd/lightnovel-crawler/tree/master/src/spiders) directory. Checkout few files in there and you will get an idea. To enable your crawler add it to [src/spiders/__init__.py](https://github.com/dipu-bd/lightnovel-crawler/tree/master/src/spiders/__init__.py). 

You can ask on the discord server if you are stuck somewhere.

**Comment by SirGryphin** [comment]
Add to PR #591
