### ISSUE TITLE
Add Intro Page to generated book

### ISSUE THREAD

**Issue by yudilee** [dipu-bd/lightnovel-crawler#29]
Many of source book has synopsis and infor regarding the book. maybe we can crawled it and app intro pages to generated book, maybe adding info that this book generated using this script, etc

**Comment by dipu-bd** [comment]
Yeah. this is an interesting idea. The [utils/binding.py](https://github.com/dipu-bd/lightnovel-crawler/blob/master/lightnovel_crawler/utils/binding.py#L20) file is where you can start. Add the intro page before adding chapters. And make sure to add the page id in TOC.

I have become busy again. I don't know when I can give time.

**Comment by dipu-bd** [comment]
to make mobi files, kindlegen is necessary. it does not support anything other than linux, windows and mac
