### ISSUE TITLE
Feature request: Adding from a txt file

### ISSUE THREAD

**Issue by mraleksander** [dipu-bd/lightnovel-crawler#295]
Would it be possible to add novels from a .txt file in which there would be links to specific novels?

**Comment by dipu-bd** [comment]
I do not plan to give batch download feature in this app anytime soon. It is not possible to determine configuration for each individual novels in that way, and there are lots of alternatives to do that.

You can write a script providing novel links and `--suppress` option to auto-download them, e.g:

```
lncrawl --suppress  --single --force --format epub pdf --last 50 -s "https://litnet.com/en/book/candy-lips-1-b106232"
lncrawl --suppress  --single --force --format epub pdf --all -s "https://anythingnovel.com/novel/king-of-gods/"
```

Or, if you are using same configuration for all novels, a one liner for linux:

```
$ cat <filename.txt> | xargs lncrawl --suppress --single --force --format epub pdf --all -s 
```
