### ISSUE TITLE
Feature: save app config to user data folder

### ISSUE THREAD

**Issue by dipu-bd** [dipu-bd/lightnovel-crawler#306]
It should only be available for console bot.

What configs can be stored:
- latest download location
- last novel link request to resume download
- last selections for each prompts
- custom configuration settings (prompt user for values)

**Comment by mhussaincov** [comment]
hi there,
added to this could be a setting to select all chapters in the novel?
 and what format?
e.g the default is all, via the config file you could set web instead of all?
Majid

**Comment by mhussaincov** [comment]
web?


On 07/02/2020, mhussaincov <notifications@github.com> wrote:
> hi there,
> added to this could be a setting to select all chapters in the novel?
>  and what format?
> e.g the default is all, via the config file you could set web instead of
> all?
> Majid
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/dipu-bd/lightnovel-crawler/issues/306#issuecomment-583380764


-- 
kind regards,
Majid Hussain

**Comment by dipu-bd** [comment]
Should be possible after implementing #1001
