### ISSUE TITLE
Linebreaks removed, formatting broken in 2.19.1

### ISSUE THREAD

**Issue by q00u** [dipu-bd/lightnovel-crawler#312]
**Describe the bug**
Linebreaks in chapters are being lost, breaking formatting.

**Let us know**
- Novel URL: https://www.wuxiaworld.com/novel/the-novels-extra/tne-chapter-0
- App Version: 2.19.1
- Package: exe
- OS: Windows 7

First lines in chapter 0:

Raw: `<p>===<br>[Kim Suho]<br>17 – 27 years old in the story<br>A righteous, honest man and a hard-worker.`

Rendered as: 

> ===
> [Kim Suho]
> 17 – 27 years old in the story
> A righteous, honest man and a hard-worker.

lncrawl's json: `<p>===<br/>[Kim Suho]17 \u2013 27 years old in the storyA righteous, honest man and a hard-worker.`

(First `<br>` converted to `<br/>`, remaining missing!)

Rendered as:

> ===
> [Kim Suho]17 – 27 years old in the storyA righteous, honest man and a hard-worker.

Three lines became one line! Broken! There's not even a space between the lines. The words run together.

**Comment by q00u** [comment]
Related to #273 ?

**Comment by q00u** [comment]
Looking at [this commit](https://github.com/dipu-bd/lightnovel-crawler/commit/599581d552dccccc07b089a03674aa65d6f33746), it looks like subsequent linebreak tags after the first are being removed. In this case, the breaks are still being used to format the text though.

Is there a case where there are linebreak tags that aren't used?

**Comment by dipu-bd** [comment]
Using `p` looks better than `br` in pdf and some other formats. Thanks for finding out where the issue is. I will fix it later. Or you can make a pull request fixing it.

**Comment by q00u** [comment]
This is what I see in pdf:
![2020-01-11 00_37_28-The Novel s Extra c1-5 pdf -  The Novel s Extra c1-5  - SumatraPDF](https://user-images.githubusercontent.com/892302/72201637-00bea480-340b-11ea-9209-bf8bb0aacf60.png)

It does not look any better.

`p` and `br` serve different functions. `p` is for a block of text. `br` is for line-breaks _within_ that block of text (eg, poetry, or a Status screen in LitRPGs). This novel is using both tags as intended.

**Comment by dipu-bd** [comment]
I know that `br` is for line-breaks. I am just saying that separating paragraphs by `<br/><br/>` does not look as good as separating them using `p` tags in pdf. But removing `br` tags indiscriminately is an issue. I will work on it when I get free.
