### ISSUE TITLE
https://www.flying-lines.com/

### ISSUE THREAD

**Issue by zvaize** [dipu-bd/lightnovel-crawler#323]
**Describe the bug**
Program closing down with 500-something error. Both discord bots show "Unknown volume 2 for chapter 101" for this and several other novels. For the other novels, when error doesn't show up, both bots and app download empty (cover, title and author) or corrupted file (discord bot, less than 100 chapters novels). 

This problem started to occur only recently. Month or so ago Lightnovel Crawler bot downloaded from this site successfully. (book_smelting_bot showed 0 chapter count and didn't download at that time too). 

**Let us know**
- Novel URL: https://www.flying-lines.com/novel/the-villain-has-something-to-say
- App Version: 2.19.1
- Package: exe
- OS: Windows 7

**Comment by dipu-bd** [comment]
Since a while ago, they disabled get api and obfuscating content in post api. I have yet to figure out how to bypass it. For now the source is disabled
