### ISSUE TITLE
Styling Font and Novel Readablity

### ISSUE THREAD

**Issue by sureshchhatwani12** [dipu-bd/lightnovel-crawler#337]
This is just a suggestion whether there is a way to improve font styling when creating epub via json.

For example,

Han sen said <b>"Hi there"</b>

**Comment by dipu-bd** [comment]
At this moment, there is no way to set custom fonts and styles for epubs. It is recommended to use custom fonts and style in your epub reader instead of the epub file directly.

I may add this feature in v3 however.
