### ISSUE TITLE
json folders and files remain after web files are downloaded, that is to say that after html files are downloaded the json folder does not get removed

### ISSUE THREAD

**Issue by mhussaincov** [dipu-bd/lightnovel-crawler#341]
**Describe the bug**

hey there,
not sure if this is ment to be so or an error,
but the json folder remains in the directory where the novels are downloaded to,
note the json format was not sellected only web and single.
here is my command that I use.
lncrawl --format web --single --all -f -s
then the url of the novel,
I use this as an alias.
I hope this made sence,
Majid

**Let us know**
- Novel URL: [e.g. https://lnmtl.com/novel/against-the-gods]
novel url:
this happens with all url that i've tryed:

- App Version: [e.g. 2.7.8]
- Package: [can be exe, pip or`github]
latest from pip
- OS: [e.g. Windows 10]

OS debian testing

**Comment by dipu-bd** [comment]
`json` is a default. The app uses it to keep track of how many chapters were downloaded in case you want to resume your download later on. 

![image](https://user-images.githubusercontent.com/5158124/74842290-58c6c000-5354-11ea-854e-626368bcfd30.png)

**Comment by mhussaincov** [comment]
arr, I see :(
thanks for your swift responce, I was not aware.

On 19/02/2020, Sudipto Chandra <notifications@github.com> wrote:
> `json` is a default. The app uses it to keep track of how many chapters were
> downloaded in case you want to resume your download later on.
>
> ![image](https://user-images.githubusercontent.com/5158124/74842290-58c6c000-5354-11ea-854e-626368bcfd30.png)
>
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/dipu-bd/lightnovel-crawler/issues/341#issuecomment-588252561


-- 
kind regards,
Majid Hussain
