### ISSUE TITLE
No module named 'PIL'

### ISSUE THREAD

**Issue by greenaar** [dipu-bd/lightnovel-crawler#346]
**Describe the bug**

Latest version (2.19.3) fails to run properly, errors with the following:

 ❗ Error: No module named 'PIL'

This does not occur with 2.19.2 and earlier.

**Let us know**
- Novel URL: Any
- App Version: 2.19.3
- Package: pip
- OS: Linux

**Comment by dipu-bd** [comment]
I can not reproduce the issue. Please provide an example url?

**Comment by dipu-bd** [comment]
I found the issue, will push a fix soon

**Comment by dipu-bd** [comment]
fixed by #347

**Comment by greenaar** [comment]
Confirmed fixed. Thank you!

**Comment by greenaar** [comment]
Confirmed fixed. Thank you!
