### ISSUE TITLE
CairoSVG was not found

### ISSUE THREAD

**Issue by SirGryphin** [dipu-bd/lightnovel-crawler#349]
When I run lightnovel-crawler it shows the following:

```
CairoSVG was not found.Install it to generate random cover image:
    pip install cairosvg
? Enter novel page url or query novel:
```

Even though I've run the install command it still says not installed. When I run the install command it shows the following.

```
Requirement already satisfied: cairosvg in c:\python37\lib\site-packages (2.4.2)
Requirement already satisfied: defusedxml in c:\python37\lib\site-packages (from cairosvg) (0.6.0)
Requirement already satisfied: cssselect2 in c:\python37\lib\site-packages (from cairosvg) (0.2.1)
Requirement already satisfied: tinycss2 in c:\python37\lib\site-packages (from cairosvg) (1.0.2)
Requirement already satisfied: cairocffi in c:\python37\lib\site-packages (from cairosvg) (0.9.0)
Requirement already satisfied: pillow in c:\python37\lib\site-packages (from cairosvg) (6.2.2)
Requirement already satisfied: webencodings>=0.4 in c:\python37\lib\site-packages (from tinycss2->cairosvg) (0.5.1)
Requirement already satisfied: setuptools>=39.2.0 in c:\python37\lib\site-packages (from tinycss2->cairosvg) (41.0.1)
Requirement already satisfied: cffi>=1.1.0 in c:\python37\lib\site-packages (from cairocffi->cairosvg) (1.12.3)
Requirement already satisfied: pycparser in c:\python37\lib\site-packages (from cffi>=1.1.0->cairocffi->cairosvg) (2.19)
```

- App Version: 2.19.4
- Package: pip
- OS: Windows 10

**Comment by MMDF** [comment]
I believe this is a problem with cairosvg. Importing cairosvg results in an error and the lightnovel-crawler code is correct.

**Comment by drewbitt** [comment]
`pip install cairosvg` results in errors when using it.
```
OSError: no library called "cairo" was found
no library called "libcairo-2" was found
cannot load library 'libcairo.so': error 0x7e
cannot load library 'libcairo.2.dylib': error 0x7e
cannot load library 'libcairo-2.dll': error 0x7e
```
So install [cairo](https://www.cairographics.org/download/). On Windows you'll need to install GTK+.

**Comment by dipu-bd** [comment]
since 2.19.3 cairosvg is an optional dependency. you can choose to ignore the message.

**Comment by drewbitt** [comment]
The message could be improved. `pip install cairosvg` will not be sufficient for most installations of cairosvg unless for some reason you already have additional tools installed. As you can see at https://cairosvg.org/documentation/, there are actually even more requirements than I listed. I would just remove the pip message and link to the documentation.

**Comment by dipu-bd** [comment]
cairosvg is used to convert svg to png image. I am looking for alternative, because it is bloated and has too many dependencies to manage! I will replace cairosvg with something else in v3 or remove the need of it altogether.

**Comment by dipu-bd** [comment]
I have set this issue report under info. Normal console app won't show it anymore.
