### ISSUE TITLE
Add new sources

### ISSUE THREAD

**Issue by dipu-bd** [dipu-bd/lightnovel-crawler#35]
- ~https://www.novelupdates.com~
- [x] https://m.wuxiaworld.co/
- [x] https://m.wuxiaworld.com
- [x] https://www.romanticlovebooks.com
- [x] https://www.novelspread.com
- [x] http://fullnovel.live
- [x] https://webnovel.online
- [x] https://www.novelall.com
- [x] http://gravitytales.com
- [ ] http://moonbunnycafe.com/
- [x] http://novelfull.com
- [x] https://novelonlinefree.info
- [x] https://m.novelspread.com
- [ ] https://www.noveluniverse.com/
- [ ] http://zenithnovels.com
- [ ] https://anythingnovel.com
- [ ] https://m.chinesefantasynovels.com
- [x] http://www.machinenoveltranslation.com/
- [ ] https://comrademao.com/

**Comment by yudilee** [comment]
I think still so many novel source out there needed to be added such as 
https://www.novelall.com
http://gravitytales.com
moonbunnycafe
http://novelfull.com
https://novelonlinefree.info
https://m.novelspread.com
https://www.noveluniverse.com/
http://zenithnovels.com
https://anythingnovel.com
https://m.chinesefantasynovels.com
Maybe this holiday if I have some free time will try to add this

**Comment by dipu-bd** [comment]
That will be great! I am going to implement a novel search feature very soon

**Comment by yudilee** [comment]
https://comrademao.com/ is a good alternative for MTL Novel source.

**Comment by dipu-bd** [comment]
we should track each source in separate issues to make discussion easier
