### ISSUE TITLE
[machinetrans] The output will fail if any chapters are blank

### ISSUE THREAD

**Issue by gnations56** [dipu-bd/lightnovel-crawler#351]
**Describe the bug**
When downloading chapters for a novel on machinenoveltranslation, the output will fail if any chapters are blank

**Let us know**
- Novel URL: http://www.machinenoveltranslation.com/bringing-the-farm-to-live-in-another-world
- App Version: 2.19.4
- Package: pip
- OS: Windows 10

**Comment by dipu-bd** [comment]
Chapter should not be blank, but app should not stop working if some are blanks.   I will check it out

**Comment by dipu-bd** [comment]
Can you give a chapter number for which it reports blank chapter and stops?

**Comment by gnations56** [comment]
aise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Body is empty: http://www.machinenoveltranslation.com/bringing-the-farm-to-live-in-another-world/volume-71/chapter-7006
Body is empty: http://www.machinenoveltranslation.com/bringing-the-farm-to-live-in-another-world/volume-75/chapter-7417
Body is empty: http://www.machinenoveltranslation.com/bringing-the-farm-to-live-in-another-world/volume-80/chapter-7916
Body is empty: http://www.machinenoveltranslation.com/bringing-the-farm-to-live-in-another-world/volume-88/chapter-8730

**Comment by dipu-bd** [comment]
@gnations56 check the original sources. 7417, 7916, 8730 have not contents. 

I am not getting empty body for 7006

![image](https://user-images.githubusercontent.com/5158124/76182592-a9ad3400-61ef-11ea-86ed-50cfee7588f0.png)
