### ISSUE TITLE
bugg gravitytales.com adaptor first chapter is not the first chapter of the novel

### ISSUE THREAD

**Issue by mhussaincov** [dipu-bd/lightnovel-crawler#354]
**Describe the bug**

when downloading for exammple
http://gravitytales.com/novel/earths-core
using the output format as web and all novels as single book,
the first chapter is not the first chapter.
the first chapter from this adaptor would be for exammple chapter 300.

**Let us know**
- Novel URL: http://gravitytales.com/novel/earths-core[e.g. https://lnmtl.com/novel/against-the-gods]
- App Version: latest via pip[e.g. 2.7.8]
- Package: [can be exe, pip or`github]
- OS: debian unstable[e.g. Windows 10]

**Comment by mhussaincov** [comment]
the file name would be 00001.html but the contence of the file would be chapter 300 as an exammple.

**Comment by dipu-bd** [comment]
fixed by #355
