### ISSUE TITLE
Create a GUI

### ISSUE THREAD

**Issue by dipu-bd** [dipu-bd/lightnovel-crawler#36]
Here is an interesting project for this: https://github.com/ChrisKnott/Eel

**Comment by yudilee** [comment]
yesterday i watch this tutorial, python and electron. it's seems really good https://youtu.be/627VBkAhKTc

**Comment by dipu-bd** [comment]
This could introduce lots of work and potential bugs, while things are going smoothly without a GUI.

I am very reluctant to work on this issue.
