### ISSUE TITLE
[www.wuxiaworld.com] Error: 'NoneType' object has no attribute 'text'

### ISSUE THREAD

**Issue by SirGryphin** [dipu-bd/lightnovel-crawler#368]
When searching or using URL to download book it just gives me this error straight away. I don't know if it's because there site looks like a different layout or not.

`! Error: 'NoneType' object has no attribute 'text'`

- Novel URL: https://www.wuxiaworld.com/novel/overgeared
- App Version: 2.19.5
- Package: pip
- OS: Windows 10

**Comment by dipu-bd** [comment]
fixed in bot. will be available in the next version
