### ISSUE TITLE
http://thenovelfreeonline.com

### ISSUE THREAD

**Issue by dipu-bd** [dipu-bd/lightnovel-crawler#374]

**Comment by SirGryphin** [comment]
I was about to make a source file for this but noticed something weird. When you first load site it's "BoxNovel" mirror site, even when you click on a novel and select a chapter. So all you would have to do is add the domain name to boxnovel script and it should work.

Here the problem though. If you search for a novel on site, it takes you to "NovelCool" looking site, which means if you add this domain to that script it should work.

Problem is you can't do both, so I'm not sure what to do. I'm not sure if it just me this is happening to, if someone else can check it out please.

**Comment by dipu-bd** [comment]
This site sure is strange. Not only it is similar to boxnovel, event the logo is just the same. Only when searching the logo is changed. 

Original link: http://thenovelfreeonline.com/n/Tales-of-Demons-and-Gods
Boxnovel clone: http://thenovelfreeonline.com/nv/tales-of-demons-and-gods/z-493

Urls of these two types of design are different. We need check url first to determine the format of the site.
