### ISSUE TITLE
Windows Binary Does nothing after inputting the novel link

### ISSUE THREAD

**Issue by neoXwave** [dipu-bd/lightnovel-crawler#38]
the provided windows binary simply exits after entering the login information with your github link reference 
Checked on a fresh install of windows with no python or any other possible dependency installed but pure windows
![screenshot](https://user-images.githubusercontent.com/36124018/49488376-69346d00-f86c-11e8-8596-651fdb0afcbf.png)

UPDATE---
calling the exe with all the proper parameters instead of using the interactive menu seems to make it work absolutely fine

**Comment by dipu-bd** [comment]
The issue has been fixed in new version. You can get it here: https://goo.gl/sc4EZh
