### ISSUE TITLE
WuxiaWorld.co Broken

### ISSUE THREAD

**Issue by brandontruongg** [dipu-bd/lightnovel-crawler#408]
The `Crawler.absolute_url` method was changed and now wuxiaworld.co no longer works on the master branch (but still works in latest release version v2.20.0).

Happens because of this commit:
https://github.com/dipu-bd/lightnovel-crawler/commit/5596c00cac41c7d53aaeca04a5735410970be940#diff-6230cb1431a3e810272dde214d4270ce

It can be fixed without changing urljoin by adding `self.last_visited_url = self.home_url` at the beginning of the `search_novel` method in WuxiaCoCrawler and changing each chapter URL to `self.last_visited_url + '/' + a['href']` in the `read_novel_info` method (not an elegant fix but it works).

The `search_novel` method needs to be changed because `self.last_visited_url` will not get set and therefore it will join nothing and leave just the href tag as the novel url.

Each chapter URL is broken because urljoin joins "https://www.wuxiaworld.co/Library-of-Heaven-s-Path" and "1300359.html" as "https://www.wuxiaworld.co/1300359.html" instead of "https://www.wuxiaworld.co/Library-of-Heaven-s-Path/1300359.html".

Not sure if any other sources are broken because of this change but I noticed this one because I use this source quite often.

**Comment by dipu-bd** [comment]
#405

**Comment by dipu-bd** [comment]
I will fix it soon
