### ISSUE TITLE
cannot download from wordexerpt

### ISSUE THREAD

**Issue by SuKiN-a** [dipu-bd/lightnovel-crawler#409]
**Describe the bug**
wordexerpt ln's cannot be downloaded
error message : ! Error: 'NoneType' object has no attribute 'text'

**Let us know**
- Novel URL: https://wordexcerpt.com/series/seirei-gensouki/
- App Version: 2.20.0
- Package: pip
- OS: Windows 10

**Comment by dipu-bd** [comment]
already fixed it. wait for next version
