### ISSUE TITLE
LNMTL not working

### ISSUE THREAD

**Issue by Mentole** [dipu-bd/lightnovel-crawler#41]
LNMTL doesnt seem to be working. For example I trried the last 10 chapters of Martial God Asura and it came back with this:

"? Enter an url or novel name to find:  https://lnmtl.com/novel/martial-god-asura
Retrieving novel info...
NOVEL: Martial God Asura
? Which chapters to download?  Last 10 chapters
Getting cover image...
[KBody is empty: https://lnmtl.com/chapter/martial-god-asura-book-8-chapter-3623
[KBody is empty: https://lnmtl.com/chapter/martial-god-asura-book-8-chapter-3621
[KBody is empty: https://lnmtl.com/chapter/martial-god-asura-book-8-chapter-3624
[KBody is empty: https://lnmtl.com/chapter/martial-god-asura-book-8-chapter-3620
[KBody is empty: https://lnmtl.com/chapter/martial-god-asura-book-8-chapter-3622
[KBody is empty: https://lnmtl.com/chapter/martial-god-asura-book-8-chapter-3625
[KBody is empty: https://lnmtl.com/chapter/martial-god-asura-book-8-chapter-3628
[KBody is empty: https://lnmtl.com/chapter/martial-god-asura-book-8-chapter-3627
[KBody is empty: https://lnmtl.com/chapter/martial-god-asura-book-8-chapter-3626
[KBody is empty: https://lnmtl.com/chapter/martial-god-asura-book-8-chapter-3629
[KDownloading chapters |████████████████████████████████| 10/10
[?25hCreated: 10 text files
Created: 10 html files
Created: Martial God Asura.epub
Created: Martial God Asura.mobi"

And the files contain no text. I have been able to get other sites to work fine just not LNMTL.
I have been trying with and without the login option. If it works than can you please give an example of the commands to get it to work, thanks.

**Comment by dipu-bd** [comment]
You may have forgotten to log in.

To check if a novel requires to be logged in open any chapter. For example, in the first link: https://lnmtl.com/chapter/martial-god-asura-book-8-chapter-3623, there is a message like this:
```
Chapter visible only for logged in users of lnmtl
```

**Comment by dipu-bd** [comment]
Well, some recent change broke the login prompt for LNTML. I have fixed it. You can download the latest version and try again.

**Comment by Mentole** [comment]
That is what I am having trouble figuring out how do you log in?

**Comment by Mentole** [comment]
Never mind, updated from 2.6 to 2.6.2 and it works now,
