### ISSUE TITLE
https://www.fanmily.org/

### ISSUE THREAD

**Issue by HarmonLucifer** [dipu-bd/lightnovel-crawler#410]
Can you add https://www.fanmily.org/? Thanks

**Comment by SirGryphin** [comment]
Not sure if this is possible, each book on site links chapters from other sites. I've tried a couple and one links to novelspread and another to eratales.com.

If there is a certain book your better find which site fanmily is linking to and request that.

**Comment by dipu-bd** [comment]
it is kind of like https://www.novelupdates.com/ 
this type of site is not possible to add. closing this issue
