### ISSUE TITLE
❗ Error: 'NoneType' object is not iterable 

### ISSUE THREAD

**Issue by yudilee** [dipu-bd/lightnovel-crawler#42]
If choose "custom range index" or "custom range url" error message "❗ Error: 'NoneType' object is not iterable" generated

**Comment by dipu-bd** [comment]
It should have been fixed with [08fa20](https://github.com/dipu-bd/lightnovel-crawler/commit/08fa202a0b00dc854c9e4b59e2874cd27b617189)

Please check again and close this issue if it is resolved

**Comment by yudilee** [comment]
Yes, it fixed. Thanks
