### ISSUE TITLE
Error: 503 Server Error on novelplanet

### ISSUE THREAD

**Issue by kuro2052** [dipu-bd/lightnovel-crawler#424]
Lightnovel Crawler #2.20.0

? Enter novel page url or query novel:  https://novelplanet.com/Novel/World-s-Apocalypse-Online
Retrieving novel info...
https://novelplanet.com/Novel/World-s-Apocalypse-Online

 ! Error: 503 Server Error: Service Temporarily Unavailable for url: https://novelplanet.com/Novel/World-s-Apocalypse-Online

**Comment by greenaar** [comment]
This is reproducible for all novels available through novelplanet.com.  It *looks* like a cloudflare challenge which is gating connectivity.

**Comment by greenaar** [comment]
Updating the cloudscraper dependency to 1.2.34 (as you have already done in master)  corrects this issue.

**Comment by greenaar** [comment]
cloudscraper 1.2.36 was just released, and should be the fix for the latest cloudflare breakage.

**Comment by greenaar** [comment]
cloudscraper 1.2.36 against lightnovel-crawler 2.20.0 -- works.

**Comment by kuro2052** [comment]
> cloudscraper 1.2.36 against lightnovel-crawler 2.20.0 -- works.

Thank you for your comment. I upgraded cloudscraper to 1.2.36 and now novel planet is working fine.
Although I do get this error while upgrading it:
`ERROR: lightnovel-crawler 2.20.0 has requirement cloudscraper==1.2.26, but you'll have cloudscraper 1.2.36 which is incompatible.`
Future release of lncrawl will need to upgrade this dependency.
