### ISSUE TITLE
Fix this bug id.mtlnovel.com

### ISSUE THREAD

**Issue by avr2020** [dipu-bd/lightnovel-crawler#425]
**Describe the bug**
Blank No Story Craw from this Site

**Let us know**
- Novel URL: [https://id.mtlnovel.com/nine-realms-god-emperor/s]
- App Version: [Lightnovel Crawler #2.20.0]
- Package: [exe]
- OS: [Windows 10 Pro x64 Build 18363]

**Comment by SirGryphin** [comment]
I'm having same problem no body text. Just chapter/title on each page.

App Version: 2.20.0
Package: PIP
OS: Windows 10 Pro [10.0.18363 Build 18363]

**Comment by dipu-bd** [comment]
fixed
