### ISSUE TITLE
LNMTL chapter numbers are wrong

### ISSUE THREAD

**Issue by Mentole** [dipu-bd/lightnovel-crawler#43]
When I compile chapters from LNMTL the chapter numbers don't match what they actually are on the site. For instance I downloaded the last 10 chapters of Martial God Asura and it had them as 3123-3132 when they should be 3620-3629 which is what they are on the site. The chapters them selves match, just not the chapter numbers.

**Comment by dipu-bd** [comment]
It has been fixed in version 2.6.3
