### ISSUE TITLE
https://m.mywuxiaworld.com/

### ISSUE THREAD

**Issue by Arleng001** [dipu-bd/lightnovel-crawler#447]

**Comment by dipu-bd** [comment]
Similar: https://www.mywuxiaworld.com/

**Comment by Arleng001** [comment]
But https://www.mywuxiaworld.com/ is not includes in the supported sources

**Comment by dipu-bd** [comment]
@Arleng001 I guess you thought I am saying that this issue is a duplicate. But, I commented it here, in case I don't forget to add both of them. Sorry, I skipped putting any details in the comment.

Since, #449 and #447 are the same issues. Closing #449

**Comment by Arleng001** [comment]
Oh, that's alright. I was bit confused too. Thanks anyway
