### ISSUE TITLE
Support inline images inside chapter content

### ISSUE THREAD

**Issue by mchubby** [dipu-bd/lightnovel-crawler#456]
**Describe the bug**
Some RR chapters include images but are skipped by the parser (not in the result .json file)

Also mentioned by #89 (whose fix was incomplete, downloaded tables)

**Let us know**
- Novel URL: https://www.royalroad.com/fiction/21844
- App Version: 2.21.0
- Package: pip
- OS: Windows 10
- Chapter Index: 6 or 7
- Chapter Sample: https://www.royalroad.com/fiction/21844/i-am-going-to-die-in-this-game-like-dimension/chapter/315359/chapter-11-lets-get-physical

**Comment by drewbitt** [comment]
The example is no longer present in RR but most chapters in https://www.royalroad.com/fiction/21844 have images. Note that wattpad can have in-line photos as well, including animated gifs.

**Comment by dipu-bd** [comment]
aded by https://github.com/dipu-bd/lightnovel-crawler/commit/9fd21fecd5a4f28c7d1cb3fdf70875e51bcee55d
