### ISSUE TITLE
Crawler failing on specific chapter on novelfull.com

### ISSUE THREAD

**Issue by Charles-Isaac** [dipu-bd/lightnovel-crawler#459]
Crawler systematically fail on chapter 111 of https://novelfull.com/reborn-evolving-from-nothing.html

**Let us know**
- Novel URL: https://novelfull.com/reborn-evolving-from-nothing.html
- App Version: 2.21.0
- Package: exe
- OS: Windows 10

![image](https://user-images.githubusercontent.com/15947340/82163498-a41c3c00-9879-11ea-9a96-76cd47f99ff1.png)

**Comment by Charles-Isaac** [comment]
Can be fixed by commenting line 111 and 112 of novelfull.py

**Comment by dipu-bd** [comment]
@Charles-Isaac thanks for you precise information. I will fix it soon.

**Comment by kuwoyuki** [comment]
That was just an issue with the title and regex, it has "Volume" in the name
> Chapter 111 - Attack - End of Volume 4

It seems like trying to match those titles using regex is just a bad idea in general because of how inconsistent some of the sites can be.
