### ISSUE TITLE
readlightnovel.org - missing chapter title

### ISSUE THREAD

**Issue by AdrianSimionov** [dipu-bd/lightnovel-crawler#46]
readlightnovel.org crawler is not crawling the title of each chapter. Instead of the title, there is a "dot".

Tested on:
https://www.readlightnovel.org/full-marks-hidden-marriage-pick-up-a-son-get-a-free-husband

**Comment by dipu-bd** [comment]
The chapter contents in readlightnovel is not well-formatted. It is tricky to get the chapter title from the page content. However, I tried to extract chapter title whenever possible. The latest version has been published. It should be available in pypi shortly.
