### ISSUE TITLE
Need ability to do machine translation using google trans api while scrapping

### ISSUE THREAD

**Issue by yudilee** [dipu-bd/lightnovel-crawler#47]
I was wondering if we need to add function to make this script able to translate to chosen language from text scrapped from novel source, maybe we can use googletrans api to do this. Hoping this program can give surprise to reader from many different language.

**Comment by dipu-bd** [comment]
This is a nice suggestion. I would very much like to implement it. But sad thing is that there is a translation limit for [google api](https://cloud.google.com/translate/). It only allows translation of 500k characters for free. On average a chapter has 10-15k characters. That means at most 50 chapters can be translated for freely per one api-key. Implementing this feature is not worthwhile with free version google api.

**Comment by dipu-bd** [comment]
After searching for a bit, I found this one: https://github.com/ssut/py-googletrans
But I am not sure if I should use this to translate huge chunk of texts. Because this is not official api and there is a chance of getting your IP address banned by google.

**Comment by yudilee** [comment]
Thank for the info, i will try the api first and looking how to integrate it

**Comment by dipu-bd** [comment]
I am testing translator in `dev` branch:
https://github.com/dipu-bd/lightnovel-crawler/blob/dev/lncrawl/core/translator.py

**Comment by yudilee** [comment]
Just trying dev brach and i got error 

`Traceback (most recent call last):
  File "__main__.py", line 2, in <module>
    main()
  File "/home/yudi/Desktop/lightnovel-crawler-dev/lncrawl/__init__.py", line 9, in main
    start_app(crawler_list)
  File "/home/yudi/Desktop/lightnovel-crawler-dev/lncrawl/core/__init__.py", line 81, in start_app
    raise err
  File "/home/yudi/Desktop/lightnovel-crawler-dev/lncrawl/core/__init__.py", line 78, in start_app
    App.run(choice_list)
  File "/home/yudi/Desktop/lightnovel-crawler-dev/lncrawl/core/app.py", line 53, in run
    novel_info(app)
  File "/home/yudi/Desktop/lightnovel-crawler-dev/lncrawl/core/novel_info.py", line 61, in novel_info
    app.save_metadata()
  File "/home/yudi/Desktop/lightnovel-crawler-dev/lncrawl/core/app.py", line 85, in save_metadata
    } for vol in self.crawler.volumes
  File "/home/yudi/Desktop/lightnovel-crawler-dev/lncrawl/core/app.py", line 85, in <setcomp>
    } for vol in self.crawler.volumes
TypeError: unhashable type: 'dict'
`
it happened in function named save_metadata

**Comment by dipu-bd** [comment]
I fixed it

**Comment by yudilee** [comment]
After trial and error i presume that all available api for translation is limited and not suitable for this purpose.  I test googletrans and it give error 503 after translating approximately 8 chapter. 
`2019-01-19 10:06:24,190 [DEBUG] (urllib3.connectionpool)
https://translate.google.com:443 "GET /translate_a/single?client=t&sl=auto&tl=id&hl=id&dt=at&dt=bd&dt=ex&dt=ld&dt=md&dt=qca&dt=rw&dt=rm&dt=ss&dt=t&ie=UTF-8&oe=UTF-8&otf=1&ssel=0&tsel=0&tk=590255.1019428&q=Chapter+236+Bloodied+Saber HTTP/1.1" 503 2426
`
and when we got 503 error all next translation request gives the same error
I guess we need to close this issue. Thanks for adding it in dev branch. And pdf, html and docx output is really amazing, great work

**Comment by dipu-bd** [comment]
Ok. I am closng the issue
