### ISSUE TITLE
Support output format: Markdown

### ISSUE THREAD

**Issue by dipu-bd** [dipu-bd/lightnovel-crawler#484]

**Comment by kuwoyuki** [comment]
I'll take this one :eyes:

**Comment by dipu-bd** [comment]
@kuwoyuki how is it going? 

I have given some thought on this feature. But it seems supporting markdown is not possible easily. Since we are crawling in html format, we have two options open.
- If we do not want to use the html inside markdown, we have convert them to markdown format. This will be challenging. 
- If we decide to html in markdown, there is no point of supporting markdown format. we can just give the plain old html files.

Let me know, if you are still willing to work on this.
