### ISSUE TITLE
Readlightnovels issues

### ISSUE THREAD

**Issue by linus727** [dipu-bd/lightnovel-crawler#489]
Hey,
much appreciate ur work.
Could u add a Dark-Mode Progressing for the generation of the PDFs with black Background and white text?
Also generating from readlightnovels.org leaves a 
"
Sponsored Content

Remove Ads?
"
on each secound site; is it possible to delete such lines in the post-progressing?

**Comment by dipu-bd** [comment]
@linus727 DarkMode is considered for version 3. There won't be any support for it on version 2
