### ISSUE TITLE
[novelfull] Unknown volume 7 for chapter 1

### ISSUE THREAD

**Issue by dipu-bd** [dipu-bd/lightnovel-crawler#492]
**Describe the bug**
Unknown volume 7 for chapter 1

**Let us know**
- Novel URL:  http://novelfull.com/half-prince.html

**Comment by kuwoyuki** [comment]
this is fixed in dev branch https://github.com/dipu-bd/lightnovel-crawler/commit/2f9e34400fc4554c016078f604f2ae9b54398a28
