### ISSUE TITLE
Please change site from https://4scanlation.xyz/ to https://4scanlation.com/

### ISSUE THREAD

**Issue by fadhilm293** [dipu-bd/lightnovel-crawler#499]
because the site domain has changed

**Comment by dipu-bd** [comment]
Which version are you using?

In the latest version, it already is using https://4scanlation.com/

See here: https://github.com/dipu-bd/lightnovel-crawler/blob/master/lncrawl/sources/fourscanlation.py#L12

**Comment by dipu-bd** [comment]
@fadhilm293 please confirm and close this issue

**Comment by yudilee** [comment]
Tested it and confimed work
