### ISSUE TITLE
[mtlnovel] having error in detecting the entire chapters

### ISSUE THREAD

**Issue by 13kirito** [dipu-bd/lightnovel-crawler#529]
www.mtlnovel.com is having error in detecting the entire chapters. The novel on the site has about 3800 chapters but it's only detecting about 980 chapters.

- Novel URL: https://www.mtlnovel.com/nine-star-hegemon-body-art/
- App Version: 2.22.1
- Package: bot
- OS: windows 8.1 and BOT
![Screenshot_20200724-173705](https://user-images.githubusercontent.com/55593373/88389559-56213880-cdd4-11ea-8727-ff56e8223250.png)

**Comment by 13kirito** [comment]
Its the same with pip version.

**Comment by yudilee** [comment]
@13kirito can you try check is there any chapter link available for volume 1 on that link you've given? i think problem is on mtlnovel sites

**Comment by 13kirito** [comment]
@yudilee, it has 2 volumes on the website, but it's not showing any chapters on clicking the volume 1 list.
But the entire list is showing in the Chapter list:-
https://www.mtlnovel.com/nine-star-hegemon-body-art/chapter-list/

**Comment by 13kirito** [comment]
Ok, I just opened the downloaded files, the file names has chapters from 1-983, but inside it's from volume 2.
Sorry for the trouble.
