### ISSUE TITLE
Latest Versions Don't Work

### ISSUE THREAD

**Issue by SirGryphin** [dipu-bd/lightnovel-crawler#538]
So I've tried version 2.22.1 and 2.22.2 and both don't work says it doesn't recognize the website url I'm trying to download. So I had to uninstall and downgrade to version 2.22.0. Not sure if this is a known issue or not I saw a Test Bot post saying that it can't download either not sure what that means.

`! Sorry! I do not recognize this website yet.`

**Let us know**
- Novel URL: https://listnovel.com/novel/carefree-path-of-dreams/
- App Version: 2.22.1 and 2.22.2
- Package: pip
- OS: Windows 10 Pro 1909

**Comment by dipu-bd** [comment]
Checked the source. Did not find any reason why it is happening. My guess is that cloudscraper is throwing error during initialization. I pushed a fix for it in the dev branch and testing it.

**Comment by SirGryphin** [comment]
Whatever it was seems to be okay now. Everything is working fine again.
