### ISSUE TITLE
https://instadoses.com

### ISSUE THREAD

**Issue by SirGryphin** [dipu-bd/lightnovel-crawler#542]

**Comment by SirGryphin** [comment]
Created a source file from novelsrock.py and it works fine. Literally only had to replace novelsrock url with instadoses as sites use same script and layout. I also removed the search script because I didn't know if it would work and didn't want to get unknown errors.

Also another problem I've noticed with Instadoses is the site is really (really!) slow when loading pages, which means sometimes when using lncrawl it can have problem downloading some chapters and skipping them as blank.

Not sure how to submit it as a source file, I don't really use github often enough to know how to sync (or whatever it called) but to github as a commbit or whatever.

**Comment by dipu-bd** [comment]
Please upload the file here. I will add it

**Comment by dipu-bd** [comment]
I just added it.

https://github.com/dipu-bd/lightnovel-crawler/blob/dev/lncrawl/sources/instadoses.py
