### ISSUE TITLE
readlightnovel failed to create epub

### ISSUE THREAD

**Issue by SirGryphin** [dipu-bd/lightnovel-crawler#55]
This has happen multiple time now it fails to create everything except html and text files.

**Comment by yudilee** [comment]
Do you run executable for windows or run py file? If you run py file, can you run it using -lll or set. env to debug mode. If you can please post error message here.

**Comment by dipu-bd** [comment]
@SirGryphin Can you specify the novel name and the site from where you were trying to download?

@yudilee  `-lll` should work in the next release. It was temporarily disabled.

**Comment by SirGryphin** [comment]
This is the novel I tried.

https://www.readlightnovel.org/adorable-treasured-fox-divine-doctor-mother-overturning-the-heavens

**Comment by dipu-bd** [comment]
It happens to be the problem of long filenames. I used the novel title to create new files. In this case, the title is too long. And in windows very long filenames are not allowed. I will upload a fix tomorrow.

Although, you can make the current version working following this tutorial:
https://www.howtogeek.com/266621/how-to-make-windows-10-accept-file-paths-over-260-characters/

**Comment by dipu-bd** [comment]
This problem is fixed using `python-slugify`. Both folder and filenames are formatted and shortened using it.
