### ISSUE TITLE
[wbnovel] 'NoneType' object has no attribute 'contents'

### ISSUE THREAD

**Issue by mmfteam1** [dipu-bd/lightnovel-crawler#553]
Failed to get novel info.
'NoneType' object has no attribute 'contents'

https://wbnovel.com/novel/world-defying-dan-god/

**Comment by yudilee** [comment]
change line 21 into 
`for x in soup.select_one('.post-title h1').contents`

**Comment by mmfteam1** [comment]
worked, thanks
