### ISSUE TITLE
Source for light-novel.online is broken

### ISSUE THREAD

**Issue by fof300f** [dipu-bd/lightnovel-crawler#557]
The source for light-novel.online seems to be broken...
The bot reports that the body is empty while a visit confirms that the text is still there. Semms to be in need of an update. 
vgl. https://light-novel.online/my-vampire-system/chapter-230 
![2020-08-17_14-30-08_screen](https://user-images.githubusercontent.com/43810052/90396275-3c52d880-e096-11ea-836a-2bf2c7e13422.png)
![2020-08-17_14-30-58_screen](https://user-images.githubusercontent.com/43810052/90396308-4aa0f480-e096-11ea-872f-391f95483128.png)

**Comment by dipu-bd** [comment]
pagination seems to be broken in this site.
