### ISSUE TITLE
Discord bot closed when processing 

### ISSUE THREAD

**Issue by yudilee** [dipu-bd/lightnovel-crawler#56]
When i use discord bot. if i ask it to generate book for novel with more than 200 chapter it usually generate error like this 
`[ERROR] (asyncio)
Task was destroyed but it is pending!
task: <Task pending coro=<Client._run_event() running at /home/yudi/.local/lib/python3.6/site-packages/discord/client.py:307> wait_for=<Future pending cb=[BaseSelectorEventLoop._sock_connect_done(15)(), <TaskWakeupMethWrapper object at 0x7f52f3c029a8>()]>>
`
and bot will destroyed(closed). But i think this not happened with lightnovel-crawler bot  in readme link. Is there something i miss when deploying discord bot?

**Comment by yudilee** [comment]
I forgot to run server.sh. i think what makes discord bot keep running is server.sh

**Comment by dipu-bd** [comment]
No, the purpose of `server.sh` is to keep running discord bot as a background task. It has another issue. I will check it soon.

**Comment by dipu-bd** [comment]
I have upgraded discord bot. Now it should not hang up or stop suddenly.

Handling `asyncio` is complicated. It took 90% mana out of my body...

**Comment by yudilee** [comment]
Great work. I keep on fail while creating discord bot. Yours is really
good. 👍

**Comment by dipu-bd** [comment]
thanks for the compliment 😄
