### ISSUE TITLE
Order of the chapters is wrong

### ISSUE THREAD

**Issue by Esse78** [dipu-bd/lightnovel-crawler#569]
When you try to download from some sources(boxnovel, novelfull, ...) the order of the chapters is wrong.
For example in the first volume 1-50 and 151-200 and in the second volume 51-150

**Comment by dipu-bd** [comment]
@Esse78 Can you provide some novel links? It will be a great help to debug what is going wrong.

**Comment by Esse78** [comment]
Yep, sorry my fault.
Here the link:
Link: https://novelfull.com/library-of-heavens-path.html

**Comment by dipu-bd** [comment]
@Esse78 You also mentioned boxnovel. Do you have any sample link?

**Comment by Esse78** [comment]
boxnovel give me problems on I'm really a Superstar but today when I tried it was ok, so at the moment only novelfull give me problems

**Comment by dipu-bd** [comment]
related issues: #576 #537
