### ISSUE TITLE
Some chapters come out empty

### ISSUE THREAD

**Issue by SquadCraftFTW** [dipu-bd/lightnovel-crawler#576]
**Describe the bug**
When I downloaded chapters of Transcending the nine heavens from novel full, I realised that after halfway through the novel some chapters just said "Chapter X" without even a title. I checked the chapters on novelfull.com and there were no problems, I checked LNcrawler's JSON files after this, and the affected chapters were all less than 1kb in size. Deleting all the files and redoing has the same symptoms. 

In total, 18/1400 chapters are affected, but the last couple hundred chapters are increasingly worse.

**Let us know**
- Novel URL: https://novelfull.com/index.php/transcending-the-nine-heavens.html
- App Version: 2.22.5
- Package: exe
- OS: Windows 10

**Comment by dipu-bd** [comment]
@SquadCraftFTW Can you give chapter number of the few affected chapter? It will help us to debug faster

**Comment by SquadCraftFTW** [comment]
![ttnh chapters](https://user-images.githubusercontent.com/7716898/91718121-aeddb100-eb8a-11ea-9afb-cb3edaf954b6.png)
