### ISSUE TITLE
https://chrysanthemumgarden.com/

### ISSUE THREAD

**Issue by PleaseReadMe** [dipu-bd/lightnovel-crawler#577]
Please support this site!!

**Comment by SirGryphin** [comment]
Tried making source file but there is gibberish text in between paragraphs, when I tried and remove it the whole chapter disappears and a anti-stealing message appears. I tried multiple things and can't find a way around it.

**Comment by PleaseReadMe** [comment]
It's fine, thank you for your reply and time!

**Comment by dipu-bd** [comment]
this is very clever. they scrambled the text inside some paragraphs, and using a font to display them unscrambled!

here is the font:
https://chrysanthemumgarden.com/wp-content/themes/chrys-garden-generatepress/resources/css/fonts/OpenSans-Jumbld2.woff2

now, we can can either find a way to unscramble the text analyzing the font, or ship the font with epub. I will think about how to solve it later.

**Comment by PleaseReadMe** [comment]
How do I use the file?, Can I use it on Android?

**Comment by dipu-bd** [comment]
I am creating a crawler for it. you won't have to do anything. just use the bot or app you usually do.

**Comment by dipu-bd** [comment]
added by https://github.com/dipu-bd/lightnovel-crawler/commit/0d66e6

**Comment by PleaseReadMe** [comment]
God!! Thank you for adding chrysanthemumgarden!!! You are a blessing from
the Yaoi God!! Hahahahha!!

**Comment by PleaseReadMe** [comment]
Are there any gibberish parts?

**Comment by dipu-bd** [comment]
I have removed all gibberish I found. still if there is any report with a new issue

**Comment by PleaseReadMe** [comment]
Again thank you for creating the crawler!!

**Comment by PleaseReadMe** [comment]
Chrysanthemumgarden is still not supported.

**Comment by PleaseReadMe** [comment]
Please send a mail if it is already supported!!Thank you!!!

**Comment by dipu-bd** [comment]
add this project to your watch to get automated update. or, you can follow the discord server

![image](https://user-images.githubusercontent.com/5158124/92347238-47c37d80-f0f1-11ea-98e4-2933b486d7e8.png)
