### ISSUE TITLE
https://novelupdates.online/

### ISSUE THREAD

**Issue by SirGryphin** [dipu-bd/lightnovel-crawler#597]
Uses same layout (wordpress theme) as listnovel and other sites, The only problem is it uses pages to list chapters. I have no idea how to get all chapters from all pages.

**Comment by dipu-bd** [comment]
Pagination is a bit advanced. You can loop through all the pages one by one, or use ThreadPoolExecutor to process all pages simultaneously. See for examples: [novelfull.py](https://github.com/dipu-bd/lightnovel-crawler/blob/master/lncrawl/sources/novelfull.py)

You can leave it. I will work on this source it later.

**Comment by dipu-bd** [comment]
For this source, the total page count is not available. You have to loop through every page one by one. I can't remember if there is any such similar crawler.

**Comment by dipu-bd** [comment]
site is moved to https://wuxiaworldsite.co/ #840
