### ISSUE TITLE
https://lightnovelbastion.com/

### ISSUE THREAD

**Issue by SirGryphin** [dipu-bd/lightnovel-crawler#602]
I tried making a source and everything worked fine, search was working and it was finding chapters but as soon as I go to download it gets about 4 chapters the gives this error.

`! Error: 429 Client Error: Too Many Requests for url`

I've tried a few things, even changing user agent using requests but doesn't seem to work. I've included my source file if anyone know how to fix.

[lightnovelbastion.zip](https://github.com/dipu-bd/lightnovel-crawler/files/5208793/lightnovelbastion.zip)

**Comment by dipu-bd** [comment]
I will look into it
