### ISSUE TITLE
Telegram bot is not working.

### ISSUE THREAD

**Issue by ExaltedA** [dipu-bd/lightnovel-crawler#617]
**Describe the bug**
Telegram bot stopped responding.

**Comment by dipu-bd** [comment]
@yudilee can you check it?

**Comment by ExaltedA** [comment]
> @yudilee can you check it?

it started to work now, thx

**Comment by yudilee** [comment]
> @yudilee can you check it?

Sorry yesterday I change my server from raspberry pi to my working laptop because some hardware issue. Sorry for that
