### ISSUE TITLE
LNMTL login issues

### ISSUE THREAD

**Issue by Krabbyos** [dipu-bd/lightnovel-crawler#62]
I'm trying to download from this url https://lnmtl.com/novel/forty-millenniums-of-cultivation
This is one of the novels on the site that needs logging in to read.
exact command I'm using 
`lncrawl --login <username> <password> -s https://lnmtl.com/novel/forty-millenniums-of-cultivation`
username and password redacted for obvious reasons. 
followed onscreen prompts for output directory and selected option for first 10 chapters
"body is empty" for every chapter; the generated file are indeed empty
 `lncrawl --version` returns `2.7.6`

also i tried downloading the above novel by just going through prompts instead of using option flags and i never got prompted to login despite the novel requiring it.

**Comment by Mentole** [comment]
I am having the same issue with https://lnmtl.com/novel/martial-god-asura. I have used "custom range using URL" and it said "! Error: No chapters to download" every time. 

I than tried "Custom range using index" and downloaded the last chapter. It appeared to download the chapter but after checking it was empty.

**Comment by dipu-bd** [comment]
I fixed it and pushed a new release. Do a `pip install -U --user lightnovel-crawler`
