### ISSUE TITLE
Error cloudflare v2 challenge

### ISSUE THREAD

**Issue by GitJar** [dipu-bd/lightnovel-crawler#629]
I git this notif today in all source Oct 20, 2020

>❗ Error: Detected a Cloudflare version 2 challenge, This feature is not available in the opensource (free) version. 

> ---------------------------------------------

> 🔗  https://github.com/dipu-bd/lightnovel-crawler/issues

**Comment by GitJar** [comment]
Sample link that i want to crawl https://www.worldnovel.online/novel/m-e-m-o-r-i-z-e/


![Screenshot_20201020-194859_Quickstep](https://user-images.githubusercontent.com/6844738/96588031-536bac00-130d-11eb-9ecc-e4c6289c9c0b.png)

**Comment by mygithub-acct** [comment]
Found same issue on readlightnovel.org

                            Lightnovel Crawler #2.24.1
                  https://github.com/dipu-bd/lightnovel-crawler
--------------------------------------------------------------------------------

-> Press  Ctrl + C  to exit

Retrieving novel info...
https://www.readlightnovel.org/yobidasa-reta-satsuriku-sha

 ! Error: Detected a Cloudflare version 2 challenge, This feature is not available in the opensource (free) version.

**Comment by dipu-bd** [comment]
#707
