### ISSUE TITLE
Fix this bug

### ISSUE THREAD

**Issue by AncientCatz** [dipu-bd/lightnovel-crawler#657]
**Describe the bug**
![Screenshot_2020-10-29-20-35-58-405_com termux](https://user-images.githubusercontent.com/69200720/97581183-d932da00-1a26-11eb-9bfd-fe4200d922c5.jpg)
Download stops suddenly and a "Segmentation fault" notification appears.

**Let us know**
- Novel URL: https://novelringan.com/series/ore-no-kanojo-to-osananajimi-ga-shuraba-sugiru/
- App Version: 2.23.3
- Package: GitHub
- OS: Termux Android 10

**Comment by dipu-bd** [comment]
This app is meant to run on Desktop. By some luck (and with power of good hardware) it sometimes runs on mobile platform too. I have not tested it well on mobile, nor do I want to. It is a hassle to debug for mobile.
