### ISSUE TITLE
https://yarhou.net/

### ISSUE THREAD

**Issue by azurymous24** [dipu-bd/lightnovel-crawler#666]
There's a lot of novel here,too.

**Comment by SirGryphin** [comment]
I've tried making source file for this as it uses same layout as wuxiaworld.co (wuxiaco.py) but for some reason not matter what I try it just won't get body text of chapters. It either crashes with different errors or return blank chapters or chapters with "None" as text.

I've included my last try before giving up for now in attachment
[yarhou.zip](https://github.com/dipu-bd/lightnovel-crawler/files/5917697/yarhou.zip)

 if someone else wants to try.

**Comment by idMysteries** [comment]
@dipu-bd down?

**Comment by dipu-bd** [comment]
Maybe. Getting blank page.
