### ISSUE TITLE
https://morenovel.net/

### ISSUE THREAD

**Issue by budikesuma** [dipu-bd/lightnovel-crawler#669]
Dear Devs, 
Please add this source: https://morenovel.net/

Novel link: https://morenovel.net/novel/spirit-realm/

Thanks Devs.
*Sorry, i forgot to put a #Source's label.

**Comment by SirGryphin** [comment]
already requested. https://github.com/dipu-bd/lightnovel-crawler/issues/633

**Comment by SirGryphin** [comment]
Added to PR #752
