### ISSUE TITLE
zsh: command not found: lncrawl

### ISSUE THREAD

**Issue by trzident** [dipu-bd/lightnovel-crawler#672]
After I successfully downloaded lncrawler, I can't seem to activate it for some reason. I tried typing in lncrawl but it shows:

zsh: command not found: lncrawl.

Got the exact same thing with lightnovel-crawler:
zsh: command not found: lightnovel-crawler

I tried reinstalling:

Installing collected packages: urllib3
  Attempting uninstall: urllib3
    Found existing installation: urllib3 1.26.2
    Uninstalling urllib3-1.26.2:
      Successfully uninstalled urllib3-1.26.2
Successfully installed urllib3-1.25.11

I am currently on MacOS Catalina, Version 10.15.6

**Comment by dipu-bd** [comment]
related to #648
