### ISSUE TITLE
https://nobles.jp/

### ISSUE THREAD

**Issue by Darkmaster006** [dipu-bd/lightnovel-crawler#680]
Hello there! I was looking for the 'Flying Whale' novel (https://www.novelupdates.com/series/flying-whales-wonderful-life-i-who-has-fused-with-an-invincible-weapon-from-the-age-of-gods-will-build-a-city-on-my-back/) and found it here, the best version, in nobles.jp (https://nobles.jp/books/1). I hope this source can be added. Thank you.

**Comment by SirGryphin** [comment]
This site seems to of shutdown, I don't know if anyone else is having problems with it?

**Comment by Galunid** [comment]
@SirGryphin Doesn't seem to work for me either. Getting json with 403 forbidden

**Comment by dipu-bd** [comment]
Closing since it is no longer available.
