### ISSUE TITLE
Parallel Downloads?

### ISSUE THREAD

**Issue by Clickative** [dipu-bd/lightnovel-crawler#682]
Hey!
I was wondering if using the multithreading library, the downloads can happen in parallel?

**Comment by dipu-bd** [comment]
It already downloads the chapters in parallel

**Comment by Clickative** [comment]
Maybe add the option to change the number of threads?

**Comment by dipu-bd** [comment]
I don't think it do good to add option to change the number of threads. Most user will try to use a large number. Which may cause side-effect to the novel sites. Eventually they may block your IP. For example, `lnmtl` blocks IP for couple of minutes if concurrent request exceeds 3-4 per second.

If you are just a casual reader, I don't think current number of threads is going to be a problem. Can't you just wait a few minutes to get your novel you may need couple days to finish reading?
