### ISSUE TITLE
https://www.mtlreader.com/

### ISSUE THREAD

**Issue by CrwChampion** [dipu-bd/lightnovel-crawler#686]
This source is actually really good and has plenty of novels, yea its mtl but its decent.

**Comment by SirGryphin** [comment]
I've tried making source but I think it uses something to do with VueJS to load chapter content. I don't know how to make this work (I'm new to python) so if anyone else can help.

### Inspect/Elements
Chapter content once page fully loaded.
![elements](https://user-images.githubusercontent.com/36343615/122629230-59d84080-d0b3-11eb-8efb-7bb19e4a93a5.JPG)

### Source Code
Same chapter but in page source code
![source](https://user-images.githubusercontent.com/36343615/122629237-68265c80-d0b3-11eb-852e-d5eabd4fca06.JPG)

### JS
I searched for "reader-component" and found this in frontend.js
![js](https://user-images.githubusercontent.com/36343615/122629247-8b510c00-d0b3-11eb-988b-d53b090e7c13.JPG)
