### ISSUE TITLE
Error: cannot use a string pattern on a bytes-like object

### ISSUE THREAD

**Issue by d1st4nt** [dipu-bd/lightnovel-crawler#692]
Previously known good URL (multiple builds from this address) now failing.  It's important to note that this error and #691 seem to be related.  You bypass #691 by performing `lncrawl -s` but are faced with the issue below.

The example URL shown is just representative.  Seeing this across multiple sources, Webnovel, RoyalRoad, ReadWebNovels, etc.

![image](https://user-images.githubusercontent.com/1766581/102024708-a0925a00-3d61-11eb-8fd8-0bbb915ebca4.png)

- Novel URL: https://www.royalroad.com/fiction/32458/unlimited-power-the-arcane-path/
- App Version: 2.24.0
- Package: pip 20.3.1 (python 3.8.3)
- OS: Windows 10

**Comment by d1st4nt** [comment]
Just checked with 2.23.3, https://www.royalroad.com/fiction/32458/unlimited-power-the-arcane-path/ works

**Comment by dipu-bd** [comment]
related to #691
