### ISSUE TITLE
Source issue: LightNovelWorld

### ISSUE THREAD

**Issue by d1st4nt** [dipu-bd/lightnovel-crawler#695]
LightNovelWorld novels are producing `Error: list index out of range`, or `Error: 'NoneType' object is not subscriptable`, 

![image](https://user-images.githubusercontent.com/1766581/102032764-a56a0480-3d87-11eb-90f8-d5bcd1e1db42.png)

- Novel URL: 
-- `index out of range`: https://www.lightnovelworld.com/novel/supreme-magus-webnovel/
-- `object is not subscriptable`: https://www.lightnovelworld.com/novel/i-alone-level-up-solo-leveling-ln/, https://www.lightnovelworld.com/novel/a-returners-magic-should-be-special-wnovel/, https://www.lightnovelworld.com/novel/tsuki-ga-michibiku-isekai-douchuu
- App Version: 2.23.3
- Package: pip
- OS: Windows 10

**Comment by dipu-bd** [comment]
test with version 2.24.0

**Comment by d1st4nt** [comment]
> 
> 
> test with version 2.24.0

#691 #692 are preventing me from doing so.
