### ISSUE TITLE
add support for scraping metadata from www.wlnupdates.com and www.novelupdates.com

### ISSUE THREAD

**Issue by Emasoft** [dipu-bd/lightnovel-crawler#696]
Hi! Can you add support for scraping metadata from [https://www.wlnupdates.com/](https://www.wlnupdates.com/) or [novelupdates.com](https://www.novelupdates.com) and saving/updating those in the epubs ?
Thx!

**Comment by dipu-bd** [comment]
Metadata is not very necessary to read ebooks. I recommend find novels online first, then you use this app to read it offline. Batch generating epubs for any other purpose is not encouraged.
