### ISSUE TITLE
Wattpad Issue

### ISSUE THREAD

**Issue by GorgeousMhica** [dipu-bd/lightnovel-crawler#702]
Good day, I would like to report an issue regarding Wattpad. Whenever I try to download stories with lot of chapters or stories that are too long, the chapter's content are incomplete.  Hopefully, you can fix this issue. God bless, stay safe and happy holidays.

**Comment by dipu-bd** [comment]
@GorgeousMhica can you give some samples? e.g: links to novels and chapters with such issue

**Comment by GorgeousMhica** [comment]
Here is a sample link.
https://www.wattpad.com/story/3942069-he%27s-into-her-season-2

Each chapter are too long, and it fails to download the entire content of
the chapter. Thank you for noticing my request.
