### ISSUE TITLE
Not detecting any chapters in Woopread :3

### ISSUE THREAD

**Issue by Tetdesu** [dipu-bd/lightnovel-crawler#705]
![Screenshot_2020-12-29-23-42-39-199_com discord](https://user-images.githubusercontent.com/75838212/103296052-1e817280-49aa-11eb-9ba7-fa10eff7fca7.png)

**Comment by yudilee** [comment]
Just tested with latest code i can download and get all free chapters 
![image](https://user-images.githubusercontent.com/7065691/103861615-4b433180-50f0-11eb-8e3e-798ae0a4a368.png)

**Comment by Tetdesu** [comment]
Its now ok 😘 Thank you ☺️ 
![Screenshot_20210109_140557_com discord](https://user-images.githubusercontent.com/75838212/104084674-2bdd0d80-5284-11eb-9723-5669958aff38.jpg)
