### ISSUE TITLE
[wattpad] Issue capturing chapters

### ISSUE THREAD

**Issue by uazpeitia** [dipu-bd/lightnovel-crawler#706]
**Describe the bug**
Hi, when using even the last version, the captured wattpad stories are created with their chapter names changed with the name of the book. This happens in the table of contents and in every chapter.

table of contents repeating name of the book, instead of the true chapter name
![image](https://user-images.githubusercontent.com/6560734/103446646-56c2d280-4c82-11eb-9a27-9b80d0de3bf2.png)

Each of the chapters are changed too
![image](https://user-images.githubusercontent.com/6560734/103446663-8d005200-4c82-11eb-9723-42ff5add5a0e.png)

- Novel URL: all of wattpad stories, but this is the book from the captures: https://www.wattpad.com/story/150184209-g%C3%A9nesis-bajo-la-luna-los-cuadernos-del-lobo-i
- App Version: [e.g. 2.24.1]
- Package: exe
- OS: w10 last version

ty and happy new year!

**Comment by yudilee** [comment]
It can be fix by commenting line 64 in wattpad crawler source `#chapter['title'] = soup.select('h2')[0].get_text().strip()` like this in your case. I haven't tested it on another title.

**Comment by dipu-bd** [comment]
can you do a PR? @yudilee

**Comment by yudilee** [comment]
> can you do a PR? @yudilee 

OK. I will do PR for this

**Comment by uazpeitia** [comment]
Ty, so niceEl 12 feb. 2021 7:14, Sudipto Chandra <notifications@github.com> escribió:
Closed #706.
