### ISSUE TITLE
Comrademao

### ISSUE THREAD

**Issue by HarmonLucifer** [dipu-bd/lightnovel-crawler#707]
**Describe the bug**
Everytime I try to download something from comrademao it gives me this

 ! Error: Detected a Cloudflare version 2 challenge, This feature is not available in the opensource (free) version.

- Novel URL: [https://comrademao.com/novel/omg-i-became-a-turtle]
- App Version: [2.24.1]
- Package: [pip]
- OS: [Windows 10]

**Comment by dipu-bd** [comment]
This is not a bug related to this app. The above website is protected by reCaptcha enabled cloudflare service. We can not bypass these captcha using bots
