### ISSUE TITLE
https://newsite.kolnovel.com

### ISSUE THREAD

**Issue by abanoubmg4** [dipu-bd/lightnovel-crawler#708]
Please add any Arabic LN site for example this
1- https://newsite.kolnovel.com
2- https://www.rewayat.club/

**Comment by dipu-bd** [comment]
@abanoubmg4 please create seaparte issues for each source

**Comment by dipu-bd** [comment]
https://rewayat.club/ is already available. See #311

**Comment by SirGryphin** [comment]
Added PR #875
