### ISSUE TITLE
How to remove header

### ISSUE THREAD

**Issue by HarmonLucifer** [dipu-bd/lightnovel-crawler#710]
When downloading novels is there a way to remove this, or to not completely add it while downloading?

https://ibb.co/PcQ9hw9

**Comment by dipu-bd** [comment]
you can modify the code to remove header.

Remove the line here: https://github.com/dipu-bd/lightnovel-crawler/blob/master/lncrawl/binders/calibre.py#L72

**Comment by HarmonLucifer** [comment]
Alright thx, it worked
