### ISSUE TITLE
Novelfull only getting 50 chapters

### ISSUE THREAD

**Issue by SirGryphin** [dipu-bd/lightnovel-crawler#711]
I tried download a book from novelfull and it downloaded 600 chapters but when I checked them it was the first 50 chapters (page 1 on site) over and over.

**Let us know**
- Novel URL: https://novelfull.com/the-enchantress-of-medicine-with-the-heaven-defying-child-and-the-black-belly-father.html#:~:text=Ongoing-,The%20Enchantress%20of%20Medicine%2C%20with%20the%20Heaven%20Defying%20Child,and%20the%20Black%20Belly%20Father&text=In%20her%20past%20life%2C%20Jun,as%20someone%20else's%20stepping%20stone
- App Version: 2.24.1
- Package: pip
- OS: Windows 10

**Comment by yudilee** [comment]
I just tested it  using this link https://novelfull.com/the-enchantress-of-medicine-with-the-heaven-defying-child-and-the-black-belly-father.html and i got all 562 chapters of it

**Comment by dipu-bd** [comment]
@SirGryphin  Maybe the problem is with the extra fragments you are passing with your url

**Comment by SirGryphin** [comment]
Ahhh, yeah it was all the junk in url messing it up. Sorry about that, next time I will make sure to clean up the url. Thanks for the help.
