### ISSUE TITLE
https://ln.hako.re/

### ISSUE THREAD

**Issue by Uegou** [dipu-bd/lightnovel-crawler#713]
Would you please add this source to your app and also https://docln.net/ source. Thank you so much!

**Comment by quantrancse** [comment]
Hi, I've create a script to epub for https://ln.hako.re/ and https://docln.net/. Perhaps you need.
https://github.com/quantrancse/hako2epub

**Comment by Uegou** [comment]
It works! Thank you so much!
Cảm ơn bạn nhiều nhé!

**Comment by Uegou** [comment]
> Hi, I've create a script to epub for https://ln.hako.re/ and https://docln.net/. Perhaps you need.
> https://github.com/quantrancse/hako2epub

Your script download vol 1 completely but the others only have the title and summary section.

**Comment by quantrancse** [comment]
> > Hi, I've create a script to epub for https://ln.hako.re/ and https://docln.net/. Perhaps you need.
> > https://github.com/quantrancse/hako2epub
> 
> Your script download vol 1 completely but the others only have the title and summary section.

Create an issue on my repo so we can discuss.
