### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by HarmonLucifer** [dipu-bd/lightnovel-crawler#719]
What does this mean? 

 ! Error: 'data-echo'

**Comment by dipu-bd** [comment]
@HarmonLucifer can you provide more context? A full log along with your OS version and app version will do much help.

You should use this issue template to report this type of error:
https://github.com/dipu-bd/lightnovel-crawler/issues/new?assignees=&labels=bug&template=bug_report.md&title=Fix+this+bug
