### ISSUE TITLE
https://read.asianovel.com/series/the-boss-i-picked-up-all-fell-in-love-with-me

### ISSUE THREAD

**Issue by Xiaowang78** [dipu-bd/lightnovel-crawler#727]

**Comment by dipu-bd** [comment]
@Xiaowang78 can you add some description about this issue? 

I guess you wanted to report a bug. Go over here for reporting bugs: https://github.com/dipu-bd/lightnovel-crawler/issues/new?assignees=&labels=bug&template=bug_report.md&title=Fix+this+bug

**Comment by dipu-bd** [comment]
Duplicate of #734
