### ISSUE TITLE
getting chapter content from https://www.readnovelfull.com

### ISSUE THREAD

**Issue by AlenToma** [dipu-bd/lightnovel-crawler#728]
Getting chapter content from https://www.readnovelfull.com not working anymore

you could test this url `https://readnovelfull.com/hidden-marriage/chapter-1-7-months-pregnant.html`

**Comment by dipu-bd** [comment]
I have tested it. it is working. check if you are giving the right url. To download the above novel your should give this url:
`https://readnovelfull.com/hidden-marriage` , not the one you provided. The app only accepts novel page that has chapter list on it, not an url of a random chapter.
