### ISSUE TITLE
No longer works

### ISSUE THREAD

**Issue by Esortuei** [dipu-bd/lightnovel-crawler#744]
none of the links I entered in the crawler works

**Comment by dipu-bd** [comment]
Can you put more details? Sending some logs would be a great help.

**Comment by Esortuei** [comment]
Sorry when I tried again today it worked, don't know what happened..........
Here are the links I tried:
https://boxnovel.com/novel/absolute-great-teacher-boxnovel/
https://www.fanfiction.net/s/12592223/96/The-Spider
https://www.wuxiaworld.co/I-m-the-King-Of-Technology/
https://fastnovel.net/harry-potter-and-deathfalls-964/
The only one that's still not working is this one:
https://daonovel.com/novel/mages-are-too-op/

**Comment by dipu-bd** [comment]
probably it was internet connection issue
