### ISSUE TITLE
line break issue

### ISSUE THREAD

**Issue by SirGryphin** [dipu-bd/lightnovel-crawler#75]
I've noticed on NovelPlanet and maybe other I not to sure but I will get weird line breaks in middle of a sentence or paragraph. I've noticed it seem to happen if it's one of these to things.

1. There is a sentence with a italic word in the middle e.g

> Qi Nan Shan said, “You’re kidding! A Fu Heart from an Earth Dragon, once absorbed into his Innate Fu Book, will extend his life by at least 30 years. It would be difficult
> 
> _not_
> 
> to look younger!”

2. It also happens if there is a italic word with a comma as well like this.

> 12th thought to himself,
> 
> _Alright_, playing dumb are we? Two can play at this game……

I know I've said italic above but in the html file they are tag as `<em>` which to me looks like italic text but is actually classed as Emphasized, I can't tell the difference between them visually..

`<i>` - Italic text
`<em>` - Emphasized text

The book used as a example is this: https://novelplanet.com/Novel/Instant-Kill

**Comment by dipu-bd** [comment]
fixed
