### ISSUE TITLE
mtlnovel source url download fails

### ISSUE THREAD

**Issue by trgtboyz** [dipu-bd/lightnovel-crawler#754]
**Describe the bug**
Not able to use lncrawl with mtlnovel source url. Getting an error 
Error: Detected a Cloudflare version 2 challenge, This feature is not available in the opensource (free) version

**Let us know**
- Novel URL: https://www.mtlnovel.com/infinite-fusion-system-of-the-heavens-and-worlds
- App Version: 2.24.3 
- Package:pip
- OS:  Windows 10
![image](https://user-images.githubusercontent.com/1019529/107738584-f6b55680-6d2c-11eb-9f71-b1da5d7fd0a7.png)

**Comment by dipu-bd** [comment]
this can not be solved. #629 #422
