### ISSUE TITLE
Error api-ms-win-crt-heap-l1-1-0.dll

### ISSUE THREAD

**Issue by Flwk** [dipu-bd/lightnovel-crawler#763]
Hello

When i try to open the program, i have this error : api-ms-win-crt-heap-l1-1-0.dll missing. I'm on Windows 7. 

Best regards,

**Comment by dipu-bd** [comment]
Download and install Visual C++ Redistributable

https://www.microsoft.com/en-ph/download/details.aspx?id=48145&751be11f-ede8-5a0c-058c-2ee190a24fa6=True

**Comment by Flwk** [comment]
it's already installed on my laptop
Le jeu. 18 févr. 2021 à 05:45, Sudipto Chandra <notifications@github.com> a
écrit :

**Comment by dipu-bd** [comment]
which version is installed? Visual C++ Redistributable for Visual Studio 2015?

the missing dll is from the above version. so, if it is installed properly, it should work.

**Comment by Flwk** [comment]
[image: image.png]

I have all these version installed

>

**Comment by dipu-bd** [comment]
I suggest uninstall both 32- and 64-bit versions, install them again, and restart your PC.

**Comment by Flwk** [comment]
I'v upgraded my laptop to W10 and it work now.

I think the issue is from the OS
