### ISSUE TITLE
Error on wuxiaworld.co crawler

### ISSUE THREAD

**Issue by yudilee** [dipu-bd/lightnovel-crawler#77]
The problem occured is :

When using wuxiaworld.co as source get 2 error while downloading chapter
1. Error on link url  like this `Invalid URL '1521084.html': No schema supplied. Perhaps you meant http://1521084.html?`
2. Get body is empty ( I think it has some connection with self.extract_content function)

More info:
- Novel URL: https://www.wuxiaworld.co/Reincarnation-Of-The-Strongest-Sword-God/
- App Version: [e.g. 2.7.8]
- Package: [github]
- OS: ubuntu 18.10

**Comment by dipu-bd** [comment]
fixed.
