### ISSUE TITLE
Unable to download from wattpad.com

### ISSUE THREAD

**Issue by credulous2skeptic** [dipu-bd/lightnovel-crawler#775]
**Describe the bug**
Tried downloading books from wattpad.com using book_smelting_bot on discord. The books that were generated had no chapters except for the book info. Tried with two different links and both gave the same result.

**Let us know**
- Novel URL: 

- https://www.wattpad.com/story/191073105-❀-blackpink-블랙핑크-lyrics-book-romanized-english

https://www.wattpad.com/story/210879040-fearless

- App Version: discord
- Package: discord book_smelting_bot
- OS: Android 11

**Comment by credulous2skeptic** [comment]
[blackpink_beulraegpingkeu_lyrics_book_romanized_c1-36.pdf](https://github.com/dipu-bd/lightnovel-crawler/files/6066301/blackpink_beulraegpingkeu_lyrics_book_romanized_c1-36.pdf)

This is the book that was generated.

**Comment by dipu-bd** [comment]
have you tried other bots?

**Comment by credulous2skeptic** [comment]
No. I'll try now and report.

**Comment by credulous2skeptic** [comment]
Just tried lightnovel crawler and it works perfectly...

**Comment by dipu-bd** [comment]
the other bot is not updated I guess
