### ISSUE TITLE
Wuxiaco gets stuck while downloading

### ISSUE THREAD

**Issue by dipu-bd** [dipu-bd/lightnovel-crawler#78]
**Describe the bug**
wuxia.co gets stuck while downloading. maybe the site is blocking consecutive requests.

**Let us know**
- Novel URL: https://www.wuxiaworld.co/Reincarnation-Of-The-Strongest-Sword-God/
- App Version: 2.7.9
- Package: pip
- OS: Linux Mint

**Comment by yudilee** [comment]
Hi Sudipto, 

I try generate book several times using the same novel url as above and no problem occured. Also it works great now with wuxiaworld.co.

**Comment by dipu-bd** [comment]
It may not be a bug then. wuxiaco does not work well when internet speed is slow. I have faced same issue for some other sources as well. maybe I should add a `retry` option on download failure.

**Comment by yudilee** [comment]
Agree.

**Comment by dipu-bd** [comment]
there are some complications in adding `retry` option. as it is not causing too much problem for most cases, closing this issue now
