### ISSUE TITLE
https://www.lightnovelpub.com

### ISSUE THREAD

**Issue by Void099** [dipu-bd/lightnovel-crawler#787]
Lightnovelworld changed to lightnovelpub

**Comment by budikesuma** [comment]
Dear devs,
Please update source address from: https://www.lightnovelworld.com/
To:
https://www.lightnovelpub.com/

**Comment by budikesuma** [comment]
@dipu-bd 
I have used the lightnovel-crawler bot to scrape the https://www.lightnovelpub.com/ site and found the watermarks quite annoying as there are at least 6 watermarks per chapter. After checked with the html code are: random classes of  <p class='......'> Random Words </p>
is there any way to remove those marks?

HTML CODE view:

<p class='sfopvd'>This content is taken from light/nove/lwo/rld/[.]com</p>

<p class='srcttw'>Follow current novels on l/ightno/velpub[.]com</p>

<p class='dnthwg'>Visit lightno/velpub[.]com for the best novel reading experience</p>

<p class='dnthwg'>This content is taken from /lightnovelpub[.]com</p>

<p class='dnthwg'>Follow current novels on /li/ghtnovelpub//[.]com</p>

**Comment by budikesuma** [comment]
Html page

**Comment by budikesuma** [comment]
This is sample novel link
