### ISSUE TITLE
Fix this bug: watermarks of lightnovelpub.com

### ISSUE THREAD

**Issue by budikesuma** [dipu-bd/lightnovel-crawler#794]
**Describe the bug**
@dipu-bd 

I have used the lightnovel-crawler bot to scrape the https://www.lightnovelpub.com/ site and found the watermarks quite annoying as there are at least 6 watermarks per chapter. After checked with the html code are: random classes of 
`<p class='......'>` Random Words `</p>` 

is there any way to remove those marks?

HTML CODE view:

 `<p class='sfopvd'>This content is taken from light/nove/lwo/rld/[.]com</p>`

`<p class='srcttw'>Follow current novels on l/ightno/velpub[.]com</p>`

`<p class='dnthwg'>Visit lightno/velpub[.]com for the best novel reading experience</p>`

`<p class='dnthwg'>This content is taken from /lightnovelpub[.]com</p>`

`<p class='dnthwg'>Follow current novels on /li/ghtnovelpub//[.]com</p>` 

**Let us know**
- Novel URL: This is sample novel chapter link:
[Detail page of Immortal and Martial Dual Cultivation!](https://www.lightnovelpub.com/novel/immortal-and-martial-dual-cultivation-17031322)

[Chapter 1 link!](https://www.lightnovelpub.com/novel/immortal-and-martial-dual-cultivation-17031322/chapter-1)

- App Version: [discord]
- Package: [lightnovel-crawler bot]
- OS: [android]

**Comment by Galunid** [comment]
@budikesuma Should be fixed, you can try running the dev version

**Comment by budikesuma** [comment]
@dipu-bd 
Thanks a lot devs.
I got pretty good results after I tried it on the bot.  Looks like the colon (:) is removed from the chapter titles?  It would be better if it was replaced by a hyphen (-) or (  &#8211; ).

**Comment by budikesuma** [comment]
@dipu-bd 
termux android hasn't updated the lightnovelpub.com source yet.

**Comment by dipu-bd** [comment]
it will available in the next version

**Comment by budikesuma** [comment]
@dipu-bd 
Can you open this thread again?
I found new ads template from this source: 
`<i><strong>`random texts from lightnovelpub.com`</strong></i>`

**Comment by dipu-bd** [comment]
@budikesuma create a new issue for that
