### ISSUE TITLE
[Feature Request] Login for webnovel dot com

### ISSUE THREAD

**Issue by Chibba-dev** [dipu-bd/lightnovel-crawler#802]
Hey, I'd like to archive my novels I unlocked or the daily free one. So for that a login is needed otherwise it only grabs free chaps.
A login like for lnmtl. =)

**Comment by dipu-bd** [comment]
webnovel login is tricky. it has google bot verification check and 2-factor authentication. this type of login is not easily possible to handle in scripts.

**Comment by nightcrawler123** [comment]
Hey, could we not add cookie support we set curl-based cookies from chrome and then this may be implementable!!!
