### ISSUE TITLE
New version Not Opening

### ISSUE THREAD

**Issue by DDC4321** [dipu-bd/lightnovel-crawler#808]
Not sure what i am doing wrong.
Old version 2.24.1 is opening but 2.24.5
![Error](https://user-images.githubusercontent.com/82085224/113833834-66bee680-978a-11eb-935a-58a7a94480e4.png)
.5

i have done the pip install --user -U lightnovel-crawler to get new version of pyp but still error

**Comment by dipu-bd** [comment]
did you upgrade `pip`? what is your `pip` version?

**Comment by DDC4321** [comment]
i checked with pip --version
and got pip 21.0.1 python 3.9 is this correct ?

**Comment by dipu-bd** [comment]
it is correct. I will check what is going wrong.
