### ISSUE TITLE
Feature Request: More generate book size options

### ISSUE THREAD

**Issue by jango1985** [dipu-bd/lightnovel-crawler#811]
I want to be able to have something in between everything and a 100 chapters.  For me 100 chapters is always too small but entire novels can be 2000 chapters sometimes which is too big.  I would like a 400-500 chapter type option.  I don't really like cluttering up my ebook reader with 20+ books of the same story.  Or just an option in a config file to set book size.  A config file for all my default choices would be nice as well.

**Comment by Von07** [comment]
I think there's already a feature on this in which you can indicate an index of range

**Comment by dipu-bd** [comment]
Use `--range` or `--chapter` etc. check `lncrawl --help` for details
