### ISSUE TITLE
Update README.md about "B3. Running the bot"

### ISSUE THREAD

**Issue by damare01** [dipu-bd/lightnovel-crawler#815]
**Describe the bug**
When I enter this "pip3 install --user -r bot_requirements.txt" in the termenal, I will get this `ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'bot_requirements.txt'`
**Let us know**
- Novel URL: 
- App Version: 
- Package: zip
- OS: Windows

**Comment by dipu-bd** [comment]
README is not updated with the latest changes. `bot_requirements.txt` file is renamed to `requirements-dev.txt`. 
Let's keep this issue open to update the README

**Comment by damare01** [comment]
ohh and also please see the issue #813
