### ISSUE TITLE
Fix this bug

### ISSUE THREAD

**Issue by malkova90** [dipu-bd/lightnovel-crawler#821]
**Describe the bug**

**Let us know**
- Novel URL: [e.g. https://lnmtl.com/novel/against-the-gods]
- App Version: [e.g. 2.7.8]
- Package: [can be exe, pip or`github]
- OS: [e.g. Windows 10]
[routerlogin](https://routerlogin.pro)

**Comment by dipu-bd** [comment]
please give more details about the bug.
