### ISSUE TITLE
[Feature Request] Download progress report from discord and telegram bots

### ISSUE THREAD

**Issue by damare01** [dipu-bd/lightnovel-crawler#835]
The title says all...please!

**Comment by dipu-bd** [comment]
there already is a download  progress indicator. it is hidden if you pass the `-l` flags

**Comment by PleaseReadMe** [comment]
In the discord bot?

**Comment by dipu-bd** [comment]
do you want to see download progress indicator on discord bot or console app?

**Comment by damare01** [comment]
in the discord and telegram please

**Comment by dipu-bd** [comment]
added download progress status in discord bot.
won't modify telegram bot for now.

**Comment by damare01** [comment]
thank you!
