### ISSUE TITLE
Fix this bug Problem crawling on wuxiaworld.site

### ISSUE THREAD

**Issue by damare01** [dipu-bd/lightnovel-crawler#837]
**Describe the bug**
when trying to request a novel from wuxiaworld.site I would get this error
`'NoneType' object has no attribute 'contents'
`
or

`It has 0 volumes and 0 chapters.`

**Let us know**
- Novel URL: [https://wuxiaworld.site/novel/astral-pet-store-webnovel-freeread/](https://wuxiaworld.site/novel/astral-pet-store-webnovel-freeread/)
- App Version:
- Package: github
- OS: Windows 10

**Comment by yudilee** [comment]
Wuxiaworld.site using cloudflare to prevent scrapping. Cloudcraper library
free cannot be used to access and scrape content from it's site. So I think
no feasible solution at the moment.
