### ISSUE TITLE
[Suggestion] Let us test using a local crawler file

### ISSUE THREAD

**Issue by sak3r** [dipu-bd/lightnovel-crawler#843]
Hi

I came across lncrawler trying to crawl a specific site that wasnt on the supported list, after following the instructions made a new source and want to test it.
It would be nice to supply the source as an argument instead of having to run from source or make a pull request

I asked about it on discord and found my solution, run from source I just think it could be a simpler process to have more people do it.

**Comment by Galunid** [comment]
Pretty sure you could do something like `python . -s "URL to novel"`.

**Comment by dipu-bd** [comment]
You can pass the local source file name using `--crawler` option. e.g. `lncrawl --crawler wattpad.py --list-sources`
