### ISSUE TITLE
https://www.hotmtlnovel.xyz/

### ISSUE THREAD

**Issue by neoryd** [dipu-bd/lightnovel-crawler#847]
![Screenshot (378)](https://user-images.githubusercontent.com/72436418/117269077-8bda6e00-ae8a-11eb-967d-f4ee08930672.png)
Hello plss add this source, i try to make a crawler for this site but i failed. I don't know why, there's also a novel need to login to read. plsss make a crawler for this source. thank you.

**Comment by SirGryphin** [comment]
I had same problem when trying to create source file. 

It gives me this error:
` ! Error: Detected a Cloudflare version 2 challenge, This feature is not available in the opensource (free) version. `

Also like you said some novels needs you to be logged in to read/download. I have no idea how to even start coding a site login. I've include my file in case
[hotmtlnovel.zip](https://github.com/dipu-bd/lightnovel-crawler/files/6495343/hotmtlnovel.zip)
 someone wants to take a look.

**Comment by dipu-bd** [comment]
i will take a look into it

**Comment by dipu-bd** [comment]
I have checked, it is not possible to bypass it.  so, this site will go into rejected source list
