### ISSUE TITLE
exiledrebelsscanlations: 400 client error

### ISSUE THREAD

**Issue by Xiaowang78** [dipu-bd/lightnovel-crawler#864]
I was making epub from the supported source called 'exiledrebelsscanlations'. But the bot said the source was not supported. And when I tried again it said 400 client error. This is not the first time. Every time I tried with bots it always show like that. I thought I was putting the wrong url before but my friend can do it fine. It only happen to me. So what's with this bug? 

- Novel URL: https://exiledrebelsscanlations.com/novels/delicious-food-got-me-famous-across-the-galaxy/

**Comment by SirGryphin** [comment]
Fixed and submitted PR #865
