### ISSUE TITLE
WUXIAWORLD.SITE ['NoneType' object has no attribute 'contents']

### ISSUE THREAD

**Issue by damare01** [dipu-bd/lightnovel-crawler#867]
**Describe the bug**
When I request a novel from wuxiaworld.site to the discord bot I would get this `'NoneType' object has no attribute 'contents'`

**Let us know**
- Novel URL: [https://wuxiaworld.site/novel/fey-evolution-merchant-novel/](https://wuxiaworld.site/novel/fey-evolution-merchant-novel/)
- App Version: 
- Package: book_smelting_bot
- OS: [Windows 10]

**Comment by dipu-bd** [comment]
@damare01 please give a sample novel url link. also mention the version if you are using the python package or the bot name

**Comment by damare01** [comment]
> @damare01 please give a sample novel url link. also mention the version if you are using the python package or the bot name

done

**Comment by damare01** [comment]
how do I update the version of the bot?
