### ISSUE TITLE
wuxiaworld.com - Line break Issue

### ISSUE THREAD

**Issue by SirGryphin** [dipu-bd/lightnovel-crawler#87]
I had similar problem with another supported site, posted here: https://github.com/dipu-bd/lightnovel-crawler/issues/75 and you fixed it.

I get line breaks after and before `<em>` and `<i>` tags.

- Novel URL: https://www.wuxiaworld.com/novel/perfect-world
- App Version: 2.7.12
- Package: pip
- OS: Windows 10

**Comment by dipu-bd** [comment]
it has been fixed. update to the latest version
