### ISSUE TITLE
Blogspot and Wordpress

### ISSUE THREAD

**Issue by SirGryphin** [dipu-bd/lightnovel-crawler#870]
Hi @dipu-bd 

I was just wondering, I've came across a lot of small translators who own blogspot or wordpress blog sites like this one:

https://zelskytranslations.wordpress.com/novels/reverend-insanity/index/

Where they just create an index/table of content and post chapters. I can make source files for them easily but I was thinking wouldn't it be easier to create one source file for all blogspots sites? and just add the url to the  base url like this:

```
base_url = [
        'https://zelskytranslations.wordpress.com',
        'http://ecwebnovel.blogspot.com/',
    ]
```

Instead of making loads of source files, or would it be more of a pain in the long run? I know each blog and site are slightly different, not sure if it would cause more errors than helping.

**Comment by dipu-bd** [comment]
You are right. I also think if two sources are the same, we should use only one crawler class for them. It is easier to maintain. 

The name of the class doesn't matter. Only the `base_url` part is important.

**Comment by SirGryphin** [comment]
When I have some free time, I will have to go through sources see which ones are the same and combined them or just do it from this point onwards whichever is better for you.

**Comment by dipu-bd** [comment]
well, leave the current sources as it is. they are working fine. you can just do it with new sources.
