### ISSUE TITLE
Error: 'charmap' codec can't decode byte 0x90

### ISSUE THREAD

**Issue by alextiniuc** [dipu-bd/lightnovel-crawler#882]
Whenever querying for a novel with the query function the message 

! Error: 'charmap' codec can't decode byte 0x90 in position 10915: character maps to <undefined>

appears. 
This occurs every time,  doesn't matter the text input whether it is a single word or a collection of words

**Let us know**
- Novel URL: unavailabe ( used in search function )
- App Version: 2.26.3
- Package: exe
- OS: Windows 10
![Capture](https://user-images.githubusercontent.com/8968740/119092531-35873680-ba17-11eb-9427-ab915647eef3.PNG)

after using -ll to check which of the sites were producing the error removing 1stkissnovel.love and noveltrench.com seemed to have fixed the issue

**Comment by s4hilsingh** [comment]
Also having the same issue at different number multiple times and once in a while it completes the search somehow.

**Comment by dipu-bd** [comment]
It is encoding issue. I could not reproduce this issue on my pc. However I pushed a probable fix.

**Comment by dipu-bd** [comment]
I could finally reproduce the issue with the `lncrawl.exe` build. This does not happen when running as a pip package.

**Comment by dipu-bd** [comment]
Building exe locally does not produce this issue. I was building the exe using appveyor automation . I don't know yet what is being different there.

**Comment by pkwok** [comment]
I have this issue too! Happens with every command

**Comment by dipu-bd** [comment]
building exe using github workflow works. this issue is solved now
