### ISSUE TITLE
Discord bot can't be added

### ISSUE THREAD

**Issue by l3td33r** [dipu-bd/lightnovel-crawler#884]
**Describe the bug**
Discord site says that the bot hasn't been verified or it requests access to wrong privileges.
Using this link: https://discordapp.com/oauth2/authorize?client_id=537526751170002946&permissions=51264&scope=bot

**Comment by dipu-bd** [comment]
The bot has exceeded the 100 servers limit. It can not be added to any new server now. Join our discord server to use the bot. If you want to add a bot to your server, ask other bot owners for invite link. You can also host your own discord bot.
