### ISSUE TITLE
Empty chapter list on foxaholic

### ISSUE THREAD

**Issue by lunevale** [dipu-bd/lightnovel-crawler#889]
**Describe the bug**
I used the discord bot to download the epub for a novel on Foxaholic but the bot failed to get novel info.

**Let us know**
- Novel URL: https://foxaholic.com/novel/how-to-survive-as-a-villain/
- App Version: Lightnovel Crawler bot on discord
![IMG_20210526_222319](https://user-images.githubusercontent.com/73226124/119677096-00dd0a00-be71-11eb-82bf-8f9aaafb8a47.jpg)

**Comment by SirGryphin** [comment]
I think this is caused by change in domain from https://foxaholic.com to https://www.foxaholic.com, also with the pip version it was giving a too many requests error when trying to get chapters. I've fixed it and submitted changes.

PR 897

**Comment by dipu-bd** [comment]
TODO: check if chapter contents are okay before new release
