### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by drewbitt** [dipu-bd/lightnovel-crawler#89]
I was curious if there were plans to support in-text images. Text-only limits the tool to series that do not use images, while some RR series in particular often use images for stat screens which makes those series unreadable for now (and I didn't even realize I was missing stat screens for a long time!).

**Comment by yudilee** [comment]
Can you give me example of book link in RR that has image for stat screen, i will look into it .

**Comment by yudilee** [comment]
I think i found it, stat posted using table, i miss that while scrapping. soon i will pull request, you can test output using telegram bot on readme

**Comment by dipu-bd** [comment]
it is available in version 2.7.14
