### ISSUE TITLE
Worldnovel.online body is empty

### ISSUE THREAD

**Issue by fadhilm293** [dipu-bd/lightnovel-crawler#890]
**Describe the bug**
the contents of the novel is empty
![Screenshot_2021-05-26-23-13-16-981_com termux](https://user-images.githubusercontent.com/22253628/119695942-e3ac3980-be78-11eb-96f1-41d1ddc4a1ae.jpg)

**Let us know**
- Novel URL: https://www.worldnovel.online/novel/ed-id/
- App Version: 2.26.3
- Package: pip
- OS: Android

**Comment by SirGryphin** [comment]
I did a test before trying to fix it, but I get a completely different error. Before I can do anything I comes up with:

` ! Error: Detected a Cloudflare version 2 challenge, This feature is not available in the opensource (free) version.`

**Comment by dipu-bd** [comment]
Closing this issue since this is not solvable
