### ISSUE TITLE
charmap error

### ISSUE THREAD

**Issue by mygithub-acct** [dipu-bd/lightnovel-crawler#892]
Error message after searching for a novel title
Error: 'charmap' codec can't decode byte 0x90 in position 10915: character maps to <undefined>
![image](https://user-images.githubusercontent.com/71422313/120056703-5851c480-c081-11eb-8e67-2313b3595c16.png)
![image](https://user-images.githubusercontent.com/71422313/120071709-d8087f00-c0d3-11eb-8b31-eb399ace0596.png)
Looks like related to foxaholic.com source. Issue happened when I run the lncrawler.exe downloaded from the site. If I run lncrawl from pip install it still can progress to the next step after experiencing the error.

**Comment by dipu-bd** [comment]
similar to #882
