### ISSUE TITLE
Empty chapter content on pdf file output for royalroad, scribblehub.com and novelplanet

### ISSUE THREAD

**Issue by yudilee** [dipu-bd/lightnovel-crawler#91]
After latest update for source royalroad, scribblehub and novel planet, table is shown on epub and mobi file but because of div and table tag in chapter content so pdf output generates empty content for chapter with only tittle. I check pdf binder. It only able to read p tag so only allowed text content. I guess it also happened on docx output. On latest pull i am not use clearcontent or extract content function because that function limiting adding table and image. The method I use is get div with content and then decompose ads so all other tag is retained. 

**Let us know**
- Novel URL: https://novelplanet.com/Novel/The-Legendary-Moonlight-Sculptor
- App Version: 2.7.14
- Package: github
- OS: Ubuntu 18.04

**Comment by dipu-bd** [comment]
Generating pdf and docx is complex. Specially the current pdf maker library I am using, makes it hard to format pdf the way I want it. However, I will try to improve them or look for alternatives.

**Comment by yudilee** [comment]
Agree. need to parsing every tag and create element in pdf or docx. Aso table and image  add more complication to book making

**Comment by dipu-bd** [comment]
weasyprint is awesome! I replaced old generator with this one. Now it can generate beautiful pdfs at ease

**Comment by yudilee** [comment]
So fast. Thanks for update

**Comment by dipu-bd** [comment]
weasyprint is _way to easy_ to use. it did not require much effort. I don't know why i could not find it sooner. I suck at searching 😒
