### ISSUE TITLE
Wattpad: 'None Type' object has no attribute 'get_text' problem

### ISSUE THREAD

**Issue by Xiaowang78** [dipu-bd/lightnovel-crawler#911]
It was fine when I make epub afternoon and now when I do it, it suddenly said 'NoneType' object has no attribute 'get_text'. How to solve this?

**Comment by Galunid** [comment]
Novel url and app version??

**Comment by Xiaowang78** [comment]
https://www.wattpad.com/story/248091367?utm_source=android&utm_medium=link&utm_content=story_info&wp_page=story_details_button&wp_uname=vickyhotaru&wp_originator=%2FK2JG0MDF0YPKZbWJvRFicU6Gd6%2F%2BUlXigBrIgv9e%2Fu%2FKSXDzU0QrJfVF7hNzyxFku9GEg0E3%2BL3EkjrBRJcIH74%2Fll0Fq4KisNgdzhJbHop%2FPeLI%2B14CSAuroxL8%2FjK

What app? I use bot at Discord.

**Comment by dipu-bd** [comment]
have you tried with just this link without extra queries? 

https://www.wattpad.com/story/248091367-tgltclrf-bl-interstellar

**Comment by Xiaowang78** [comment]
Yes. I've tried. But it saying the same.

**Comment by SirGryphin** [comment]
I think it has something to do with the site won't fully load with a JS Script that it runs when you open webpage. If you view the source of the page there is a lot missing including all the HTML tags that are giving `'None Type' object has no attribute 'get_text'` error message.

I'm not sure how you get it working without using something like Selenium. Maybe I'm wrong though and over thinking it.

**Comment by yudilee** [comment]
Tried fixed in #919
