### ISSUE TITLE
[Fix this bug] COMRADEMAO 'NoneType' object has no attribute 'text'

### ISSUE THREAD

**Issue by damare01** [dipu-bd/lightnovel-crawler#915]
**Describe the bug**
'NoneType' object has no attribute 'text'

**Let us know**
- Novel URL: [https://comrademao.com/novel/unlimited-pubg-upgrade-system/]
- App Version: [v2.26.3_8]
- OS: [Windows 10]

**Comment by dipu-bd** [comment]
same as this issue: #887
