### ISSUE TITLE
pip upgrade message

### ISSUE THREAD

**Issue by SirGryphin** [dipu-bd/lightnovel-crawler#918]
@dipu-bd I don't use "normal" lightnovel-crawler normally as I mostly use my Dev version for VSCode. 

But I noticed today I was running v2.26.2 and I didn't notice there was a v2.26.3. Normally (before logo update) when I run lncrawl in command prompt it says when there's a new version out. Is there a reason I didn't get a message this time? or has it already been fixed in latest version.

**Comment by dipu-bd** [comment]
Update notice did not appear because current version 2.26.2 is less than 2.26.3, what is set in the dev branch. Recently I changed the notification option to only show update message when the available version is greater than the current one.
