### ISSUE TITLE
WeasyPrint throws errors on Windows

### ISSUE THREAD

**Issue by SirGryphin** [dipu-bd/lightnovel-crawler#92]
When I run lncrawl I get the error showing right before _? Enter novel page url or query novel:_ I don't know how to fix it, something must of change in latest version because I had no problem before updating, I've also made sure every package is up to date and still same problem.

`c:\program files (x86)\python37-32\lib\site-packages\weasyprint\fonts.py:44: UserWarning: @font-face support needs Pango >= 1.38
  warnings.warn('@font-face support needs Pango >= 1.38')
c:\program files (x86)\python37-32\lib\site-packages\weasyprint\document.py:34: UserWarning: There are known rendering problems and missing features with cairo < 1.15.4. WeasyPrint may work with older versions, but please read the note about the needed cairo version on the "Install" page of the documentation before reporting bugs. http://weasyprint.readthedocs.io/en/latest/install.html
  'There are known rendering problems and missing features with '`

- Novel URL: None
- App Version: 2.8.0
- Package: pip
- OS: Windows 10

**Comment by yudilee** [comment]
Latest update use weasyprint to generate pdf. To ensure weasyprint work, please make sure you install Pango >=1.38 and cairo <1.15.4. To install pango in windows check https://www.pango.org/Download, to install cairo you can use pip. Check it to make sure every requirement/dependency available

**Comment by SirGryphin** [comment]
I have GTK installed for windows, which Pango site recommends. I'm also 99.9% sure I have the correct and uptodate pip package for Cairo installed as well.

**Comment by yudilee** [comment]
> I have GTK installed for windows, which Pango site recommends. I'm also 99.9% sure I have the correct and uptodate pip package for Cairo installed as well.

do you still get the same error?

**Comment by dipu-bd** [comment]
I had trouble loading `cairo` in windows too. I will look for a fix ASAP

**Comment by dipu-bd** [comment]
As I further explored the issue, I found that the new pdf generation library `WeasyPrint` requires GTK+ to be installed on windows. 

https://github.com/tschoonj/GTK-for-Windows-Runtime-Environment-Installer/releases

Although it works after installing it, I can not publish EXE builds for now

**Comment by SirGryphin** [comment]
I no longer get error on Windows 10 using latest version 2.9.0 but I'm not using Windows EXE I'm using Command Prompt and PIP.

**Comment by dipu-bd** [comment]
I turned off those errors. But you probably can not generate PDF files. You have to install the GTK+ tools for that. I am looking for alternatives so that this extra dependency is not required.

**Comment by yudilee** [comment]
I found another library to generate pdf from html and it is also support TOC and cover. check this https://github.com/JazzCore/python-pdfkit need https://wkhtmltopdf.org/ but also available on linux,mac and windows.

**Comment by dipu-bd** [comment]
Maintaining third party dependencies is a lot of trouble. It would be best if any alternative without any external dependencies is found

**Comment by dipu-bd** [comment]
PDF generation is working on both Windows and Linux using pip and gtk3 runtime installed. EXE bundle has resource path problem for `cairo`
