### ISSUE TITLE
scribblehub: images and moonreader

### ISSUE THREAD

**Issue by dra6on1** [dipu-bd/lightnovel-crawler#920]
with the latest versions that include images some chapters will not been shown in moonreader epub reader. for example

https://www.scribblehub.com/series/299930/the-caretaker-of-otherworldly-tenants/

with latest chapters 18 to 20 do not show and just have 1 blank page. load in to calibre and remove the image section from the bottom of the page(under authors notes) and save fixes it.
however use an older version of lncrawler such as 2.24.1 and then have calibre download and add the external images works fine.

also these chapters are reported as having a bad id but having calibre fix that does not fix the chapters.

the offending chapters do show in other readers so may not seem much of an issue however it does point to the image adding not being perfect.

large thanks for this app.  :)

**Comment by dipu-bd** [comment]
I will check it out

**Comment by dra6on1** [comment]
i also checked the source for the page/image and it does not use "style" for the image in page either.

**Comment by dra6on1** [comment]
tested the dev branch after you made the changes and seems fix works fine. thanks.
