### ISSUE TITLE
Comic Output Format

### ISSUE THREAD

**Issue by SirGryphin** [dipu-bd/lightnovel-crawler#922]
There are a few sites that lncrawl can download from that are comic/manga. I was wondering if you could add comic output format like these. I know there just archived images to create. I don't even see just images in output format.

~~At the moment I output to PDF then use Kindle Comic Converter to make cbr.~~

Seems it doesn't put images in PDF for some reason just chapter title. I've scraped to ePUB then used Calibre to get images and manually create .cbr

.cbr (RAR)
.cbz (ZIP)
cb7 (7z)
cbt (TAR)
cba (ACE)

**Comment by dipu-bd** [comment]
Here is the code that converts epub to pdf: https://github.com/dipu-bd/lightnovel-crawler/blob/master/lncrawl/binders/calibre.py#L68

If epub has images, but pdf does not, it can be a bug in calibre.
