### ISSUE TITLE
Error: 'charmap' codec can't decode byte 0x90 in position 10915: character maps to <undefined>

### ISSUE THREAD

**Issue by joshb3** [dipu-bd/lightnovel-crawler#927]
Searched for: Kill the Hero

App Version: 2.26.3
Package: github
OS: Windows 8.1

The program shows the error at 89/93 sources, then closes after it finishes searching. Lightnovel Crawler Bot on Discord doesn't have this issue.
![image](https://user-images.githubusercontent.com/16784911/122628261-fc6bd180-d069-11eb-9807-da8b089e88a1.png)

**Comment by Alphaegen** [comment]
I tried running it as administrator and it seemed fixed it. 🤔

**Comment by Alphaegen** [comment]
It also seems to happen whenever you add quotation symbols to the input.

**Comment by joshb3** [comment]
Running as administrator didn't seem to work for me. Also searched for 'golden time', which resulted in the same error.

**Comment by dipu-bd** [comment]
try running from powershell

**Comment by dipu-bd** [comment]
similar to #892
