### ISSUE TITLE
Fix this bug Error: Error: 403 Client Error: Forbidden [id.mtlnovel.com] 

### ISSUE THREAD

**Issue by fadhilm293** [dipu-bd/lightnovel-crawler#928]
**Describe the bug**
Error: 403 Client Error: Forbidden for url: https://www.mtlnovel.com/the-strongest-qi-refiner/

**Let us know**
- Novel URL: https://id.mtlnovel.com/the-strongest-qi-refiner/
- App Version: 2.26.3
- Package: pip
- OS: Android

**Comment by dipu-bd** [comment]
already fixed. wait for new version
