### ISSUE TITLE
Error: 'cp932' codec can't decode byte 0x9b in position 10879: illegal multibyte sequence

### ISSUE THREAD

**Issue by Sabruness** [dipu-bd/lightnovel-crawler#939]
**Describe the bug**
Attempted to compile pdf of Stealing Spree on Novelhall. Chapter download count reaches 68 before failing and presenting the error message: "Error: 'cp932' codec can't decode byte 0x9b in position 10879: illegal multibyte sequence" and mentions 'Logging Error' after the message. Unsure if it's an issue with the crawler package or a source issue. 

**Let us know**
- Novel URL: https://www.novelhall.com/stealing-spree-18666/ (tried different novels on same site which presents same error message)
- App Version: 2.26.3 (also tested on Ver 2.26.2 and presents same error)
- Package: exe (not tested with any other package)
- OS: Win 10
![lncrawl error](https://user-images.githubusercontent.com/86401359/123223710-78579500-d514-11eb-94d6-ac3bc5bbe6a5.jpg)

**Comment by Sabruness** [comment]
Update: The same exact problem occurs while trying to crawl https://creativenovels.com/novel/the-villains-need-to-save-the-world/ as it gets stuck in an endless cycle of logging error. Also tested with previous 2.26.2 version and the same error occurs

**Comment by dipu-bd** [comment]
Similar to #892
