### ISSUE TITLE
When searching or using URL to download book it just gives me this error. 

### ISSUE THREAD

**Issue by Yuki75200** [dipu-bd/lightnovel-crawler#941]
![Screenshot_2021-06-25-19-55-55-99](https://user-images.githubusercontent.com/86478265/123431575-68f94a00-d5ef-11eb-9809-a3492a7419ef.jpg)

**Let us know**
- Novel URL: https://1stkissnovel.love/novel/i-have-medicine/
- App Version: 2.26.3
- OS: android

**Comment by dipu-bd** [comment]
similar to #925
