### ISSUE TITLE
Add novel info in search result

### ISSUE THREAD

**Issue by yudilee** [dipu-bd/lightnovel-crawler#95]
I think, really nice if we can add novel info (found x volume and y chapter or latest chapter tittle) in search result. So it easier for bot user to determine novel source to choose(which one more updated).

**Comment by dipu-bd** [comment]
Yes, it would be nice. I have a plan to upgrade the search results. like- combining similar results and adding more info. I will work on it next time I get free

**Comment by yudilee** [comment]
> Yes, it would be nice. I have a plan to upgrade the search results. like- combining similar results and adding more info. I will work on it next time I get free

That's great

**Comment by dipu-bd** [comment]
@yudilee Please checkout the `dev` branch. I have implemented this feature for console bot only. Help me add it to other discord and telegram bots too. I will merge it with master after it is done.

**Comment by dipu-bd** [comment]
I have added this feature in `dev` branch. For now the `search_novel` method of `core/app.py` should return a list of grouped search results. Each item should have these keys: `id`, `title`, `novels`.

The `novels` contains the list of novels. Each novel should have these keys: `title`, `url`, and `info`. You can put your short description in `info`. This field is optional. You can skip including this one when returning search results.

I have migrated console bot with this new feature. Help me migrate the telegram and discord bots too.

**Comment by yudilee** [comment]
Ok, i'll tried it out and migrate it in telegram and discord. thanks for this feature addition

**Comment by dipu-bd** [comment]
I finished adding discord bot

**Comment by dipu-bd** [comment]
Hi, I have migrated telegram bot too. The latest changes are pushed to master

**Comment by yudilee** [comment]
Thank you so much, Sorry taking too long time for me to digest the change in app and crawler. Still working on it and read email about discord bot and then this. You're so fast. I'm going to update crawler that has search function to provide info then.
