### ISSUE TITLE
www.mtlnovel.com 

### ISSUE THREAD

**Issue by stromgHold** [dipu-bd/lightnovel-crawler#953]
**Describe the bug**

**Let us know**
- Novel url :[ https://www.mtlnovel.com/i-can-talk-to-cats]

- App Version: [e.g. 2.7.8]
- Package: [can be exe, pip or`github]
- OS: [e.g. Windows 10]

This site used to work a few days ago but now it is not working or showing chapter list is empty but there are many chapters in the site 

Please please fix it.

**Comment by dipu-bd** [comment]
already fixed. please wait for the new version

**Comment by stromgHold** [comment]
Thanks a lot!!!!
