### ISSUE TITLE
Use lightnovel-crawler from python code

### ISSUE THREAD

**Issue by sandorex** [dipu-bd/lightnovel-crawler#955]
I am planning an app using kivy and wanted to use lightnovel-crwaler in it and wondering if it's possible to include it as a library ?

**Comment by dipu-bd** [comment]
yes, you can use the lightnovel-crawler as a library. the package name to import is `lncrawl`.

**Comment by dipu-bd** [comment]
No, there is no API docs. I don't plan to create one anytime soon in the future. You can tell me how you want to use it. I can help.

**Comment by sandorex** [comment]
Thank you ill look into it
