### ISSUE TITLE
Pls Fix this bug: wrong parameter for worldnovel.online

### ISSUE THREAD

**Issue by johnveyron** [dipu-bd/lightnovel-crawler#957]
**Describe the bug**
Hello devs, @yudilee , @dipu-bd ,
You seem to have taken the parameters of the web page incorrectly: https://www.worldnovel.online/. 
Novel link for checking:
https://www.worldnovel.online/novel/my-disciples-are-all-villains/

`<div class="cha-content " data-report-l1="3">`
`<div class="cha-words">`

The parameters above incorrectly captures the hidden chapter contents (in English).  

What should be Crawled is the contents in Indonesian (below).

`<div id='soop' class="post-content text-cloud font-sizer-sync">`

*this should be easy to fix quickly, hope it helps*...

**Just remove codes: `.cha-content`  and  `.cha-words`  from  `download_chapter_body` parameter.**

__Suggestion:__  you should also be able to remove the footnote  `www.worldnovel.online`

OS: bot and termux.

**Comment by dipu-bd** [comment]
This site is blocked by cloudflare captcha challenge in my region. I can't access it to test any fix.

```
 ❗ Error: Detected a Cloudflare version 2 challenge, This feature is not available in the opensource (free) version. 
```
