### ISSUE TITLE
For Telegram Bot problem with queue

### ISSUE THREAD

**Issue by yudilee** [dipu-bd/lightnovel-crawler#96]
**Describe the bug**
If Telegram bot used by multiple user at the same time, for example user A want to create epub for Monster paradise with 883 chapter and user B want to create epub for king of gods with 1119 chapter. User A ask  to bot first and then bot downloading chapter for user A. User B ask bot for king of gods and for novel info he gets 883+1119 chapter = 2002 chapter and when book generated later he get book with first 883 chapter is monster paradise chapter and 1119 chapter later is king of gods chapter. Maybe chapter url saved on the same variable.  

**Let us know**
- Novel URL: https://www.wuxiaworld.co/King-of-Gods and https://boxnovel.com/novel/monster-paradise/
- App Version: 2.8.2
- Package: pip
- OS: Ubuntu 18.10

**Comment by dipu-bd** [comment]
Please test the latest push and see if this issue is solved.

**Comment by yudilee** [comment]
It works. Thanks a lot for this fix
