### ISSUE TITLE
2.26.5 python error with win 7

### ISSUE THREAD

**Issue by dra6on1** [dipu-bd/lightnovel-crawler#969]
when the exe is run it throws up the following message before closing

Error loading Python DLL 'C:\Users\*****\AppData\Local\Temp\_MEI35722\python39.d
ll'.
No error messages generated.
FormatMessageW: The parameter is incorrect.
LoadLibrary: PyInstaller: FormatMessageW failed.

windows 7 of course can not have python 3.9 installed only up to 3.8. 2.26.3 does not have this error.
- App Version: 2.26.5
- Package: exe
- OS: Windows 7

**Comment by dipu-bd** [comment]
Download this version: https://github.com/dipu-bd/lightnovel-crawler/releases/download/v2.26.5/lncrawl-2.26.5.exe

**Comment by dra6on1** [comment]
that works. thanks.
