### ISSUE TITLE
https://noveltoon.mobi/

### ISSUE THREAD

**Issue by Viani1412** [dipu-bd/lightnovel-crawler#972]
**Describe the bug**
Can't download it 

**Let us know**
- Novel URL: https://noveltoon.mobi/id/detail/310273
- App Version: 2.26.5
- Package: discort 
- OS: android

**Comment by dipu-bd** [comment]
The site is not yet supported. This should be a source request.

**Comment by dipu-bd** [comment]
seems like it has already been requested here: #906

**Comment by Viani1412** [comment]
Sudah kga bisa ya min?
Dulu mmg mangatoon dia namanya...
Sekarang jd dua bagian mangatoon sama noveltoon

**Comment by Viani1412** [comment]
I'm so sorry for my Indonesian...
But thanks for your information...
I'll wait then
