### ISSUE TITLE
Error: list index out of range

### ISSUE THREAD

**Issue by tenco452** [dipu-bd/lightnovel-crawler#977]
Error: list index out of range in https://tunovelaligera.com/

- Novel URL: [https://tunovelaligera.com/novelas/pantasya-2020/]
- App Version: [2.26.5]
- OS: [ Windows 10, Android... All]

**Comment by dipu-bd** [comment]
this site may be out of service. I can not access it from my browser.

**Comment by dipu-bd** [comment]
@SirGryphin can you check this issue?

**Comment by SirGryphin** [comment]
This is error I get:
```
Downloading chapters |                                | 0/21Failed to download chapter body
Traceback (most recent call last):
  File "C:\Github\lightnovel-crawler\lncrawl\core\downloader.py", line 122, in download_chapter_body      
    body = app.crawler.download_chapter_body(chapter)
  File "C:\Github\lightnovel-crawler\lncrawl\sources\tunovelaligera.py", line 80, in download_chapter_body
    for bad in contents.select('h3, .code-block, script, .adsbygoogle'):
AttributeError: 'NoneType' object has no attribute 'select'
Body is empty: https://tunovelaligera.com/novelas/pantasya-2020/volumen-1-un-panadero-en-la-gran-ciudad/borrar/
Downloading chapters |█▌                              | 1/21Failed to download chapter body
```

I double check site and it because there site is broken and not list chapter text.
![tempsnip](https://user-images.githubusercontent.com/36343615/127879265-e5b4708d-2ea6-4d6c-9411-46e224529445.png)

**Comment by dipu-bd** [comment]
> I double check site and it because there site is broken and not list chapter text.

If it is broken, we should add it to not rejected sources list

**Comment by dipu-bd** [comment]
@SirGryphin can you please confirm if it is broken? I want to close this issue.

**Comment by SirGryphin** [comment]
@dipu-bd Confirm broken. Still not loading chapters, tried on multiple browsers and with VPN.
